import HexGramSchmidt
import HexMatrix

/-!
Core LLL predicates and integer state for `hex-lll`.

This module introduces the executable lattice-membership and independence
predicates used by the LLL library together with the `δ`-reducedness contract,
the Gram-Schmidt norm identities stated over those predicates, and the
all-integer `LLLState` record consumed by later algorithmic phases.
-/

namespace Hex

namespace Matrix

/-- `v` lies in the integer lattice generated by the rows of `b`. -/
def memLattice (b : Matrix Int n m) (v : Vector Int m) : Prop :=
  ∃ c : Vector Int n, rowCombination b c = v

/-- The rows of `b` are linearly independent, witnessed by positivity of each
leading principal Gram determinant. -/
def independent (b : Matrix Int n m) : Prop :=
  ∀ k : Fin n, 0 < det (submatrix (gramMatrix b) k)

/-- The identity matrix is independent: every leading principal Gram
determinant equals `det 1 = 1 > 0`. Used by Phase 4 benchmarks of
`lll.firstShortVector`, where the identity basis is the degenerate BZ-style
recombination input with all-zero lift coefficients. -/
theorem identity_independent {n : Nat} : (1 : Matrix Int n n).independent := by
  intro k
  rw [Matrix.gramMatrix_one, Matrix.submatrix_one, Matrix.det_one]
  decide

/-- Product of the squared Gram-Schmidt basis norms along the first `k` rows. -/
noncomputable def gramSchmidtNormProduct (b : Matrix Int n m) (k : Nat) (hk : k ≤ n) : Rat :=
  (List.finRange k).foldl
    (fun acc j =>
      let jn : Fin n := ⟨j.val, Nat.lt_of_lt_of_le j.isLt hk⟩
      acc * Vector.normSq ((GramSchmidt.Int.basis b).row jn))
    1

theorem gramDet_eq_prod_normSq (b : Matrix Int n m)
    (hli : b.independent) (k : Nat) (hk : k ≤ n) :
    (GramSchmidt.Int.gramDet b k hk : Rat) = gramSchmidtNormProduct b k hk := by
  sorry

theorem gramDet_pos (b : Matrix Int n m)
    (hli : b.independent) (k : Nat) (hk : k ≤ n) (hk' : 0 < k) :
    0 < GramSchmidt.Int.gramDet b k hk := by
  sorry

theorem basis_normSq (b : Matrix Int n m)
    (hli : b.independent) (k : Nat) (hk : k < n) :
    Vector.normSq ((GramSchmidt.Int.basis b).row ⟨k, hk⟩) =
      (GramSchmidt.Int.gramDet b (k + 1) (Nat.succ_le_of_lt hk) : Rat) /
        (GramSchmidt.Int.gramDet b k (Nat.le_of_lt hk) : Rat) := by
  sorry

theorem normSq_latticeVec_ge_min_basis_normSq
    (b : Matrix Int n m) (hli : b.independent)
    (v : Vector Int m) (hv : b.memLattice v) (hv' : v ≠ 0) :
    ∃ i : Fin n,
      Vector.normSq ((GramSchmidt.Int.basis b).row i) ≤ ((Vector.normSq v : Int) : Rat) := by
  sorry

end Matrix

namespace LLLCore

/-- Recover the squared norm of a Gram-Schmidt basis vector. -/
private def basisNormSq (basis : Matrix Rat n m) (i : Fin n) : Rat :=
  Vector.normSq (basis.row i)

end LLLCore

/-- A basis is `δ`-LLL-reduced when it is size-reduced and satisfies the
Lovasz condition at every adjacent pair. -/
def isLLLReduced (b : Matrix Int n m) (δ : Rat) : Prop :=
  let basis := GramSchmidt.Int.basis b
  let coeffs := GramSchmidt.Int.coeffs b
  (∀ i j, (hi : i < n) → (hji : j < i) →
      let iFin : Fin n := ⟨i, hi⟩
      let jFin : Fin n := ⟨j, Nat.lt_trans hji hi⟩
      let μ := coeffs[iFin][jFin]
      4 * μ * μ ≤ 1) ∧
    ∀ i, (hi : i + 1 < n) →
      let iFin : Fin n := ⟨i, Nat.lt_trans (Nat.lt_succ_self i) hi⟩
      let ip1Fin : Fin n := ⟨i + 1, hi⟩
      let μ := coeffs[ip1Fin][iFin]
      δ * LLLCore.basisNormSq basis iFin ≤
        LLLCore.basisNormSq basis ip1Fin + μ * μ * LLLCore.basisNormSq basis iFin

/-- Integer-only state for later LLL reduction steps. The proof-facing fields
connect the stored Gram determinants and scaled coefficients to the
noncomputable Gram-Schmidt projections of `b`. -/
structure LLLState (n m : Nat) where
  b : Matrix Int n m
  ν : Matrix Int n n
  d : Vector Nat (n + 1)
  ν_eq : ∀ i j, (hi : i < n) → (hj : j < n) → j < i →
      ((ν.get ⟨i, hi⟩).get ⟨j, hj⟩ : Rat) =
        (d.get ⟨j + 1, Nat.succ_lt_succ hj⟩ : Rat) *
          ((GramSchmidt.Int.coeffs b).get ⟨i, hi⟩).get ⟨j, hj⟩
  d_eq : ∀ i, (hi : i < n + 1) →
      d.get ⟨i, hi⟩ = GramSchmidt.Int.gramDet b i (Nat.le_of_lt_succ hi)

namespace LLLState

/-- Integer nearest-quotient used by the LLL size-reduction test. -/
private def nearestQuotient (νjk : Int) (dj1 : Nat) : Int :=
  Int.fdiv (2 * νjk + Int.ofNat dj1) (2 * Int.ofNat dj1)

/-- Targeted matrix entry update for LLL's integer coefficient state. -/
private def setEntry (M : Matrix Int n n) (i j : Fin n) (x : Int) : Matrix Int n n :=
  M.set i ((M.get i).set j x)

private theorem foldl_set_outerSubMul_get_eq
    {n : Nat} (xs : List (Fin n))
    (base outerK outerJ : Vector Int n) (r : Int) (l : Fin n) :
    (xs.foldl
        (fun (row : Vector Int n) (i : Fin n) =>
          row.set i (outerK.get i - r * outerJ.get i))
        base).get l =
      if (∃ i ∈ xs, i.val = l.val) then
        outerK.get l - r * outerJ.get l
      else
        base.get l := by
  induction xs generalizing base with
  | nil => simp
  | cons x xs ih =>
    simp only [List.foldl_cons]
    rw [ih]
    by_cases h_xs : ∃ i ∈ xs, i.val = l.val
    · have h_cons : ∃ i ∈ x :: xs, i.val = l.val := by
        obtain ⟨i, hi, hi_l⟩ := h_xs
        exact ⟨i, List.mem_cons.mpr (Or.inr hi), hi_l⟩
      simp [h_xs, h_cons]
    · by_cases h_xl : x.val = l.val
      · have h_cons : ∃ i ∈ x :: xs, i.val = l.val :=
          ⟨x, List.mem_cons.mpr (Or.inl rfl), h_xl⟩
        have h_xeq : x = l := Fin.eq_of_val_eq h_xl
        subst h_xeq
        simp only [h_xs, ↓reduceIte, h_cons]
        change (base.set x.val (outerK.get x - r * outerJ.get x) x.isLt)[x.val] = _
        exact Vector.getElem_set_self x.isLt
      · have h_cons : ¬ ∃ i ∈ x :: xs, i.val = l.val := by
          rintro ⟨i, hi, hi_l⟩
          rcases List.mem_cons.mp hi with rfl | hxs
          · exact h_xl hi_l
          · exact h_xs ⟨i, hxs, hi_l⟩
        simp only [h_xs, ↓reduceIte, h_cons]
        change (base.set x.val (outerK.get x - r * outerJ.get x) x.isLt)[l.val] = base[l.val]
        exact Vector.getElem_set_ne x.isLt l.isLt h_xl

private theorem foldl_finRange_set_outerSubMul_get_eq
    {n : Nat} (jVal : Nat) (hjn : jVal ≤ n)
    (base outerK outerJ : Vector Int n) (r : Int) (l : Fin n) :
    ((List.finRange jVal).foldl
        (fun (row : Vector Int n) (l' : Fin jVal) =>
          let lFin : Fin n := ⟨l'.val, Nat.lt_of_lt_of_le l'.isLt hjn⟩
          row.set lFin (outerK.get lFin - r * outerJ.get lFin))
        base).get l =
      if l.val < jVal then
        outerK.get l - r * outerJ.get l
      else
        base.get l := by
  let cast : Fin jVal → Fin n :=
    fun l' => ⟨l'.val, Nat.lt_of_lt_of_le l'.isLt hjn⟩
  show ((List.finRange jVal).foldl
        (fun (row : Vector Int n) (l' : Fin jVal) =>
          row.set (cast l') (outerK.get (cast l') - r * outerJ.get (cast l')))
        base).get l = _
  rw [show ((List.finRange jVal).foldl
        (fun (row : Vector Int n) (l' : Fin jVal) =>
          row.set (cast l') (outerK.get (cast l') - r * outerJ.get (cast l')))
        base) =
      ((List.finRange jVal).map cast).foldl
        (fun (row : Vector Int n) (i : Fin n) =>
          row.set i (outerK.get i - r * outerJ.get i))
        base from
      (@List.foldl_map (Fin jVal) (Fin n) (Vector Int n) cast
        (fun row i => row.set i (outerK.get i - r * outerJ.get i))
        (List.finRange jVal) base).symm]
  rw [foldl_set_outerSubMul_get_eq]
  by_cases hlj : l.val < jVal
  · have hex : ∃ i ∈ (List.finRange jVal).map cast, i.val = l.val := by
      refine ⟨⟨l.val, Nat.lt_of_lt_of_le hlj hjn⟩, ?_, rfl⟩
      rw [List.mem_map]
      exact ⟨⟨l.val, hlj⟩, List.mem_finRange _, rfl⟩
    rw [if_pos hex, if_pos hlj]
  · have hno : ¬ ∃ i ∈ (List.finRange jVal).map cast, i.val = l.val := by
      rintro ⟨i, hi_mem, hi_eq⟩
      rw [List.mem_map] at hi_mem
      obtain ⟨l', _, hl'⟩ := hi_mem
      have hcast : (cast l').val = l'.val := rfl
      have : l.val < jVal := by
        rw [← hi_eq, ← hl', hcast]
        exact l'.isLt
      exact hlj this
    rw [if_neg hno, if_neg hlj]

/-- Single-column size reduction update for row `k` against row `j`. -/
def sizeReduceColumn (s : LLLState n m) (j k : Fin n) (hjk : j.val < k.val) :
    LLLState n m :=
  let νjk := (s.ν.get k).get j
  let dj1 := s.d.get ⟨j.val + 1, Nat.succ_lt_succ j.isLt⟩
  if hreduce : 2 * Int.natAbs νjk > dj1 then
    let r := nearestQuotient νjk dj1
    let b' := GramSchmidt.Int.sizeReduce s.b j k r
    let rowK :=
      (List.finRange j.val).foldl
        (fun row l =>
          let lFin : Fin n := ⟨l.val, Nat.lt_trans l.isLt j.isLt⟩
          row.set lFin ((s.ν.get k).get lFin - r * (s.ν.get j).get lFin))
        (s.ν.get k)
    let rowK := rowK.set j ((s.ν.get k).get j - r * Int.ofNat dj1)
    let ν' : Matrix Int n n :=
      s.ν.set k rowK
    { b := b'
      ν := ν'
      d := s.d
      ν_eq := by
        intro i l hi hl hli
        by_cases hik : i = k.val
        · -- Row i is row k. Subdivide on l vs j.val.
          subst hik
          -- ν'.get ⟨k.val, hi⟩ = rowK
          have hν_get_k : ν'.get ⟨k.val, hi⟩ = rowK := by
            change (s.ν.set k.val rowK k.isLt)[k.val] = rowK
            exact Vector.getElem_set_self k.isLt
          rw [hν_get_k]
          rcases Nat.lt_trichotomy l j.val with hlj | hlj | hlj
          · -- Case B: l < j.val. rowK[l] = (s.ν.get k).get l - r * (s.ν.get j).get l
            have h_lne_j : l ≠ j.val := Nat.ne_of_lt hlj
            have h_rowK_get : rowK.get ⟨l, hl⟩ =
                (s.ν.get k).get ⟨l, hl⟩ - r * (s.ν.get j).get ⟨l, hl⟩ := by
              change (((List.finRange j.val).foldl
                  (fun row l' =>
                    let lFin : Fin n := ⟨l'.val, Nat.lt_trans l'.isLt j.isLt⟩
                    row.set lFin ((s.ν.get k).get lFin - r * (s.ν.get j).get lFin))
                  (s.ν.get k)).set j.val ((s.ν.get k).get j - r * Int.ofNat dj1)
                  j.isLt)[l] = _
              rw [Vector.getElem_set_ne j.isLt hl (Ne.symm h_lne_j)]
              have h := foldl_finRange_set_outerSubMul_get_eq j.val
                (Nat.le_of_lt j.isLt) (s.ν.get k) (s.ν.get k) (s.ν.get j) r ⟨l, hl⟩
              rw [if_pos hlj] at h
              exact h
            rw [h_rowK_get]
            push_cast
            have h_νkl : ((s.ν.get k).get ⟨l, hl⟩ : Rat) =
                (s.d.get ⟨l + 1, Nat.succ_lt_succ hl⟩ : Rat) *
                  ((GramSchmidt.Int.coeffs s.b).get k).get ⟨l, hl⟩ :=
              s.ν_eq k.val l k.isLt hl hli
            have h_νjl : ((s.ν.get j).get ⟨l, hl⟩ : Rat) =
                (s.d.get ⟨l + 1, Nat.succ_lt_succ hl⟩ : Rat) *
                  ((GramSchmidt.Int.coeffs s.b).get j).get ⟨l, hl⟩ :=
              s.ν_eq j.val l j.isLt hl hlj
            have h_coeff_lower :
                ((GramSchmidt.Int.coeffs b').get ⟨k.val, hi⟩).get ⟨l, hl⟩ =
                  ((GramSchmidt.Int.coeffs s.b).get ⟨k.val, hi⟩).get ⟨l, hl⟩ -
                    (r : Rat) * ((GramSchmidt.Int.coeffs s.b).get ⟨j.val, j.isLt⟩).get
                      ⟨l, Nat.lt_trans hlj j.isLt⟩ :=
              GramSchmidt.Int.coeffs_sizeReduce_lower s.b ⟨l, hl⟩ j k hlj hjk r
            rw [h_coeff_lower, h_νkl, h_νjl]
            grind
          · -- Case C: l = j.val
            sorry
          · -- Case D: l > j.val
            sorry
        · -- Row i ≠ k.val: ν' agrees with s.ν, and coeffs(b') agrees with coeffs(s.b)
          -- on row i, so this case reduces to s.ν_eq directly.
          have hik_fin : (⟨i, hi⟩ : Fin n) ≠ k := fun h => hik (congrArg Fin.val h)
          have hν_get : (ν'.get ⟨i, hi⟩) = s.ν.get ⟨i, hi⟩ := by
            change (s.ν.set k.val rowK k.isLt).get ⟨i, hi⟩ = s.ν.get ⟨i, hi⟩
            change (s.ν.set k.val rowK k.isLt)[i] = s.ν[i]
            exact Vector.getElem_set_ne k.isLt hi (fun h => hik h.symm)
          have hcoeff_row :
              (GramSchmidt.Int.coeffs b').get ⟨i, hi⟩ =
                (GramSchmidt.Int.coeffs s.b).get ⟨i, hi⟩ :=
            GramSchmidt.Int.coeffs_sizeReduce_other_row s.b j k hjk r ⟨i, hi⟩ hik_fin
          rw [hν_get, hcoeff_row]
          exact s.ν_eq i l hi hl hli
      d_eq := by
        intro i hi
        dsimp only [b']
        rw [GramSchmidt.Int.gramDet_sizeReduce s.b j k hjk r i (Nat.le_of_lt_succ hi)]
        exact s.d_eq i hi }
  else
    s

/-- Size-reduce row `k` against each earlier row using the stored integer
scaled coefficients. -/
def sizeReduce (s : LLLState n m) (k : Nat) : LLLState n m :=
  if hk : k < n then
    let kFin : Fin n := ⟨k, hk⟩
    ((List.finRange k).reverse).foldl
      (fun state j =>
        let jFin : Fin n := ⟨j.val, Nat.lt_trans j.isLt hk⟩
        LLLState.sizeReduceColumn state jFin kFin j.isLt)
      s
  else
    s

/-- Swap adjacent rows `k - 1` and `k`, updating the stored scaled coefficients
and Gram determinants with the integer formulas from the LLL specification. -/
def swapStep (s : LLLState n m) (k : Nat) : LLLState n m :=
  if hk : k < n then
    if hk0 : 0 < k then
      let kFin : Fin n := ⟨k, hk⟩
      let km1 : Fin n := GramSchmidt.prevRow kFin hk0
      let B := (s.ν.get kFin).get km1
      let dkPrev := s.d.get ⟨km1.val, Nat.lt_succ_of_lt km1.isLt⟩
      let dk := s.d.get ⟨k, Nat.lt_succ_of_lt hk⟩
      let dkNext := s.d.get ⟨k + 1, Nat.succ_lt_succ hk⟩
      let dk' : Nat :=
        Int.toNat (((Int.ofNat dkNext * Int.ofNat dkPrev + B ^ 2) / Int.ofNat dk))
      let b' := GramSchmidt.Int.adjacentSwap s.b kFin hk0
      let d' : Vector Nat (n + 1) :=
        s.d.set k dk' (h := Nat.lt_succ_of_lt hk)
      let νRowsSwapped :=
        (List.finRange km1.val).foldl
          (fun ν j =>
            let jFin : Fin n := ⟨j.val, Nat.lt_trans j.isLt km1.isLt⟩
            let ν := setEntry ν km1 jFin ((s.ν.get kFin).get jFin)
            setEntry ν kFin jFin ((s.ν.get km1).get jFin))
          s.ν
      let νPivot := setEntry νRowsSwapped kFin km1 B
      let ν' : Matrix Int n n :=
        (List.finRange n).foldl
          (fun ν i =>
            if hklt : k < i.val then
              let prev :=
                (Int.ofNat dkPrev * (s.ν.get i).get kFin + B * (s.ν.get i).get km1) /
                  Int.ofNat dk
              let curr :=
                (Int.ofNat dkNext * (s.ν.get i).get km1 - B * (s.ν.get i).get kFin) /
                  Int.ofNat dk
              let ν := setEntry ν i km1 prev
              setEntry ν i kFin curr
            else
              ν)
          νPivot
      { b := b'
        ν := ν'
        d := d'
        ν_eq := by
          intro i j hi hj hij
          sorry
        d_eq := by
          intro i hi
          sorry }
    else
      s
  else
    s

/-- Size reduction leaves the stored Gram determinants unchanged. -/
theorem sizeReduce_d (s : LLLState n m) (k : Nat) :
    (s.sizeReduce k).d = s.d := by
  sorry

/-- Size reduction preserves the Gram-Schmidt basis of the state basis matrix. -/
theorem sizeReduce_basis (s : LLLState n m) (k : Nat) :
    GramSchmidt.Int.basis (s.sizeReduce k).b = GramSchmidt.Int.basis s.b := by
  sorry

/-- Adjacent swaps preserve the generated lattice. -/
theorem swapStep_memLattice_iff (s : LLLState n m) (k : Nat) (v : Vector Int m) :
    Matrix.memLattice (s.swapStep k).b v ↔ Matrix.memLattice s.b v := by
  sorry

/-- The updated swap state still packages the intended scaled coefficient
representation for its basis. -/
theorem swapStep_ν_eq
    (s : LLLState n m) (k : Nat)
    (i j : Nat) (hi : i < n) (hj : j < n) (hji : j < i) :
    (((s.swapStep k).ν.get ⟨i, hi⟩).get ⟨j, hj⟩ : Rat) =
      (((s.swapStep k).d.get ⟨j + 1, Nat.succ_lt_succ hj⟩ : Nat) : Rat) *
        (((GramSchmidt.Int.coeffs (s.swapStep k).b).get ⟨i, hi⟩).get ⟨j, hj⟩) := by
  simpa using (s.swapStep k).ν_eq i j hi hj hji

/-- The updated swap state still packages the intended Gram-determinant
representation for its basis. -/
theorem swapStep_d_eq (s : LLLState n m) (k i : Nat) (hi : i < n + 1) :
    (s.swapStep k).d.get ⟨i, hi⟩ =
      GramSchmidt.Int.gramDet (s.swapStep k).b i (Nat.le_of_lt_succ hi) := by
  simpa using (s.swapStep k).d_eq i hi

/-- Recover a single rational Gram-Schmidt coefficient from the integer state.
This exists for the proof layer; later executable code continues to work over
the stored integer data. -/
noncomputable def gramSchmidtCoeff (s : LLLState n m) (i j : Nat)
    (hi : i < n) (hj : j < n) : Rat :=
  (((s.ν.get ⟨i, hi⟩).get ⟨j, hj⟩ : Int) : Rat) / (s.d.get ⟨j + 1, Nat.succ_lt_succ hj⟩ : Rat)

/-- The multiplicative potential used by the LLL termination argument:
`d₁ * ... * dₙ₋₁`. -/
def potential (s : LLLState n m) : Nat :=
  (List.finRange (n - 1)).foldl
    (fun acc i =>
      acc * s.d.get
        ⟨i.val + 1, Nat.succ_lt_succ (Nat.lt_of_lt_of_le i.isLt (Nat.sub_le n 1))⟩)
    1

/-- Unfold the termination potential through the state's Gram-determinant
certificate. The product only ranges over `d₁, ..., dₙ₋₁`, so later
termination proofs do not need to reason about `dₙ`. -/
theorem potential_eq_gramDetProduct (s : LLLState n m) :
    s.potential =
      (List.finRange (n - 1)).foldl
        (fun acc i =>
          acc * GramSchmidt.Int.gramDet s.b (i.val + 1)
            (Nat.succ_le_of_lt (Nat.lt_of_lt_of_le i.isLt (Nat.sub_le n 1))))
        1 := by
  simp [potential, s.d_eq]

/-- Initial `LLLState` constructor: build the integer state directly from a
basis matrix. The `ν` field is the integral scaled Gram-Schmidt coefficient
matrix and the `d` field is the leading Gram-determinant vector. The proof
fields are discharged by composing `GramSchmidt.Int.scaledCoeffs_eq` with
`GramSchmidt.Int.gramDetVec_eq_gramDet`. -/
def ofBasis (b : Matrix Int n m) (_hind : b.independent) : LLLState n m :=
  { b
    ν := GramSchmidt.Int.scaledCoeffs b
    d := GramSchmidt.Int.gramDetVec b
    ν_eq := by
      intro i j hi hj hji
      rw [GramSchmidt.Int.gramDetVec_eq_gramDet]
      simpa [GramSchmidt.entry, Matrix.row] using
        GramSchmidt.Int.scaledCoeffs_eq b i j hi hji
    d_eq := by
      intro i hi
      exact GramSchmidt.Int.gramDetVec_eq_gramDet b i (Nat.le_of_lt_succ hi) }

end LLLState

/-- Outer LLL loop, dispatched by `lll`.

At row `k`, the loop size-reduces the current row, checks the integer
Lovasz condition, and either advances to `k + 1` or swaps adjacent rows and
continues from the previous position. -/
def lllAux (s : LLLState n m) (k : Nat) (δ : Rat)
    (hδ : 1/4 < δ) (hδ' : δ ≤ 1) (hind : s.b.independent)
    (hk : 1 ≤ k) (hkn : k ≤ n) : Matrix Int n m :=
  if hdone : k = n then
    s.b
  else
    have hlt : k < n := Nat.lt_of_le_of_ne hkn hdone
    have hkm1lt : k - 1 < n :=
      Nat.lt_of_le_of_lt (Nat.sub_le k 1) hlt
    let sReduced := s.sizeReduce k
    let kFin : Fin n := ⟨k, hlt⟩
    let km1Fin : Fin n := ⟨k - 1, hkm1lt⟩
    let dkPrev := sReduced.d.get
      ⟨k - 1, Nat.lt_trans hkm1lt (Nat.lt_succ_self n)⟩
    let dk := sReduced.d.get ⟨k, Nat.lt_succ_of_lt hlt⟩
    let dkNext := sReduced.d.get ⟨k + 1, Nat.succ_lt_succ hlt⟩
    let B := (sReduced.ν.get kFin).get km1Fin
    let lovaszLhs : Int :=
      Int.ofNat δ.den * (Int.ofNat dkNext * Int.ofNat dkPrev + B ^ 2)
    let lovaszRhs : Int :=
      δ.num * (Int.ofNat dk ^ 2)
    if lovaszLhs ≥ lovaszRhs then
      lllAux sReduced (k + 1) δ hδ hδ'
        (by
          sorry)
        (Nat.succ_pos k) (Nat.succ_le_of_lt hlt)
    else
      let sSwapped := sReduced.swapStep k
      let k' := max (k - 1) 1
      lllAux sSwapped k' δ hδ hδ'
        (by
          sorry)
        (Nat.le_max_right (k - 1) 1)
        (by
          exact (Nat.max_le).2
            ⟨Nat.le_trans (Nat.sub_le k 1) hkn, Nat.le_trans hk hkn⟩)
termination_by (s.potential, n - k)
decreasing_by
  all_goals sorry

/-- Top-level LLL entry point. Builds the canonical integer state via
`LLLState.ofBasis` and dispatches to `lllAux`. The proof obligations of
`LLLState.ofBasis` are discharged inside the constructor itself, so the
body of `lll` has no deferred proof terms. -/
def lll (b : Matrix Int n m) (δ : Rat)
    (hδ : 1/4 < δ) (hδ' : δ ≤ 1) (hn : 1 ≤ n) (hind : b.independent) :
    Matrix Int n m :=
  lllAux (LLLState.ofBasis b hind) 1 δ hδ hδ' hind (Nat.le_refl 1) hn

/-- The first row of the reduced basis (shortest vector under the LLL
guarantee). Canonical short-vector entry point for downstream consumers
such as `hex-berlekamp-zassenhaus` recombination. -/
def lll.firstShortVector (b : Matrix Int n m) (δ : Rat)
    (hδ : 1/4 < δ) (hδ' : δ ≤ 1) (hn : 1 ≤ n) (hind : b.independent) :
    Vector Int m :=
  (lll b δ hδ hδ' hn hind)[0]

/-- The full reduced basis viewed as an ordered array of candidate short
vectors. -/
def lll.shortVectors (b : Matrix Int n m) (δ : Rat)
    (hδ : 1/4 < δ) (hδ' : δ ≤ 1) (hn : 1 ≤ n) (hind : b.independent) :
    Array (Vector Int m) :=
  (lll b δ hδ hδ' hn hind).toArray

end Hex
