/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.CompatibilityCore
public import HexConway.CompatibilityProofs.S0_0

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Compatibility of C(283, 2) with C(283, 4). -/
theorem compat_283_2_4 :
    Compatible 283 2 4 supportedEntry_283_2 supportedEntry_283_4 := by decide +kernel

/-- Compatibility of C(349, 2) with C(349, 4). -/
theorem compat_349_2_4 :
    Compatible 349 2 4 supportedEntry_349_2 supportedEntry_349_4 := by decide +kernel

/-- Compatibility of C(367, 2) with C(367, 4). -/
theorem compat_367_2_4 :
    Compatible 367 2 4 supportedEntry_367_2 supportedEntry_367_4 := by decide +kernel

/-- Compatibility of C(397, 2) with C(397, 4). -/
theorem compat_397_2_4 :
    Compatible 397 2 4 supportedEntry_397_2 supportedEntry_397_4 := by decide +kernel

/-- Compatibility of C(431, 2) with C(431, 4). -/
theorem compat_431_2_4 :
    Compatible 431 2 4 supportedEntry_431_2 supportedEntry_431_4 := by decide +kernel

/-- Compatibility of C(457, 2) with C(457, 4). -/
theorem compat_457_2_4 :
    Compatible 457 2 4 supportedEntry_457_2 supportedEntry_457_4 := by decide +kernel

/-- Compatibility of C(487, 2) with C(487, 4). -/
theorem compat_487_2_4 :
    Compatible 487 2 4 supportedEntry_487_2 supportedEntry_487_4 := by decide +kernel

/-- Compatibility of C(2, 4) with C(2, 8). -/
theorem compat_2_4_8 :
    Compatible 2 4 8 supportedEntry_2_4 supportedEntry_2_8 := by decide +kernel

/-- Compatibility of C(131, 1) with C(131, 4). -/
theorem compat_131_1_4 :
    Compatible 131 1 4 supportedEntry_131_1 supportedEntry_131_4 := by decide +kernel

/-- Compatibility of C(139, 1) with C(139, 4). -/
theorem compat_139_1_4 :
    Compatible 139 1 4 supportedEntry_139_1 supportedEntry_139_4 := by decide +kernel

/-- Compatibility of C(151, 1) with C(151, 4). -/
theorem compat_151_1_4 :
    Compatible 151 1 4 supportedEntry_151_1 supportedEntry_151_4 := by decide +kernel

/-- Compatibility of C(179, 1) with C(179, 4). -/
theorem compat_179_1_4 :
    Compatible 179 1 4 supportedEntry_179_1 supportedEntry_179_4 := by decide +kernel

/-- Compatibility of C(197, 1) with C(197, 4). -/
theorem compat_197_1_4 :
    Compatible 197 1 4 supportedEntry_197_1 supportedEntry_197_4 := by decide +kernel

/-- Compatibility of C(227, 1) with C(227, 4). -/
theorem compat_227_1_4 :
    Compatible 227 1 4 supportedEntry_227_1 supportedEntry_227_4 := by decide +kernel

/-- Compatibility of C(241, 1) with C(241, 4). -/
theorem compat_241_1_4 :
    Compatible 241 1 4 supportedEntry_241_1 supportedEntry_241_4 := by decide +kernel

/-- Compatibility of C(2, 1) with C(2, 9). -/
theorem compat_2_1_9 :
    Compatible 2 1 9 supportedEntry_2_1 supportedEntry_2_9 := by decide +kernel

/-- Compatibility of C(257, 2) with C(257, 4). -/
theorem compat_257_2_4 :
    Compatible 257 2 4 supportedEntry_257_2 supportedEntry_257_4 := by decide +kernel

/-- Compatibility of C(383, 2) with C(383, 4). -/
theorem compat_383_2_4 :
    Compatible 383 2 4 supportedEntry_383_2 supportedEntry_383_4 := by decide +kernel

/-- Compatibility of C(67, 2) with C(67, 4). -/
theorem compat_67_2_4 :
    Compatible 67 2 4 supportedEntry_67_2 supportedEntry_67_4 := by decide +kernel

/-- Compatibility of C(89, 2) with C(89, 4). -/
theorem compat_89_2_4 :
    Compatible 89 2 4 supportedEntry_89_2 supportedEntry_89_4 := by decide +kernel

/-- Compatibility of C(109, 2) with C(109, 4). -/
theorem compat_109_2_4 :
    Compatible 109 2 4 supportedEntry_109_2 supportedEntry_109_4 := by decide +kernel

/-- Compatibility of C(5, 2) with C(5, 6). -/
theorem compat_5_2_6 :
    Compatible 5 2 6 supportedEntry_5_2 supportedEntry_5_6 := by decide +kernel

/-- Compatibility of C(7, 3) with C(7, 6). -/
theorem compat_7_3_6 :
    Compatible 7 3 6 supportedEntry_7_3 supportedEntry_7_6 := by decide +kernel

/-- Compatibility of C(193, 2) with C(193, 4). -/
theorem compat_193_2_4 :
    Compatible 193 2 4 supportedEntry_193_2 supportedEntry_193_4 := by decide +kernel


end Conway

end Hex
