/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.CompatibilityCore
public import HexConway.CompatibilityProofs.S0_2

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Compatibility of C(281, 1) with C(281, 3). -/
theorem compat_281_1_3 :
    Compatible 281 1 3 supportedEntry_281_1 supportedEntry_281_3 := by decide +kernel

/-- Compatibility of C(337, 1) with C(337, 3). -/
theorem compat_337_1_3 :
    Compatible 337 1 3 supportedEntry_337_1 supportedEntry_337_3 := by decide +kernel

/-- Compatibility of C(367, 1) with C(367, 3). -/
theorem compat_367_1_3 :
    Compatible 367 1 3 supportedEntry_367_1 supportedEntry_367_3 := by decide +kernel

/-- Compatibility of C(421, 1) with C(421, 3). -/
theorem compat_421_1_3 :
    Compatible 421 1 3 supportedEntry_421_1 supportedEntry_421_3 := by decide +kernel

/-- Compatibility of C(461, 1) with C(461, 3). -/
theorem compat_461_1_3 :
    Compatible 461 1 3 supportedEntry_461_1 supportedEntry_461_3 := by decide +kernel

/-- Compatibility of C(7, 1) with C(7, 5). -/
theorem compat_7_1_5 :
    Compatible 7 1 5 supportedEntry_7_1 supportedEntry_7_5 := by decide +kernel

/-- Compatibility of C(151, 1) with C(151, 3). -/
theorem compat_151_1_3 :
    Compatible 151 1 3 supportedEntry_151_1 supportedEntry_151_3 := by decide +kernel

/-- Compatibility of C(239, 1) with C(239, 3). -/
theorem compat_239_1_3 :
    Compatible 239 1 3 supportedEntry_239_1 supportedEntry_239_3 := by decide +kernel

/-- Compatibility of C(577, 1) with C(577, 3). -/
theorem compat_577_1_3 :
    Compatible 577 1 3 supportedEntry_577_1 supportedEntry_577_3 := by decide +kernel

/-- Compatibility of C(673, 1) with C(673, 3). -/
theorem compat_673_1_3 :
    Compatible 673 1 3 supportedEntry_673_1 supportedEntry_673_3 := by decide +kernel

/-- Compatibility of C(743, 1) with C(743, 3). -/
theorem compat_743_1_3 :
    Compatible 743 1 3 supportedEntry_743_1 supportedEntry_743_3 := by decide +kernel

/-- Compatibility of C(827, 1) with C(827, 3). -/
theorem compat_827_1_3 :
    Compatible 827 1 3 supportedEntry_827_1 supportedEntry_827_3 := by decide +kernel

/-- Compatibility of C(929, 1) with C(929, 3). -/
theorem compat_929_1_3 :
    Compatible 929 1 3 supportedEntry_929_1 supportedEntry_929_3 := by decide +kernel

/-- Compatibility of C(11, 1) with C(11, 4). -/
theorem compat_11_1_4 :
    Compatible 11 1 4 supportedEntry_11_1 supportedEntry_11_4 := by decide +kernel

/-- Compatibility of C(313, 1) with C(313, 3). -/
theorem compat_313_1_3 :
    Compatible 313 1 3 supportedEntry_313_1 supportedEntry_313_3 := by decide +kernel

/-- Compatibility of C(401, 1) with C(401, 3). -/
theorem compat_401_1_3 :
    Compatible 401 1 3 supportedEntry_401_1 supportedEntry_401_3 := by decide +kernel

/-- Compatibility of C(467, 1) with C(467, 3). -/
theorem compat_467_1_3 :
    Compatible 467 1 3 supportedEntry_467_1 supportedEntry_467_3 := by decide +kernel

/-- Compatibility of C(509, 1) with C(509, 3). -/
theorem compat_509_1_3 :
    Compatible 509 1 3 supportedEntry_509_1 supportedEntry_509_3 := by decide +kernel

/-- Compatibility of C(2, 2) with C(2, 6). -/
theorem compat_2_2_6 :
    Compatible 2 2 6 supportedEntry_2_2 supportedEntry_2_6 := by decide +kernel

/-- Compatibility of C(157, 1) with C(157, 3). -/
theorem compat_157_1_3 :
    Compatible 157 1 3 supportedEntry_157_1 supportedEntry_157_3 := by decide +kernel

/-- Compatibility of C(199, 1) with C(199, 3). -/
theorem compat_199_1_3 :
    Compatible 199 1 3 supportedEntry_199_1 supportedEntry_199_3 := by decide +kernel

/-- Compatibility of C(241, 1) with C(241, 3). -/
theorem compat_241_1_3 :
    Compatible 241 1 3 supportedEntry_241_1 supportedEntry_241_3 := by decide +kernel

/-- Compatibility of C(773, 1) with C(773, 3). -/
theorem compat_773_1_3 :
    Compatible 773 1 3 supportedEntry_773_1 supportedEntry_773_3 := by decide +kernel

/-- Compatibility of C(83, 1) with C(83, 3). -/
theorem compat_83_1_3 :
    Compatible 83 1 3 supportedEntry_83_1 supportedEntry_83_3 := by decide +kernel


end Conway

end Hex
