/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.CompatibilityCore
public import HexConway.CompatibilityProofs.S1_2

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Compatibility of C(347, 1) with C(347, 3). -/
theorem compat_347_1_3 :
    Compatible 347 1 3 supportedEntry_347_1 supportedEntry_347_3 := by decide +kernel

/-- Compatibility of C(379, 1) with C(379, 3). -/
theorem compat_379_1_3 :
    Compatible 379 1 3 supportedEntry_379_1 supportedEntry_379_3 := by decide +kernel

/-- Compatibility of C(439, 1) with C(439, 3). -/
theorem compat_439_1_3 :
    Compatible 439 1 3 supportedEntry_439_1 supportedEntry_439_3 := by decide +kernel

/-- Compatibility of C(491, 1) with C(491, 3). -/
theorem compat_491_1_3 :
    Compatible 491 1 3 supportedEntry_491_1 supportedEntry_491_3 := by decide +kernel

/-- Compatibility of C(137, 1) with C(137, 3). -/
theorem compat_137_1_3 :
    Compatible 137 1 3 supportedEntry_137_1 supportedEntry_137_3 := by decide +kernel

/-- Compatibility of C(149, 1) with C(149, 3). -/
theorem compat_149_1_3 :
    Compatible 149 1 3 supportedEntry_149_1 supportedEntry_149_3 := by decide +kernel

/-- Compatibility of C(229, 1) with C(229, 3). -/
theorem compat_229_1_3 :
    Compatible 229 1 3 supportedEntry_229_1 supportedEntry_229_3 := by decide +kernel

/-- Compatibility of C(569, 1) with C(569, 3). -/
theorem compat_569_1_3 :
    Compatible 569 1 3 supportedEntry_569_1 supportedEntry_569_3 := by decide +kernel

/-- Compatibility of C(641, 1) with C(641, 3). -/
theorem compat_641_1_3 :
    Compatible 641 1 3 supportedEntry_641_1 supportedEntry_641_3 := by decide +kernel

/-- Compatibility of C(727, 1) with C(727, 3). -/
theorem compat_727_1_3 :
    Compatible 727 1 3 supportedEntry_727_1 supportedEntry_727_3 := by decide +kernel

/-- Compatibility of C(797, 1) with C(797, 3). -/
theorem compat_797_1_3 :
    Compatible 797 1 3 supportedEntry_797_1 supportedEntry_797_3 := by decide +kernel

/-- Compatibility of C(887, 1) with C(887, 3). -/
theorem compat_887_1_3 :
    Compatible 887 1 3 supportedEntry_887_1 supportedEntry_887_3 := by decide +kernel

/-- Compatibility of C(983, 1) with C(983, 3). -/
theorem compat_983_1_3 :
    Compatible 983 1 3 supportedEntry_983_1 supportedEntry_983_3 := by decide +kernel

/-- Compatibility of C(353, 1) with C(353, 3). -/
theorem compat_353_1_3 :
    Compatible 353 1 3 supportedEntry_353_1 supportedEntry_353_3 := by decide +kernel

/-- Compatibility of C(433, 1) with C(433, 3). -/
theorem compat_433_1_3 :
    Compatible 433 1 3 supportedEntry_433_1 supportedEntry_433_3 := by decide +kernel

/-- Compatibility of C(487, 1) with C(487, 3). -/
theorem compat_487_1_3 :
    Compatible 487 1 3 supportedEntry_487_1 supportedEntry_487_3 := by decide +kernel

/-- Compatibility of C(79, 1) with C(79, 3). -/
theorem compat_79_1_3 :
    Compatible 79 1 3 supportedEntry_79_1 supportedEntry_79_3 := by decide +kernel

/-- Compatibility of C(2, 3) with C(2, 6). -/
theorem compat_2_3_6 :
    Compatible 2 3 6 supportedEntry_2_3 supportedEntry_2_6 := by decide +kernel

/-- Compatibility of C(179, 1) with C(179, 3). -/
theorem compat_179_1_3 :
    Compatible 179 1 3 supportedEntry_179_1 supportedEntry_179_3 := by decide +kernel

/-- Compatibility of C(223, 1) with C(223, 3). -/
theorem compat_223_1_3 :
    Compatible 223 1 3 supportedEntry_223_1 supportedEntry_223_3 := by decide +kernel

/-- Compatibility of C(251, 1) with C(251, 3). -/
theorem compat_251_1_3 :
    Compatible 251 1 3 supportedEntry_251_1 supportedEntry_251_3 := by decide +kernel

/-- Compatibility of C(857, 1) with C(857, 3). -/
theorem compat_857_1_3 :
    Compatible 857 1 3 supportedEntry_857_1 supportedEntry_857_3 := by decide +kernel

/-- Compatibility of C(109, 1) with C(109, 3). -/
theorem compat_109_1_3 :
    Compatible 109 1 3 supportedEntry_109_1 supportedEntry_109_3 := by decide +kernel

/-- Compatibility of C(293, 1) with C(293, 3). -/
theorem compat_293_1_3 :
    Compatible 293 1 3 supportedEntry_293_1 supportedEntry_293_3 := by decide +kernel


end Conway

end Hex
