/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.CompatibilityCore
public import HexConway.PrimitiveProofs.S2_7

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Compatibility of C(2, 4) with C(2, 16). -/
theorem compat_2_4_16 :
    Compatible 2 4 16 supportedEntry_2_4 supportedEntry_2_16 := by decide +kernel

/-- Compatibility of C(2, 5) with C(2, 15). -/
theorem compat_2_5_15 :
    Compatible 2 5 15 supportedEntry_2_5 supportedEntry_2_15 := by decide +kernel

/-- Compatibility of C(2, 2) with C(2, 12). -/
theorem compat_2_2_12 :
    Compatible 2 2 12 supportedEntry_2_2 supportedEntry_2_12 := by decide +kernel

/-- Compatibility of C(2, 6) with C(2, 12). -/
theorem compat_2_6_12 :
    Compatible 2 6 12 supportedEntry_2_6 supportedEntry_2_12 := by decide +kernel

/-- Compatibility of C(7, 2) with C(7, 8). -/
theorem compat_7_2_8 :
    Compatible 7 2 8 supportedEntry_7_2 supportedEntry_7_8 := by decide +kernel

/-- Compatibility of C(2, 5) with C(2, 10). -/
theorem compat_2_5_10 :
    Compatible 2 5 10 supportedEntry_2_5 supportedEntry_2_10 := by decide +kernel

/-- Compatibility of C(853, 2) with C(853, 4). -/
theorem compat_853_2_4 :
    Compatible 853 2 4 supportedEntry_853_2 supportedEntry_853_4 := by decide +kernel

/-- Compatibility of C(11, 1) with C(11, 6). -/
theorem compat_11_1_6 :
    Compatible 11 1 6 supportedEntry_11_1 supportedEntry_11_6 := by decide +kernel

/-- Compatibility of C(463, 1) with C(463, 4). -/
theorem compat_463_1_4 :
    Compatible 463 1 4 supportedEntry_463_1 supportedEntry_463_4 := by decide +kernel

/-- Compatibility of C(701, 1) with C(701, 4). -/
theorem compat_701_1_4 :
    Compatible 701 1 4 supportedEntry_701_1 supportedEntry_701_4 := by decide +kernel

/-- Compatibility of C(743, 1) with C(743, 4). -/
theorem compat_743_1_4 :
    Compatible 743 1 4 supportedEntry_743_1 supportedEntry_743_4 := by decide +kernel

/-- Compatibility of C(827, 1) with C(827, 4). -/
theorem compat_827_1_4 :
    Compatible 827 1 4 supportedEntry_827_1 supportedEntry_827_4 := by decide +kernel

/-- Compatibility of C(857, 1) with C(857, 4). -/
theorem compat_857_1_4 :
    Compatible 857 1 4 supportedEntry_857_1 supportedEntry_857_4 := by decide +kernel

/-- Compatibility of C(919, 1) with C(919, 4). -/
theorem compat_919_1_4 :
    Compatible 919 1 4 supportedEntry_919_1 supportedEntry_919_4 := by decide +kernel

/-- Compatibility of C(307, 1) with C(307, 4). -/
theorem compat_307_1_4 :
    Compatible 307 1 4 supportedEntry_307_1 supportedEntry_307_4 := by decide +kernel

/-- Compatibility of C(421, 1) with C(421, 4). -/
theorem compat_421_1_4 :
    Compatible 421 1 4 supportedEntry_421_1 supportedEntry_421_4 := by decide +kernel

/-- Compatibility of C(547, 1) with C(547, 4). -/
theorem compat_547_1_4 :
    Compatible 547 1 4 supportedEntry_547_1 supportedEntry_547_4 := by decide +kernel

/-- Compatibility of C(563, 1) with C(563, 4). -/
theorem compat_563_1_4 :
    Compatible 563 1 4 supportedEntry_563_1 supportedEntry_563_4 := by decide +kernel

/-- Compatibility of C(593, 1) with C(593, 4). -/
theorem compat_593_1_4 :
    Compatible 593 1 4 supportedEntry_593_1 supportedEntry_593_4 := by decide +kernel

/-- Compatibility of C(613, 1) with C(613, 4). -/
theorem compat_613_1_4 :
    Compatible 613 1 4 supportedEntry_613_1 supportedEntry_613_4 := by decide +kernel

/-- Compatibility of C(619, 1) with C(619, 4). -/
theorem compat_619_1_4 :
    Compatible 619 1 4 supportedEntry_619_1 supportedEntry_619_4 := by decide +kernel

/-- Compatibility of C(647, 1) with C(647, 4). -/
theorem compat_647_1_4 :
    Compatible 647 1 4 supportedEntry_647_1 supportedEntry_647_4 := by decide +kernel

/-- Compatibility of C(691, 1) with C(691, 4). -/
theorem compat_691_1_4 :
    Compatible 691 1 4 supportedEntry_691_1 supportedEntry_691_4 := by decide +kernel

/-- Compatibility of C(733, 1) with C(733, 4). -/
theorem compat_733_1_4 :
    Compatible 733 1 4 supportedEntry_733_1 supportedEntry_733_4 := by decide +kernel


end Conway

end Hex
