/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.CompatibilityCore
public import HexConway.CompatibilityProofs.S2_5

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Compatibility of C(23, 1) with C(23, 2). -/
theorem compat_23_1_2 :
    Compatible 23 1 2 supportedEntry_23_1 supportedEntry_23_2 := by decide +kernel

/-- Compatibility of C(17, 1) with C(17, 2). -/
theorem compat_17_1_2 :
    Compatible 17 1 2 supportedEntry_17_1 supportedEntry_17_2 := by decide +kernel


end Conway

end Hex
