/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.CompatibilityCore
public import HexConway.CompatibilityProofs.S3_0

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Compatibility of C(11, 1) with C(11, 2). -/
theorem compat_11_1_2 :
    Compatible 11 1 2 supportedEntry_11_1 supportedEntry_11_2 := by decide +kernel

/-- Compatibility of C(7, 1) with C(7, 2). -/
theorem compat_7_1_2 :
    Compatible 7 1 2 supportedEntry_7_1 supportedEntry_7_2 := by decide +kernel


end Conway

end Hex
