/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

import HexPermGroupTheory
import Mathlib.GroupTheory.Perm.Cycle.Concrete
meta import Mathlib.GroupTheory.Perm.Cycle.Concrete

/-!
# Examples of `perm_group`

Each statement is about a subgroup of `Equiv.Perm (Fin n)` generated by
permutations written in Mathlib's cycle notation, and each proof is
`perm_group`, which checks a stabilizer-chain certificate in the kernel.
-/

namespace Hex.PermGroup.ProofProbe

/-- The Mathieu group `M11`, generated by an 11-cycle and a product of two
4-cycles, has order 7920. -/
example : Nat.card (Subgroup.closure
    ({c[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], c[2, 6, 10, 7] * c[3, 9, 4, 5]} :
      Set (Equiv.Perm (Fin 11)))) = 7920 := by
  perm_group

/-- A transposition and an 11-cycle generate the whole symmetric group. -/
example : Subgroup.closure ({c[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], c[0, 1]} :
    Set (Equiv.Perm (Fin 11))) = ⊤ := by
  perm_group

/-- A product of the generators of `M11` lies in `M11`. -/
example : c[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10] * (c[2, 6, 10, 7] * c[3, 9, 4, 5]) ∈
    Subgroup.closure ({c[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], c[2, 6, 10, 7] * c[3, 9, 4, 5]} :
      Set (Equiv.Perm (Fin 11))) := by
  perm_group

/-- `M11` contains only even permutations, so no transposition. -/
example : c[0, 1] ∉ Subgroup.closure ({c[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    c[2, 6, 10, 7] * c[3, 9, 4, 5]} : Set (Equiv.Perm (Fin 11))) := by
  perm_group

/-- The generating set may also be a `Finset` literal. -/
example : Nat.card (Subgroup.closure (↑({c[0, 1, 2], c[0, 1]} : Finset (Equiv.Perm (Fin 3))) :
    Set (Equiv.Perm (Fin 3)))) = 6 := by
  perm_group

/-- The Mathieu group `M12` from its ATLAS generators has order 95040. -/
example : Nat.card (Subgroup.closure ({c[0, 3] * c[2, 9] * c[4, 10] * c[5, 11],
      c[0, 7, 8] * c[1, 2, 3] * c[4, 11, 10] * c[5, 9, 6]} :
      Set (Equiv.Perm (Fin 12)))) = 95040 := by
  perm_group

/-- The Mathieu group `M22` from its ATLAS generators has order 443520. -/
example : Nat.card (Subgroup.closure ({c[0, 12] * c[1, 7] * c[2, 15] * c[3, 11] * c[5, 21] *
        c[6, 16] * c[8, 9] * c[10, 13],
      c[0, 21, 2, 20] * c[1, 17, 3, 12] * c[4, 11] * c[5, 10, 6, 14] * c[7, 13, 19, 9] *
        c[16, 18]} :
      Set (Equiv.Perm (Fin 22)))) = 443520 := by
  perm_group

/-- The Mathieu group `M24` from its ATLAS generators has order 244823040. With a
small chunk budget the Schreier generators of each level are checked in
several declarations. -/
example : Nat.card (Subgroup.closure ({c[0, 3] * c[1, 6] * c[2, 16] * c[4, 12] * c[5, 8] *
        c[7, 14] * c[9, 18] * c[10, 17] * c[11, 20] * c[13, 15] * c[19, 23] * c[21, 22],
      c[0, 3, 5] * c[1, 20, 13] * c[2, 8, 14] * c[4, 17, 9] * c[12, 16, 15] * c[18, 23, 22]} :
      Set (Equiv.Perm (Fin 24)))) = 244823040 := by
  perm_group (maxChunkWork := 20000)

/--
error: perm_group: the certified order is 7920, not 7921
-/
#guard_msgs in
example : Nat.card (Subgroup.closure
    ({c[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], c[2, 6, 10, 7] * c[3, 9, 4, 5]} :
      Set (Equiv.Perm (Fin 11)))) = 7921 := by
  perm_group

/-- The Mathieu group `M24` with its generators given as image lists, which elaborate in time
linear in the degree and are checked by the kernel in time linear in the degree. -/
example : Nat.card (Subgroup.closure ({
    Hex.PermGroup.Kernel.permOfImages 24
      [3, 6, 16, 0, 12, 8, 1, 14, 5, 18, 17, 20, 4, 15, 7, 13, 2, 10, 9, 23, 11, 22, 21, 19],
    Hex.PermGroup.Kernel.permOfImages 24
      [3, 20, 8, 5, 17, 0, 6, 7, 14, 4, 10, 11, 16, 1, 2, 12, 15, 9, 23, 19, 13, 21, 18, 22]} :
      Set (Equiv.Perm (Fin 24)))) = 244823040 := by
  perm_group

-- `#perm_group_certificate` prints the same proof as Lean source, for committing a large
-- certificate as data.
#guard_msgs (drop info) in
#perm_group_certificate symmetricThree for ({c[0, 1, 2], c[0, 1]} : Set (Equiv.Perm (Fin 3)))

-- Goals of any other shape are rejected before any work is done.
example : c[0, 1] ∉ Subgroup.closure ({c[0, 1, 2]} : Set (Equiv.Perm (Fin 3))) ⊓ ⊥ := by
  fail_if_success perm_group
  rw [Subgroup.mem_inf, Subgroup.mem_bot]
  exact fun h => absurd h.2 (by decide)

end Hex.PermGroup.ProofProbe
