/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

meta import HexPermGroup.Kernel.Certify
import HexPermGroup.Kernel.Certify

/-!
Conformance for kernel certificates: `Kernel.check` accepts `Kernel.certify S`
and certifies `Group.order`, for every group generated by two permutations of
degree at most four, for cyclic groups of degree 16 and 32, for the symmetric
group of degree 8, and for the trivial group. It rejects every corrupted certificate below, and
`Kernel.chunks` returns adjacent ranges covering every Schreier pair and
rejects a zero budget.
-/

namespace Hex.PermGroup.Kernel.Conformance

open Hex Hex.PermGroup Hex.PermGroup.Kernel

private meta def insertions (x : Nat) : List Nat → List (List Nat)
  | [] => [[x]]
  | y :: ys => (x :: y :: ys) :: (insertions x ys).map (y :: ·)

private meta def permutations : List Nat → List (List Nat)
  | [] => [[]]
  | x :: xs => (permutations xs).flatMap (insertions x)

private meta def fail {α : Type} (msg : String) : IO α := throw (IO.userError msg)

/-- Certify `S`, check it, and compare the certified order with `Group.order`. -/
private meta def certifyChecked (S : Array (Perm n)) : IO Certificate := do
  let c ← match certify S with
    | .ok c => pure c
    | .error e => fail s!"certify failed at degree {n}: {e}"
  unless check n (S.toList.map pack) c do fail s!"check rejected a certificate at degree {n}"
  unless order c == (Group.ofGenerators S).order do
    fail s!"certified order {order c} differs from {(Group.ofGenerators S).order} at degree {n}"
  return c

/-- The entries `0 ≤ j < size` of a level's array. -/
private meta def entries {α : Type} [Inhabited α] (r : Lean.RArray α) (size : Nat) : Array α :=
  (Array.range size).map r.get

-- Every group generated by two permutations of degree at most four.
#eval do
  let mut count := 0
  for n in List.range 5 do
    for p in permutations (List.range n) do
      for q in permutations (List.range n) do
        let some a := Perm.ofNatArray? n (List.toArray p) | fail "bad input"
        let some b := Perm.ofNatArray? n (List.toArray q) | fail "bad input"
        discard <| certifyChecked #[a, b]
        count := count + 1
  unless count == 1 + 1 + 4 + 36 + 576 do fail "small groups were omitted"

-- Cyclic groups at degrees that are powers of two, whose single orbit makes the
-- lookup value `n` need the full field width, a symmetric group, the trivial
-- group, and degree zero.
#eval do
  for n in [16, 32] do
    let some cyc := Perm.ofNatArray? n ((List.range n).map (fun i => (i + 1) % n)).toArray
      | fail "bad cycle"
    let c ← certifyChecked #[cyc]
    unless order c == n do fail s!"order of the cyclic group of degree {n}"
  let some cyc := Perm.ofNatArray? 8 #[1, 2, 3, 4, 5, 6, 7, 0] | fail "bad cycle"
  let some tr := Perm.ofNatArray? 8 #[1, 0, 2, 3, 4, 5, 6, 7] | fail "bad transposition"
  let c ← certifyChecked #[cyc, tr]
  unless order c == 40320 do fail "order of the symmetric group of degree 8"
  let c ← certifyChecked #[Perm.id 5, Perm.id 5]
  unless c.isEmpty && order c == 1 do fail "trivial group certificate has levels"
  unless check 5 [pack (Perm.id 5)] [] do fail "trivial group rejected"
  discard <| certifyChecked (#[] : Array (Perm 0))

/-- A certificate for the symmetric group of degree four, and its inputs. -/
private meta def s4 : IO (List Nat × Certificate) := do
  let some cyc := Perm.ofNatArray? 4 #[1, 2, 3, 0] | fail "bad input"
  let some tr := Perm.ofNatArray? 4 #[1, 0, 2, 3] | fail "bad input"
  return ([pack cyc, pack tr], ← certifyChecked #[cyc, tr])

/-- Replace the first level of a certificate. -/
private meta def withFirst (c : Certificate) (f : Level → Level) : Certificate :=
  match c with
  | L :: rest => f L :: rest
  | [] => []

-- Every corruption is rejected by the check that targets it, which accepts the
-- unmodified level, and by `check` as a whole.
#eval do
  let (inputs, c) ← s4
  let W := width 4
  let e := ident 4 W
  let some L := c.head? | fail "no levels"
  let rest := c.tail
  let setAt {α : Type} [Inhabited α] (r : Lean.RArray α) (j : Nat) (x : α) :=
    rarrayOf ((entries r L.size).set! j x)
  let targets (name : String) (component : Level → Bool) (bad : Level) : IO Unit := do
    unless component L do fail s!"the {name} check rejects the unmodified level"
    if component bad then fail s!"the {name} check accepted a corrupted level"
    if check 4 inputs (bad :: rest) then fail s!"check accepted a corrupted {name}"
  let shape := fun L => shapeOk 4 W L
  let trans := fun L => transversalOk 4 W e L
  let next := fun L => nextOk 4 W L (headGens rest)
  targets "transversal" trans { L with reps := setAt L.reps 1 (L.reps.get 2) }
  targets "stored inverse" trans { L with invs := setAt L.invs 1 (L.invs.get 2) }
  targets "lookup" shape { L with lookup := L.lookup ^^^ (1 <<< W) }
  targets "orbit point" shape { L with orbit := setAt L.orbit 1 (L.orbit.get 2) }
  targets "orbit size" shape { L with size := L.size - 1 }
  targets "base point" shape { L with base := 4 }
  targets "Schreier-tree parent" trans
    { L with parents := setAt L.parents 1 ((L.parents.get 1).1, 1) }
  targets "parent generator index" trans
    { L with parents := setAt L.parents 1 (L.gens.length, (L.parents.get 1).2) }
  targets "next-level index" next
    { L with next := L.next.map fun (i, j) => (i, (j + 1) % L.size) }
  -- A first-level generator unrelated to the inputs fails the input check.
  let bad := { L with
    gens := L.gens.map fun s => if s == L.gens.head! then pack (Perm.id 4) else s }
  unless inputsOk 4 W e inputs c do fail "the input check rejects the unmodified certificate"
  if inputsOk 4 W e inputs (bad :: rest) then fail "the input check accepted an unrelated generator"
  if check 4 [] c then fail "accepted a certificate for different inputs"

-- `chunks` covers every Schreier pair with adjacent ranges, and rejects budget zero.
#eval do
  let (inputs, c) ← s4
  match chunks 4 inputs.length c 0 with
  | .ok _ => fail "a zero chunk budget was accepted"
  | .error _ => pure ()
  let some cyc := Perm.ofNatArray? 8 #[1, 2, 3, 4, 5, 6, 7, 0] | fail "bad input"
  let some tr := Perm.ofNatArray? 8 #[1, 0, 2, 3, 4, 5, 6, 7] | fail "bad input"
  let c ← certifyChecked #[cyc, tr]
  let parts ← match chunks 8 2 c 1500 with
    | .ok p => pure p
    | .error e => fail s!"chunks failed: {e}"
  unless parts.length == c.length do fail "one range list per level"
  for (L, rs) in c.zip parts do
    let mut next := 0
    for (lo, hi) in rs do
      unless lo == next && lo < hi do fail "ranges are not adjacent and nonempty"
      next := hi
    unless next == L.gens.length * L.size do fail "ranges do not cover every Schreier pair"
  unless parts.any (·.length > 1) do fail "the small budget did not split any level"

end Hex.PermGroup.Kernel.Conformance
