import HexBerlekampZassenhaus
import Mathlib.LinearAlgebra.Matrix.RowCol

/-!
Mathlib-facing row-span interface for the executable BHKS projected lattice.

The executable fast path stores the Gram-Schmidt cut output as arrays of
integer projected rows.  This module packages those arrays as Mathlib
submodules: the integer projected lattice `L'`, its rational row space, and the
indicator lattice `W` generated by true-factor supports.
-/

namespace HexBerlekampZassenhausMathlib

noncomputable section

namespace BHKS

/-- The projected integer rows of the executable BHKS cut as a Mathlib matrix. -/
def projectedRowsIntMatrix (L : Hex.BhksProjectedRows) :
    Matrix (Fin L.projectedRows.size) (Fin L.factorCount) ℤ :=
  fun i j => (L.projectedRows.getD i.val #[]).getD j.val 0

/-- The projected rational rows of the executable BHKS cut as a Mathlib matrix. -/
def projectedRowsRatMatrix (L : Hex.BhksProjectedRows) :
    Matrix (Fin L.projectedRows.size) (Fin L.factorCount) ℚ :=
  fun i j => ((L.projectedRows.getD i.val #[]).getD j.val 0 : ℚ)

/--
The integer row span represented by the executable projected BHKS rows.  This
is the proof-facing `L' <= Z^r`.
-/
def projectedRowSpanInt (L : Hex.BhksProjectedRows) :
    Submodule ℤ (Fin L.factorCount → ℤ) :=
  Submodule.span ℤ (Set.range fun i : Fin L.projectedRows.size =>
    Matrix.row (projectedRowsIntMatrix L) i)

/--
The rational row space represented by the same executable projected rows.  This
is the row-space input used by the RREF equivalence-class stage.
-/
def projectedRowSpaceRat (L : Hex.BhksProjectedRows) :
    Submodule ℚ (Fin L.factorCount → ℚ) :=
  Submodule.span ℚ (Set.range fun i : Fin L.projectedRows.size =>
    Matrix.row (projectedRowsRatMatrix L) i)

/-- Cast an integer vector over the lifted-factor indices to a rational vector. -/
def intVectorToRat {r : Nat} (v : Fin r → ℤ) : Fin r → ℚ :=
  fun i => (v i : ℚ)

/-- A `0/1` indicator vector for a support of lifted factor indices. -/
def indicatorVector {r : Nat} (S : Set (Fin r)) : Fin r → ℤ :=
  by
    classical
    exact fun i => if i ∈ S then 1 else 0

@[simp] theorem indicatorVector_apply_mem {r : Nat} (S : Set (Fin r))
    {i : Fin r} (hi : i ∈ S) :
    indicatorVector S i = 1 := by
  simp [indicatorVector, hi]

@[simp] theorem indicatorVector_apply_not_mem {r : Nat} (S : Set (Fin r))
    {i : Fin r} (hi : i ∉ S) :
    indicatorVector S i = 0 := by
  simp [indicatorVector, hi]

/-- A support of lifted local-factor indices for a BHKS lattice basis. -/
abbrev LiftedFactorSupport (L : Hex.BhksLatticeBasis) :=
  Set (Fin L.factorCount)

/-- The `0/1` indicator vector attached to a lifted-factor support. -/
def liftedFactorIndicator (L : Hex.BhksLatticeBasis) (S : LiftedFactorSupport L) :
    Fin L.factorCount → ℤ :=
  indicatorVector S

/--
The true-factor indicator lattice `W`, generated by the indicator vectors of
the true integer factors' lifted-factor supports.
-/
def trueFactorIndicatorLattice {r : Nat} (trueSupports : Set (Set (Fin r))) :
    Submodule ℤ (Fin r → ℤ) :=
  Submodule.span ℤ (Set.range fun S : trueSupports => indicatorVector S.1)

/-- Each declared true-factor support contributes its indicator to `W`. -/
theorem indicatorVector_mem_trueFactorIndicatorLattice
    {r : Nat} (trueSupports : Set (Set (Fin r))) (S : trueSupports) :
    indicatorVector S.1 ∈ trueFactorIndicatorLattice trueSupports := by
  exact Submodule.subset_span ⟨S, rfl⟩

/-- The true-factor indicator lattice over the lifted factors of a BHKS basis. -/
def liftedFactorIndicatorLattice
    (L : Hex.BhksLatticeBasis) (trueSupports : Set (LiftedFactorSupport L)) :
    Submodule ℤ (Fin L.factorCount → ℤ) :=
  trueFactorIndicatorLattice trueSupports

/-- Each declared lifted-factor support contributes its indicator to `W`. -/
theorem liftedFactorIndicator_mem_liftedFactorIndicatorLattice
    (L : Hex.BhksLatticeBasis) (trueSupports : Set (LiftedFactorSupport L))
    (S : trueSupports) :
    liftedFactorIndicator L S.1 ∈ liftedFactorIndicatorLattice L trueSupports := by
  exact indicatorVector_mem_trueFactorIndicatorLattice trueSupports S

/--
Cut hypotheses needed to connect the executable projected rows to the abstract
true-factor supports.  Later B4/B5 work discharges `indicator_mem_projected`
from the BHKS norm bound and Gram-Schmidt cut soundness.
-/
structure CutProjectionHypotheses
    (L : Hex.BhksProjectedRows) (trueSupports : Set (Set (Fin L.factorCount))) where
  indicator_mem_projected :
    ∀ S : trueSupports, indicatorVector S.1 ∈ projectedRowSpanInt L

/-- Direct consumer-facing form of the cut hypothesis for one true support. -/
theorem indicatorVector_mem_projectedRowSpan_of_cut
    (L : Hex.BhksProjectedRows) (trueSupports : Set (Set (Fin L.factorCount)))
    (hcut : CutProjectionHypotheses L trueSupports) (S : trueSupports) :
    indicatorVector S.1 ∈ projectedRowSpanInt L :=
  hcut.indicator_mem_projected S

/--
BHKS `W <= L'`: every vector in the true-factor indicator lattice is in the
integer row span represented by the executable projected rows.
-/
theorem trueFactorIndicatorLattice_le_projectedRowSpan
    (L : Hex.BhksProjectedRows) (trueSupports : Set (Set (Fin L.factorCount)))
    (hcut : CutProjectionHypotheses L trueSupports) :
    trueFactorIndicatorLattice trueSupports ≤ projectedRowSpanInt L := by
  rw [trueFactorIndicatorLattice]
  refine Submodule.span_le.mpr ?_
  rintro v ⟨S, rfl⟩
  exact hcut.indicator_mem_projected S

/-- Membership form of `W <= L'`, useful after proving a vector lies in `W`. -/
theorem mem_projectedRowSpan_of_mem_trueFactorIndicatorLattice
    (L : Hex.BhksProjectedRows) (trueSupports : Set (Set (Fin L.factorCount)))
    (hcut : CutProjectionHypotheses L trueSupports)
    {v : Fin L.factorCount → ℤ}
    (hv : v ∈ trueFactorIndicatorLattice trueSupports) :
    v ∈ projectedRowSpanInt L :=
  trueFactorIndicatorLattice_le_projectedRowSpan L trueSupports hcut hv

/--
Abstract separation hypotheses for the BHKS `L' = W` step.

The forward direction packages the existing Gram-Schmidt cut evidence
`W <= L'`.  The reverse direction is deliberately stated as a contradiction:
later work constructs a BHKS bad-vector setup from any vector in `L' \ W`, then
uses the cap/resultant contradiction to discharge this field.
-/
structure SeparationHypotheses
    (L : Hex.BhksProjectedRows) (trueSupports : Set (Set (Fin L.factorCount))) where
  cut : CutProjectionHypotheses L trueSupports
  no_projected_not_indicator :
    ∀ v : Fin L.factorCount → ℤ,
      v ∈ projectedRowSpanInt L →
        v ∉ trueFactorIndicatorLattice trueSupports →
          False

/-- Under the abstract BHKS separation hypotheses, the projected lattice `L'`
is exactly the true-factor indicator lattice `W`. -/
theorem projectedRowSpan_eq_trueFactorIndicatorLattice
    (L : Hex.BhksProjectedRows) (trueSupports : Set (Set (Fin L.factorCount)))
    (hsep : SeparationHypotheses L trueSupports) :
    projectedRowSpanInt L = trueFactorIndicatorLattice trueSupports := by
  refine le_antisymm ?_ ?_
  · intro v hv
    by_contra hnot
    exact hsep.no_projected_not_indicator v hv hnot
  · exact trueFactorIndicatorLattice_le_projectedRowSpan L trueSupports hsep.cut

/-- Separation gives the reverse containment `L' <= W`. -/
theorem projectedRowSpan_le_trueFactorIndicatorLattice
    (L : Hex.BhksProjectedRows) (trueSupports : Set (Set (Fin L.factorCount)))
    (hsep : SeparationHypotheses L trueSupports) :
    projectedRowSpanInt L ≤ trueFactorIndicatorLattice trueSupports := by
  intro v hv
  by_contra hnot
  exact hsep.no_projected_not_indicator v hv hnot

/-- Membership in `L'` and `W` are equivalent under separation. -/
theorem mem_projectedRowSpan_iff_mem_trueFactorIndicatorLattice
    (L : Hex.BhksProjectedRows) (trueSupports : Set (Set (Fin L.factorCount)))
    (hsep : SeparationHypotheses L trueSupports)
    {v : Fin L.factorCount → ℤ} :
    v ∈ projectedRowSpanInt L ↔
      v ∈ trueFactorIndicatorLattice trueSupports := by
  rw [projectedRowSpan_eq_trueFactorIndicatorLattice L trueSupports hsep]

/-- Each projected integer row is one of the generators of `L'`. -/
theorem projectedRow_mem_projectedRowSpanInt
    (L : Hex.BhksProjectedRows) (i : Fin L.projectedRows.size) :
    Matrix.row (projectedRowsIntMatrix L) i ∈ projectedRowSpanInt L := by
  exact Submodule.subset_span ⟨i, rfl⟩

/-- Each projected rational row is one of the generators of the rational row space. -/
theorem projectedRow_mem_projectedRowSpaceRat
    (L : Hex.BhksProjectedRows) (i : Fin L.projectedRows.size) :
    Matrix.row (projectedRowsRatMatrix L) i ∈ projectedRowSpaceRat L := by
  exact Submodule.subset_span ⟨i, rfl⟩

end BHKS

end

end HexBerlekampZassenhausMathlib
