/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.ApiCore
public import HexConway.Supported.S0_4

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- The verified table supports C(7, 3). -/
@[expose] def supportedEntry_7_3 : SupportedEntry 7 3 :=
  ⟨luebeckConwayPolynomial_7_3, prime_seven, luebeckConwayPolynomial?_hit_7_3⟩

/-- The verified table supports C(863, 2). -/
@[expose] def supportedEntry_863_2 : SupportedEntry 863 2 :=
  ⟨luebeckConwayPolynomial_863_2, prime_863, luebeckConwayPolynomial?_hit_863_2⟩

/-- The verified table supports C(103, 2). -/
@[expose] def supportedEntry_103_2 : SupportedEntry 103 2 :=
  ⟨luebeckConwayPolynomial_103_2, prime_103, luebeckConwayPolynomial?_hit_103_2⟩

/-- The verified table supports C(383, 2). -/
@[expose] def supportedEntry_383_2 : SupportedEntry 383 2 :=
  ⟨luebeckConwayPolynomial_383_2, prime_383, luebeckConwayPolynomial?_hit_383_2⟩

/-- The verified table supports C(59, 2). -/
@[expose] def supportedEntry_59_2 : SupportedEntry 59 2 :=
  ⟨luebeckConwayPolynomial_59_2, prime_59, luebeckConwayPolynomial?_hit_59_2⟩

/-- The verified table supports C(193, 2). -/
@[expose] def supportedEntry_193_2 : SupportedEntry 193 2 :=
  ⟨luebeckConwayPolynomial_193_2, prime_193, luebeckConwayPolynomial?_hit_193_2⟩

/-- The verified table supports C(5, 3). -/
@[expose] def supportedEntry_5_3 : SupportedEntry 5 3 :=
  ⟨luebeckConwayPolynomial_5_3, prime_five, luebeckConwayPolynomial?_hit_5_3⟩

/-- The verified table supports C(37, 2). -/
@[expose] def supportedEntry_37_2 : SupportedEntry 37 2 :=
  ⟨luebeckConwayPolynomial_37_2, prime_37, luebeckConwayPolynomial?_hit_37_2⟩

/-- The verified table supports C(19, 2). -/
@[expose] def supportedEntry_19_2 : SupportedEntry 19 2 :=
  ⟨luebeckConwayPolynomial_19_2, prime_19, luebeckConwayPolynomial?_hit_19_2⟩

/-- The verified table supports C(11, 2). -/
@[expose] def supportedEntry_11_2 : SupportedEntry 11 2 :=
  ⟨luebeckConwayPolynomial_11_2, prime_eleven, luebeckConwayPolynomial?_hit_11_2⟩

/-- The verified table supports C(547, 1). -/
@[expose] def supportedEntry_547_1 : SupportedEntry 547 1 :=
  ⟨luebeckConwayPolynomial_547_1, prime_547, luebeckConwayPolynomial?_hit_547_1⟩

/-- The verified table supports C(691, 1). -/
@[expose] def supportedEntry_691_1 : SupportedEntry 691 1 :=
  ⟨luebeckConwayPolynomial_691_1, prime_691, luebeckConwayPolynomial?_hit_691_1⟩

/-- The verified table supports C(991, 1). -/
@[expose] def supportedEntry_991_1 : SupportedEntry 991 1 :=
  ⟨luebeckConwayPolynomial_991_1, prime_991, luebeckConwayPolynomial?_hit_991_1⟩

/-- The verified table supports C(521, 1). -/
@[expose] def supportedEntry_521_1 : SupportedEntry 521 1 :=
  ⟨luebeckConwayPolynomial_521_1, prime_521, luebeckConwayPolynomial?_hit_521_1⟩

/-- The verified table supports C(601, 1). -/
@[expose] def supportedEntry_601_1 : SupportedEntry 601 1 :=
  ⟨luebeckConwayPolynomial_601_1, prime_601, luebeckConwayPolynomial?_hit_601_1⟩

/-- The verified table supports C(619, 1). -/
@[expose] def supportedEntry_619_1 : SupportedEntry 619 1 :=
  ⟨luebeckConwayPolynomial_619_1, prime_619, luebeckConwayPolynomial?_hit_619_1⟩

/-- The verified table supports C(673, 1). -/
@[expose] def supportedEntry_673_1 : SupportedEntry 673 1 :=
  ⟨luebeckConwayPolynomial_673_1, prime_673, luebeckConwayPolynomial?_hit_673_1⟩

/-- The verified table supports C(727, 1). -/
@[expose] def supportedEntry_727_1 : SupportedEntry 727 1 :=
  ⟨luebeckConwayPolynomial_727_1, prime_727, luebeckConwayPolynomial?_hit_727_1⟩

/-- The verified table supports C(751, 1). -/
@[expose] def supportedEntry_751_1 : SupportedEntry 751 1 :=
  ⟨luebeckConwayPolynomial_751_1, prime_751, luebeckConwayPolynomial?_hit_751_1⟩

/-- The verified table supports C(811, 1). -/
@[expose] def supportedEntry_811_1 : SupportedEntry 811 1 :=
  ⟨luebeckConwayPolynomial_811_1, prime_811, luebeckConwayPolynomial?_hit_811_1⟩

/-- The verified table supports C(829, 1). -/
@[expose] def supportedEntry_829_1 : SupportedEntry 829 1 :=
  ⟨luebeckConwayPolynomial_829_1, prime_829, luebeckConwayPolynomial?_hit_829_1⟩

/-- The verified table supports C(883, 1). -/
@[expose] def supportedEntry_883_1 : SupportedEntry 883 1 :=
  ⟨luebeckConwayPolynomial_883_1, prime_883, luebeckConwayPolynomial?_hit_883_1⟩

/-- The verified table supports C(941, 1). -/
@[expose] def supportedEntry_941_1 : SupportedEntry 941 1 :=
  ⟨luebeckConwayPolynomial_941_1, prime_941, luebeckConwayPolynomial?_hit_941_1⟩

/-- The verified table supports C(997, 1). -/
@[expose] def supportedEntry_997_1 : SupportedEntry 997 1 :=
  ⟨luebeckConwayPolynomial_997_1, prime_997, luebeckConwayPolynomial?_hit_997_1⟩


end Conway

end Hex
