/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.ApiCore

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- The verified table supports C(2, 12). -/
@[expose] def supportedEntry_2_12 : SupportedEntry 2 12 :=
  ⟨luebeckConwayPolynomial_2_12, prime_two, luebeckConwayPolynomial?_hit_2_12⟩

/-- The verified table supports C(5, 8). -/
@[expose] def supportedEntry_5_8 : SupportedEntry 5 8 :=
  ⟨luebeckConwayPolynomial_5_8, prime_five, luebeckConwayPolynomial?_hit_5_8⟩

/-- The verified table supports C(2, 10). -/
@[expose] def supportedEntry_2_10 : SupportedEntry 2 10 :=
  ⟨luebeckConwayPolynomial_2_10, prime_two, luebeckConwayPolynomial?_hit_2_10⟩

/-- The verified table supports C(911, 4). -/
@[expose] def supportedEntry_911_4 : SupportedEntry 911 4 :=
  ⟨luebeckConwayPolynomial_911_4, prime_911, luebeckConwayPolynomial?_hit_911_4⟩

/-- The verified table supports C(599, 4). -/
@[expose] def supportedEntry_599_4 : SupportedEntry 599 4 :=
  ⟨luebeckConwayPolynomial_599_4, prime_599, luebeckConwayPolynomial?_hit_599_4⟩

/-- The verified table supports C(811, 4). -/
@[expose] def supportedEntry_811_4 : SupportedEntry 811 4 :=
  ⟨luebeckConwayPolynomial_811_4, prime_811, luebeckConwayPolynomial?_hit_811_4⟩

/-- The verified table supports C(859, 4). -/
@[expose] def supportedEntry_859_4 : SupportedEntry 859 4 :=
  ⟨luebeckConwayPolynomial_859_4, prime_859, luebeckConwayPolynomial?_hit_859_4⟩

/-- The verified table supports C(419, 4). -/
@[expose] def supportedEntry_419_4 : SupportedEntry 419 4 :=
  ⟨luebeckConwayPolynomial_419_4, prime_419, luebeckConwayPolynomial?_hit_419_4⟩

/-- The verified table supports C(557, 4). -/
@[expose] def supportedEntry_557_4 : SupportedEntry 557 4 :=
  ⟨luebeckConwayPolynomial_557_4, prime_557, luebeckConwayPolynomial?_hit_557_4⟩

/-- The verified table supports C(601, 4). -/
@[expose] def supportedEntry_601_4 : SupportedEntry 601 4 :=
  ⟨luebeckConwayPolynomial_601_4, prime_601, luebeckConwayPolynomial?_hit_601_4⟩

/-- The verified table supports C(643, 4). -/
@[expose] def supportedEntry_643_4 : SupportedEntry 643 4 :=
  ⟨luebeckConwayPolynomial_643_4, prime_643, luebeckConwayPolynomial?_hit_643_4⟩

/-- The verified table supports C(709, 4). -/
@[expose] def supportedEntry_709_4 : SupportedEntry 709 4 :=
  ⟨luebeckConwayPolynomial_709_4, prime_709, luebeckConwayPolynomial?_hit_709_4⟩

/-- The verified table supports C(769, 4). -/
@[expose] def supportedEntry_769_4 : SupportedEntry 769 4 :=
  ⟨luebeckConwayPolynomial_769_4, prime_769, luebeckConwayPolynomial?_hit_769_4⟩

/-- The verified table supports C(863, 4). -/
@[expose] def supportedEntry_863_4 : SupportedEntry 863 4 :=
  ⟨luebeckConwayPolynomial_863_4, prime_863, luebeckConwayPolynomial?_hit_863_4⟩

/-- The verified table supports C(941, 4). -/
@[expose] def supportedEntry_941_4 : SupportedEntry 941 4 :=
  ⟨luebeckConwayPolynomial_941_4, prime_941, luebeckConwayPolynomial?_hit_941_4⟩

/-- The verified table supports C(983, 4). -/
@[expose] def supportedEntry_983_4 : SupportedEntry 983 4 :=
  ⟨luebeckConwayPolynomial_983_4, prime_983, luebeckConwayPolynomial?_hit_983_4⟩

/-- The verified table supports C(281, 4). -/
@[expose] def supportedEntry_281_4 : SupportedEntry 281 4 :=
  ⟨luebeckConwayPolynomial_281_4, prime_281, luebeckConwayPolynomial?_hit_281_4⟩

/-- The verified table supports C(317, 4). -/
@[expose] def supportedEntry_317_4 : SupportedEntry 317 4 :=
  ⟨luebeckConwayPolynomial_317_4, prime_317, luebeckConwayPolynomial?_hit_317_4⟩

/-- The verified table supports C(373, 4). -/
@[expose] def supportedEntry_373_4 : SupportedEntry 373 4 :=
  ⟨luebeckConwayPolynomial_373_4, prime_373, luebeckConwayPolynomial?_hit_373_4⟩

/-- The verified table supports C(443, 4). -/
@[expose] def supportedEntry_443_4 : SupportedEntry 443 4 :=
  ⟨luebeckConwayPolynomial_443_4, prime_443, luebeckConwayPolynomial?_hit_443_4⟩

/-- The verified table supports C(499, 4). -/
@[expose] def supportedEntry_499_4 : SupportedEntry 499 4 :=
  ⟨luebeckConwayPolynomial_499_4, prime_499, luebeckConwayPolynomial?_hit_499_4⟩

/-- The verified table supports C(569, 4). -/
@[expose] def supportedEntry_569_4 : SupportedEntry 569 4 :=
  ⟨luebeckConwayPolynomial_569_4, prime_569, luebeckConwayPolynomial?_hit_569_4⟩

/-- The verified table supports C(631, 4). -/
@[expose] def supportedEntry_631_4 : SupportedEntry 631 4 :=
  ⟨luebeckConwayPolynomial_631_4, prime_631, luebeckConwayPolynomial?_hit_631_4⟩

/-- The verified table supports C(677, 4). -/
@[expose] def supportedEntry_677_4 : SupportedEntry 677 4 :=
  ⟨luebeckConwayPolynomial_677_4, prime_677, luebeckConwayPolynomial?_hit_677_4⟩


end Conway

end Hex
