/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.ApiCore

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- The verified table supports C(2, 12). -/
@[expose] def supportedEntry_2_12 : SupportedEntry 2 12 :=
  ⟨luebeckConwayPolynomial_2_12, prime_two, luebeckConwayPolynomial?_hit_2_12⟩

/-- The verified table supports C(5, 8). -/
@[expose] def supportedEntry_5_8 : SupportedEntry 5 8 :=
  ⟨luebeckConwayPolynomial_5_8, prime_five, luebeckConwayPolynomial?_hit_5_8⟩

/-- The verified table supports C(2, 10). -/
@[expose] def supportedEntry_2_10 : SupportedEntry 2 10 :=
  ⟨luebeckConwayPolynomial_2_10, prime_two, luebeckConwayPolynomial?_hit_2_10⟩

/-- The verified table supports C(307, 4). -/
@[expose] def supportedEntry_307_4 : SupportedEntry 307 4 :=
  ⟨luebeckConwayPolynomial_307_4, prime_307, luebeckConwayPolynomial?_hit_307_4⟩

/-- The verified table supports C(421, 4). -/
@[expose] def supportedEntry_421_4 : SupportedEntry 421 4 :=
  ⟨luebeckConwayPolynomial_421_4, prime_421, luebeckConwayPolynomial?_hit_421_4⟩

/-- The verified table supports C(293, 4). -/
@[expose] def supportedEntry_293_4 : SupportedEntry 293 4 :=
  ⟨luebeckConwayPolynomial_293_4, prime_293, luebeckConwayPolynomial?_hit_293_4⟩

/-- The verified table supports C(331, 4). -/
@[expose] def supportedEntry_331_4 : SupportedEntry 331 4 :=
  ⟨luebeckConwayPolynomial_331_4, prime_331, luebeckConwayPolynomial?_hit_331_4⟩

/-- The verified table supports C(389, 4). -/
@[expose] def supportedEntry_389_4 : SupportedEntry 389 4 :=
  ⟨luebeckConwayPolynomial_389_4, prime_389, luebeckConwayPolynomial?_hit_389_4⟩

/-- The verified table supports C(461, 4). -/
@[expose] def supportedEntry_461_4 : SupportedEntry 461 4 :=
  ⟨luebeckConwayPolynomial_461_4, prime_461, luebeckConwayPolynomial?_hit_461_4⟩

/-- The verified table supports C(157, 4). -/
@[expose] def supportedEntry_157_4 : SupportedEntry 157 4 :=
  ⟨luebeckConwayPolynomial_157_4, prime_157, luebeckConwayPolynomial?_hit_157_4⟩

/-- The verified table supports C(211, 4). -/
@[expose] def supportedEntry_211_4 : SupportedEntry 211 4 :=
  ⟨luebeckConwayPolynomial_211_4, prime_211, luebeckConwayPolynomial?_hit_211_4⟩

/-- The verified table supports C(269, 4). -/
@[expose] def supportedEntry_269_4 : SupportedEntry 269 4 :=
  ⟨luebeckConwayPolynomial_269_4, prime_269, luebeckConwayPolynomial?_hit_269_4⟩

/-- The verified table supports C(349, 4). -/
@[expose] def supportedEntry_349_4 : SupportedEntry 349 4 :=
  ⟨luebeckConwayPolynomial_349_4, prime_349, luebeckConwayPolynomial?_hit_349_4⟩

/-- The verified table supports C(397, 4). -/
@[expose] def supportedEntry_397_4 : SupportedEntry 397 4 :=
  ⟨luebeckConwayPolynomial_397_4, prime_397, luebeckConwayPolynomial?_hit_397_4⟩

/-- The verified table supports C(457, 4). -/
@[expose] def supportedEntry_457_4 : SupportedEntry 457 4 :=
  ⟨luebeckConwayPolynomial_457_4, prime_457, luebeckConwayPolynomial?_hit_457_4⟩

/-- The verified table supports C(2, 8). -/
@[expose] def supportedEntry_2_8 : SupportedEntry 2 8 :=
  ⟨luebeckConwayPolynomial_2_8, prime_two, luebeckConwayPolynomial?_hit_2_8⟩

/-- The verified table supports C(139, 4). -/
@[expose] def supportedEntry_139_4 : SupportedEntry 139 4 :=
  ⟨luebeckConwayPolynomial_139_4, prime_139, luebeckConwayPolynomial?_hit_139_4⟩

/-- The verified table supports C(179, 4). -/
@[expose] def supportedEntry_179_4 : SupportedEntry 179 4 :=
  ⟨luebeckConwayPolynomial_179_4, prime_179, luebeckConwayPolynomial?_hit_179_4⟩

/-- The verified table supports C(227, 4). -/
@[expose] def supportedEntry_227_4 : SupportedEntry 227 4 :=
  ⟨luebeckConwayPolynomial_227_4, prime_227, luebeckConwayPolynomial?_hit_227_4⟩

/-- The verified table supports C(2, 9). -/
@[expose] def supportedEntry_2_9 : SupportedEntry 2 9 :=
  ⟨luebeckConwayPolynomial_2_9, prime_two, luebeckConwayPolynomial?_hit_2_9⟩

/-- The verified table supports C(449, 4). -/
@[expose] def supportedEntry_449_4 : SupportedEntry 449 4 :=
  ⟨luebeckConwayPolynomial_449_4, prime_449, luebeckConwayPolynomial?_hit_449_4⟩

/-- The verified table supports C(103, 4). -/
@[expose] def supportedEntry_103_4 : SupportedEntry 103 4 :=
  ⟨luebeckConwayPolynomial_103_4, prime_103, luebeckConwayPolynomial?_hit_103_4⟩

/-- The verified table supports C(7, 6). -/
@[expose] def supportedEntry_7_6 : SupportedEntry 7 6 :=
  ⟨luebeckConwayPolynomial_7_6, prime_seven, luebeckConwayPolynomial?_hit_7_6⟩

/-- The verified table supports C(43, 4). -/
@[expose] def supportedEntry_43_4 : SupportedEntry 43 4 :=
  ⟨luebeckConwayPolynomial_43_4, prime_43, luebeckConwayPolynomial?_hit_43_4⟩


end Conway

end Hex
