/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexPermGroup.Kernel.Check
public import HexPermGroupMathlib.Word
public import Mathlib.GroupTheory.GroupAction.Quotient
public import Mathlib.GroupTheory.Index
public import Mathlib.Algebra.Group.Subgroup.Finite
public import Mathlib.Data.Finite.Perm

public section

/-!
Soundness of the kernel certificate checker.

A packed number *represents* a permutation `σ` of `Fin n` when its fields
`0..n-1` are the images of `σ`. Bits at or above `n*W` are ignored. The proof
works from the last level of a certificate upward: sifting from a level
accepts exactly the packings of the subgroup generated by that level's
generators, the next level's subgroup is the stabilizer of the base point,
and orbit–stabilizer multiplies the orbit sizes.
-/

namespace Hex.PermGroup.Kernel

open Hex.Kernel

variable {n : Nat}

/-- `x` represents `σ`: its field `i` is `σ i` for every `i < n`. -/
def Rep (n : Nat) (x : Nat) (σ : Equiv.Perm (Fin n)) : Prop :=
  ∀ i : Fin n, field (width n) x i.val = (σ i).val

/-- `x` is determined by its fields `0..n-1`, as the output of `packFn` is. -/
def Canon (n : Nat) (x : Nat) : Prop :=
  x = packFn (width n) (fun i => field (width n) x i) n

theorem packFn_congr (W : Nat) {f g : Nat → Nat} :
    ∀ k, (∀ i < k, f i = g i) → packFn W f k = packFn W g k
  | 0, _ => rfl
  | k + 1, h => by
    rw [packFn_succ, packFn_succ, packFn_congr W k (fun i hi => h i (by omega)),
      h k (by omega)]

theorem canon_packFn (f : Nat → Nat) (hf : ∀ i < n, f i < 2 ^ width n) :
    Canon n (packFn (width n) f n) := by
  unfold Canon
  exact packFn_congr _ n fun i hi => (field_packFn _ f n hf i hi).symm

theorem canon_comp (x y : Nat) : Canon n (comp n (width n) x y) :=
  canon_packFn _ fun _ _ => field_lt _ _ _

theorem canon_ident : Canon n (ident n (width n)) :=
  canon_packFn _ fun _ hi => Nat.lt_trans hi (lt_two_pow_width n)

theorem canon_pack (p : Perm n) : Canon n (pack p) :=
  canon_packFn _ fun i hi => by
    simp only [hi, ↓reduceDIte]
    exact Nat.lt_trans (p.get _).isLt (lt_two_pow_width n)

theorem rep_pack (p : Perm n) : Rep n (pack p) p.toEquiv := fun i => by
  rw [field_pack]
  simp

theorem rep_ident : Rep n (ident n (width n)) 1 := fun i =>
  field_ident (lt_two_pow_width n) i.isLt

theorem rep_comp {x y : Nat} {σ τ : Equiv.Perm (Fin n)} (hx : Rep n x σ) (hy : Rep n y τ) :
    Rep n (comp n (width n) x y) (σ * τ) := fun i => by
  rw [field_comp _ _ _ _ i.isLt, hy i, hx]
  rfl

theorem Rep.unique {x : Nat} {σ τ : Equiv.Perm (Fin n)} (hσ : Rep n x σ) (hτ : Rep n x τ) :
    σ = τ := by
  ext i
  rw [← hσ i, ← hτ i]

/-- A value that composes on the right with a representative of `τ` to the
identity represents `τ⁻¹`. -/
theorem rep_of_comp_eq_ident {x y : Nat} {τ : Equiv.Perm (Fin n)} (hy : Rep n y τ)
    (h : comp n (width n) x y = ident n (width n)) : Rep n x τ⁻¹ := fun i => by
  have h1 := field_comp n (width n) x y (τ⁻¹ i).isLt
  rw [h, field_ident (lt_two_pow_width n) (τ⁻¹ i).isLt, hy] at h1
  simpa using h1.symm

/-- Two canonical values with the same representative are equal. -/
theorem Canon.eq_of_rep {x y : Nat} {σ : Equiv.Perm (Fin n)} (hx : Canon n x) (hy : Canon n y)
    (hxσ : Rep n x σ) (hyσ : Rep n y σ) : x = y := by
  rw [hx, hy]
  exact packFn_congr _ n fun i hi => by rw [hxσ ⟨i, hi⟩, hyσ ⟨i, hi⟩]

/-! # Reading the Boolean checks -/

theorem allRange_iff (k : Nat) (p : Nat → Bool) : allRange k p = true ↔ ∀ i < k, p i = true := by
  simp [allRange_eq]

section Facts

variable {n : Nat} {L : Level} {rest : List Level}

local notation "W" => width n
local notation "e" => ident n (width n)

theorem shapeOk_iff : shapeOk n W L = true ↔
    L.base < n ∧ 0 < L.size ∧ L.orbit.get 0 = L.base ∧
    (∀ j < L.size, L.orbit.get j < n ∧ field W L.lookup (L.orbit.get j) = j + 1) ∧
    (∀ x < n, field W L.lookup x = 0 ∨
      (field W L.lookup x ≤ L.size ∧ L.orbit.get (field W L.lookup x - 1) = x)) := by
  simp only [shapeOk, allRange_iff, Bool.and_eq_true, Bool.or_eq_true, blt_eq_decide,
    ble_eq_decide, beq_eq_decide, decide_eq_true_eq, Nat.succ_eq_add_one, sub_eq]
  constructor
  · rintro ⟨⟨⟨⟨h1, h2⟩, h3⟩, h4⟩, h5⟩
    exact ⟨h1, h2, h3, h4, h5⟩
  · rintro ⟨h1, h2, h3, h4, h5⟩
    exact ⟨⟨⟨⟨h1, h2⟩, h3⟩, h4⟩, h5⟩

theorem invClosedOk_iff : invClosedOk n W e L = true ↔
    ∀ s ∈ L.gens, ∃ s' ∈ L.gens, comp n W s s' = e := by
  simp [invClosedOk, beq_eq_decide]

theorem transversalOk_iff : transversalOk n W e L = true ↔
    L.reps.get 0 = e ∧
    (∀ j < L.size, j ≠ 0 →
      (L.parents.get j).1 < L.gens.length ∧ (L.parents.get j).2 < j ∧
      field W (gen L (L.parents.get j).1) (L.orbit.get (L.parents.get j).2) = L.orbit.get j ∧
      L.reps.get j = comp n W (gen L (L.parents.get j).1) (L.reps.get (L.parents.get j).2)) ∧
    (∀ j < L.size, comp n W (L.invs.get j) (L.reps.get j) = e) := by
  simp only [transversalOk, allRange_iff, Bool.and_eq_true, Bool.or_eq_true, blt_eq_decide,
    beq_eq_decide, decide_eq_true_eq]
  constructor
  · rintro ⟨⟨h1, h2⟩, h3⟩
    refine ⟨h1, fun j hj hj0 => ?_, h3⟩
    rcases h2 j hj with h | ⟨⟨⟨a, b⟩, c⟩, d⟩
    · exact absurd h hj0
    · exact ⟨a, b, c, d⟩
  · rintro ⟨h1, h2, h3⟩
    refine ⟨⟨h1, fun j hj => ?_⟩, h3⟩
    by_cases hj0 : j = 0
    · exact Or.inl hj0
    · obtain ⟨a, b, c, d⟩ := h2 j hj hj0
      exact Or.inr ⟨⟨⟨a, b⟩, c⟩, d⟩

theorem pairsOk_iff (lo hi : Nat) : pairsOk n W e L rest lo hi = true ↔
    ∀ p, lo ≤ p → p < hi →
      field W L.lookup (field W (gen L (p / L.size)) (L.orbit.get (p % L.size))) ≠ 0 ∧
      sift n W e rest (schreier n W L (p / L.size) (p % L.size)) = true := by
  simp only [pairsOk, allRange_iff, Bool.and_eq_true, Bool.not_eq_true', beq_eq_decide,
    decide_eq_false_iff_not, sub_eq, add_eq, div_eq, mod_eq]
  constructor
  · intro h p hlo hhi
    have := h (p - lo) (by omega)
    rwa [show lo + (p - lo) = p by omega] at this
  · intro h t ht
    exact h (lo + t) (by omega) (by omega)

theorem nextOk_iff (nextGens : List Nat) : nextOk n W L nextGens = true ↔
    L.next.length = nextGens.length ∧
    ∀ q ∈ L.next.zip nextGens, q.1.1 < L.gens.length ∧ q.1.2 < L.size ∧
      schreier n W L q.1.1 q.1.2 = q.2 := by
  simp [nextOk, blt_eq_decide, beq_eq_decide, and_assoc]

end Facts

/-! # The subgroup of a level -/

/-- The permutations represented by the generators of a level. -/
def genSet (n : Nat) (L : Level) : Set (Equiv.Perm (Fin n)) :=
  {σ | ∃ s ∈ L.gens, Rep n s σ}

/-- The subgroup generated by a level's generators. -/
def levelGroup (n : Nat) (L : Level) : Subgroup (Equiv.Perm (Fin n)) :=
  Subgroup.closure (genSet n L)

/-- The subgroup of the first of a list of levels, trivial for no levels. -/
def groupOf (n : Nat) : List Level → Subgroup (Equiv.Perm (Fin n))
  | [] => ⊥
  | L :: _ => levelGroup n L

theorem gen_eq_getElem {L : Level} {i : Nat} (hi : i < L.gens.length) :
    gen L i = L.gens[i] := by
  simp [gen, List.getD_eq_getElem?_getD, hi]

theorem gen_mem {L : Level} {i : Nat} (hi : i < L.gens.length) : gen L i ∈ L.gens := by
  rw [gen_eq_getElem hi]
  exact List.getElem_mem hi

theorem exists_gen_eq {L : Level} {s : Nat} (hs : s ∈ L.gens) :
    ∃ i < L.gens.length, gen L i = s := by
  obtain ⟨i, hi, rfl⟩ := List.getElem_of_mem hs
  exact ⟨i, hi, gen_eq_getElem hi⟩

section Level

variable {n : Nat} {L : Level} {rest : List Level}

local notation "W" => width n
local notation "e" => ident n (width n)

/-- The checks of one level of an accepted certificate, and representatives
for its generators. -/
structure LevelBase (n : Nat) (L : Level) (rest : List Level) : Prop where
  shape : shapeOk n (width n) L = true
  inv : invClosedOk n (width n) (ident n (width n)) L = true
  trans : transversalOk n (width n) (ident n (width n)) L = true
  next : nextOk n (width n) L (headGens rest) = true
  pairs : pairsOk n (width n) (ident n (width n)) L rest 0 (L.gens.length * L.size) = true
  gens : ∀ s ∈ L.gens, ∃ σ, Rep n s σ

namespace LevelBase

variable (h : LevelBase n L rest)
include h

theorem base_lt : L.base < n := ((shapeOk_iff.mp h.shape).1)

theorem size_pos : 0 < L.size := (shapeOk_iff.mp h.shape).2.1

theorem orbit_zero : L.orbit.get 0 = L.base := (shapeOk_iff.mp h.shape).2.2.1

theorem orbit_lt {j : Nat} (hj : j < L.size) : L.orbit.get j < n :=
  ((shapeOk_iff.mp h.shape).2.2.2.1 j hj).1

theorem lookup_orbit {j : Nat} (hj : j < L.size) : field W L.lookup (L.orbit.get j) = j + 1 :=
  ((shapeOk_iff.mp h.shape).2.2.2.1 j hj).2

theorem lookup_spec {x : Nat} (hx : x < n) (h0 : field W L.lookup x ≠ 0) :
    field W L.lookup x ≤ L.size ∧ L.orbit.get (field W L.lookup x - 1) = x := by
  rcases (shapeOk_iff.mp h.shape).2.2.2.2 x hx with h' | h'
  · exact absurd h' h0
  · exact h'

/-- The orbit as a set of points. -/
def Ω (_ : LevelBase n L rest) : Set (Fin n) := {x | field W L.lookup x.val ≠ 0}

/-- The orbit point `j`. -/
def pt (j : Nat) (hj : j < L.size) : Fin n := ⟨L.orbit.get j, h.orbit_lt hj⟩

/-- The orbit index of a point of the orbit. -/
def idx (_ : LevelBase n L rest) (x : Fin n) : Nat := field W L.lookup x.val - 1

theorem idx_lt {x : Fin n} (hx : x ∈ h.Ω) : h.idx x < L.size := by
  have := (h.lookup_spec x.isLt hx).1
  have h0 : field W L.lookup x.val ≠ 0 := hx
  unfold idx
  omega

theorem pt_idx {x : Fin n} (hx : x ∈ h.Ω) : h.pt (h.idx x) (h.idx_lt hx) = x :=
  Fin.ext (h.lookup_spec x.isLt hx).2

theorem pt_mem {j : Nat} (hj : j < L.size) : h.pt j hj ∈ h.Ω := by
  show field W L.lookup (L.orbit.get j) ≠ 0
  rw [h.lookup_orbit hj]
  omega

theorem idx_pt {j : Nat} (hj : j < L.size) : h.idx (h.pt j hj) = j := by
  show field W L.lookup (L.orbit.get j) - 1 = j
  rw [h.lookup_orbit hj]
  omega

theorem pt_zero : h.pt 0 h.size_pos = ⟨L.base, h.base_lt⟩ := Fin.ext h.orbit_zero

theorem genSet_inv {σ : Equiv.Perm (Fin n)} (hσ : σ ∈ genSet n L) : σ⁻¹ ∈ genSet n L := by
  obtain ⟨s, hs, hsσ⟩ := hσ
  obtain ⟨s', hs', hc⟩ := invClosedOk_iff.mp h.inv s hs
  obtain ⟨τ, hτ⟩ := h.gens s' hs'
  have h1 : Rep n (comp n W s s') (σ * τ) := rep_comp hsσ hτ
  rw [hc] at h1
  have : σ * τ = 1 := h1.unique rep_ident
  refine ⟨s', hs', ?_⟩
  rw [← eq_inv_of_mul_eq_one_right this]
  exact hτ

/-- The facts checked for one Schreier pair. -/
theorem pair_facts {i j : Nat} (hi : i < L.gens.length) (hj : j < L.size) :
    field W L.lookup (field W (gen L i) (L.orbit.get j)) ≠ 0 ∧
      Kernel.sift n W e rest (schreier n W L i j) = true := by
  have hp := (pairsOk_iff 0 _ |>.mp h.pairs) (i * L.size + j) (by omega)
    (calc i * L.size + j < i * L.size + L.size := by omega
      _ = (i + 1) * L.size := (Nat.succ_mul _ _).symm
      _ ≤ L.gens.length * L.size := Nat.mul_le_mul_right _ hi)
  have hdiv : (i * L.size + j) / L.size = i := by
    rw [Nat.add_comm, Nat.add_mul_div_right _ _ h.size_pos, Nat.div_eq_of_lt hj, Nat.zero_add]
  have hmod : (i * L.size + j) % L.size = j := by
    rw [Nat.add_comm, Nat.add_mul_mod_self_right, Nat.mod_eq_of_lt hj]
  rwa [hdiv, hmod] at hp

theorem gen_maps {σ : Equiv.Perm (Fin n)} (hσ : σ ∈ genSet n L) {x : Fin n} (hx : x ∈ h.Ω) :
    σ x ∈ h.Ω := by
  obtain ⟨s, hs, hsσ⟩ := hσ
  obtain ⟨i, hi, rfl⟩ := exists_gen_eq hs
  have hp := h.pair_facts hi (h.idx_lt hx)
  have hx' : L.orbit.get (h.idx x) = x.val := (h.lookup_spec x.isLt hx).2
  show field W L.lookup (σ x).val ≠ 0
  rw [← hsσ x, ← hx']
  exact hp.1

theorem group_maps {σ : Equiv.Perm (Fin n)} (hσ : σ ∈ levelGroup n L) :
    ∀ x ∈ h.Ω, σ x ∈ h.Ω := by
  induction hσ using Subgroup.closure_induction_left with
  | one => intro x hx; exact hx
  | mul_left a ha b _ ih => intro x hx; exact h.gen_maps ha (ih x hx)
  | inv_mul_cancel a ha b _ ih => intro x hx; exact h.gen_maps (h.genSet_inv ha) (ih x hx)

theorem trans_exists : ∀ j (hj : j < L.size), ∃ τ ∈ levelGroup n L,
    Rep n (L.reps.get j) τ ∧ τ ⟨L.base, h.base_lt⟩ = h.pt j hj := by
  have ht := transversalOk_iff.mp h.trans
  intro j
  induction j using Nat.strong_induction_on with
  | _ j ih =>
    intro hj
    by_cases hj0 : j = 0
    · subst hj0
      refine ⟨1, one_mem _, ?_, ?_⟩
      · rw [ht.1]; exact rep_ident
      · rw [h.pt_zero]; rfl
    · obtain ⟨hi, hk, hedge, hrep⟩ := ht.2.1 j hj hj0
      obtain ⟨τ, hτG, hτ, hτb⟩ := ih _ hk (by omega)
      obtain ⟨σ, hσ⟩ := h.gens _ (gen_mem hi)
      refine ⟨σ * τ, mul_mem (Subgroup.subset_closure ⟨_, gen_mem hi, hσ⟩) hτG, ?_, ?_⟩
      · rw [hrep]; exact rep_comp hσ hτ
      · apply Fin.ext
        rw [Equiv.Perm.mul_apply, hτb, ← hσ]
        exact hedge

/-- The transversal element for orbit point `j`. -/
noncomputable def tr (j : Nat) : Equiv.Perm (Fin n) :=
  if hj : j < L.size then Classical.choose (h.trans_exists j hj) else 1

theorem tr_spec {j : Nat} (hj : j < L.size) :
    h.tr j ∈ levelGroup n L ∧ Rep n (L.reps.get j) (h.tr j) ∧
      h.tr j ⟨L.base, h.base_lt⟩ = h.pt j hj := by
  unfold tr
  simp only [hj, ↓reduceDIte]
  exact Classical.choose_spec (h.trans_exists j hj)

theorem tr_mem {j : Nat} (hj : j < L.size) : h.tr j ∈ levelGroup n L := (h.tr_spec hj).1

theorem tr_apply {j : Nat} (hj : j < L.size) : h.tr j ⟨L.base, h.base_lt⟩ = h.pt j hj :=
  (h.tr_spec hj).2.2

theorem rep_reps {j : Nat} (hj : j < L.size) : Rep n (L.reps.get j) (h.tr j) := (h.tr_spec hj).2.1

theorem rep_invs {j : Nat} (hj : j < L.size) : Rep n (L.invs.get j) (h.tr j)⁻¹ :=
  rep_of_comp_eq_ident (h.rep_reps hj) ((transversalOk_iff.mp h.trans).2.2 j hj)

theorem tr_zero : h.tr 0 = 1 := by
  have := h.rep_reps h.size_pos
  rw [(transversalOk_iff.mp h.trans).1] at this
  exact this.unique rep_ident

/-- The permutation represented by generator `i`. -/
theorem rep_gen {i : Nat} (hi : i < L.gens.length) : ∃ σ, Rep n (gen L i) σ :=
  h.gens _ (gen_mem hi)

/-- The Schreier element of `σ` at orbit point `j`. -/
noncomputable def schreierElt (σ : Equiv.Perm (Fin n)) (j : Nat) (hj : j < L.size) :
    Equiv.Perm (Fin n) :=
  (h.tr (h.idx (σ (h.pt j hj))))⁻¹ * σ * h.tr j

theorem rep_schreier {i j : Nat} (hi : i < L.gens.length) (hj : j < L.size)
    {σ : Equiv.Perm (Fin n)} (hσ : Rep n (gen L i) σ) :
    Rep n (schreier n W L i j) (h.schreierElt σ j hj) := by
  have hk : field W L.lookup (field W (gen L i) (L.orbit.get j)) - 1 = h.idx (σ (h.pt j hj)) := by
    unfold idx
    rw [← hσ]
    rfl
  have hk' : Nat.sub (field W L.lookup (field W (gen L i) (L.orbit.get j))) 1 =
      h.idx (σ (h.pt j hj)) := hk
  unfold schreier schreierElt
  simp only
  rw [hk', mul_assoc]
  exact rep_comp (h.rep_invs (h.idx_lt (h.gen_maps ⟨_, gen_mem hi, hσ⟩ (h.pt_mem hj))))
    (rep_comp hσ (h.rep_reps hj))

theorem schreierElt_fixes {σ : Equiv.Perm (Fin n)} (hσ : ∀ x ∈ h.Ω, σ x ∈ h.Ω)
    {j : Nat} (hj : j < L.size) :
    h.schreierElt σ j hj ⟨L.base, h.base_lt⟩ = ⟨L.base, h.base_lt⟩ := by
  have hm := hσ _ (h.pt_mem hj)
  unfold schreierElt
  rw [Equiv.Perm.mul_apply, Equiv.Perm.mul_apply, h.tr_apply hj, Equiv.Perm.inv_eq_iff_eq,
    h.tr_apply (h.idx_lt hm), h.pt_idx hm]

theorem schreierElt_mem {σ : Equiv.Perm (Fin n)} (hσ : σ ∈ levelGroup n L)
    {j : Nat} (hj : j < L.size) : h.schreierElt σ j hj ∈ levelGroup n L := by
  have hm := h.group_maps hσ _ (h.pt_mem hj)
  exact mul_mem (mul_mem (inv_mem (h.tr_mem (h.idx_lt hm))) hσ) (h.tr_mem hj)

/-- The next level's generators are Schreier elements of this level. -/
theorem next_gens {L' : Level} {rest' : List Level} (hrest : rest = L' :: rest')
    {t : Nat} (ht : t ∈ L'.gens) :
    ∃ τ, Rep n t τ ∧ τ ∈ levelGroup n L ∧ τ ⟨L.base, h.base_lt⟩ = ⟨L.base, h.base_lt⟩ := by
  subst hrest
  obtain ⟨hlen, hall⟩ := (nextOk_iff _).mp h.next
  simp only [headGens] at hlen hall
  obtain ⟨m, hm, rfl⟩ := List.getElem_of_mem ht
  have hq : (L.next[m]'(by omega), L'.gens[m]) ∈ L.next.zip L'.gens :=
    List.mem_iff_getElem.mpr ⟨m, by simp [List.length_zip]; omega, by simp [List.getElem_zip]⟩
  obtain ⟨hi, hj, hs⟩ := hall _ hq
  obtain ⟨σ, hσ⟩ := h.rep_gen hi
  have hσG : σ ∈ levelGroup n L := Subgroup.subset_closure ⟨_, gen_mem hi, hσ⟩
  refine ⟨h.schreierElt σ _ hj, ?_, h.schreierElt_mem hσG hj,
    h.schreierElt_fixes (h.group_maps hσG) hj⟩
  simp only at hs
  rw [← hs]
  exact h.rep_schreier hi hj hσ

end LevelBase

/-- The checks of one level together with the soundness of sifting through the
levels after it. -/
structure LevelHyp (n : Nat) (L : Level) (rest : List Level) : Prop
    extends LevelBase n L rest where
  sift : ∀ x σ, Rep n x σ → Canon n x →
    (sift n (width n) (ident n (width n)) rest x = true ↔ σ ∈ groupOf n rest)

namespace LevelHyp

variable (h : LevelHyp n L rest)
include h

theorem gen_schreier_mem {σ : Equiv.Perm (Fin n)} (hσ : σ ∈ genSet n L)
    {j : Nat} (hj : j < L.size) : h.schreierElt σ j hj ∈ groupOf n rest := by
  obtain ⟨s, hs, hsσ⟩ := hσ
  obtain ⟨i, hi, rfl⟩ := exists_gen_eq hs
  exact (h.sift _ _ (h.rep_schreier hi hj hsσ) (canon_comp _ _)).mp (h.pair_facts hi hj).2

/-- Schreier's lemma for the certified transversal. -/
theorem schreier_mem {σ : Equiv.Perm (Fin n)} (hσ : σ ∈ levelGroup n L) :
    ∀ j (hj : j < L.size), h.schreierElt σ j hj ∈ groupOf n rest := by
  induction hσ using Subgroup.closure_induction_left with
  | one =>
    intro j hj
    unfold LevelBase.schreierElt
    rw [Equiv.Perm.one_apply, h.idx_pt hj, mul_one, inv_mul_cancel]
    exact one_mem _
  | mul_left a ha b hb ih =>
    intro j hj
    have hm := h.group_maps hb _ (h.pt_mem hj)
    have hk := h.idx_lt hm
    have := mul_mem (h.gen_schreier_mem ha hk) (ih j hj)
    unfold LevelBase.schreierElt at this ⊢
    rw [h.pt_idx hm] at this
    simpa [mul_assoc] using this
  | inv_mul_cancel a ha b hb ih =>
    intro j hj
    have hm := h.group_maps hb _ (h.pt_mem hj)
    have hk := h.idx_lt hm
    have := mul_mem (h.gen_schreier_mem (h.genSet_inv ha) hk) (ih j hj)
    unfold LevelBase.schreierElt at this ⊢
    rw [h.pt_idx hm] at this
    simpa [mul_assoc] using this

theorem mem_rest_of_fixes {σ : Equiv.Perm (Fin n)} (hσ : σ ∈ levelGroup n L)
    (hb : σ ⟨L.base, h.base_lt⟩ = ⟨L.base, h.base_lt⟩) : σ ∈ groupOf n rest := by
  have := h.schreier_mem hσ 0 h.size_pos
  unfold LevelBase.schreierElt at this
  rw [h.pt_zero, hb, ← h.pt_zero, h.idx_pt, h.tr_zero, inv_one, one_mul, mul_one] at this
  exact this

theorem rest_le : groupOf n rest ≤ levelGroup n L ⊓
    MulAction.stabilizer (Equiv.Perm (Fin n)) (⟨L.base, h.base_lt⟩ : Fin n) := by
  match hr : rest with
  | [] => exact bot_le
  | L' :: rest' =>
    show Subgroup.closure (genSet n L') ≤ _
    rw [Subgroup.closure_le]
    rintro τ ⟨t, ht, htτ⟩
    obtain ⟨τ', hτ', hG, hb⟩ := h.next_gens rfl ht
    rw [htτ.unique hτ']
    exact ⟨hG, hb⟩

theorem mem_rest_iff {σ : Equiv.Perm (Fin n)} : σ ∈ groupOf n rest ↔
    σ ∈ levelGroup n L ∧ σ ⟨L.base, h.base_lt⟩ = ⟨L.base, h.base_lt⟩ := by
  constructor
  · intro hσ
    exact ⟨(h.rest_le hσ).1, (h.rest_le hσ).2⟩
  · rintro ⟨hσ, hb⟩
    exact h.mem_rest_of_fixes hσ hb

theorem base_mem : (⟨L.base, h.base_lt⟩ : Fin n) ∈ h.Ω := by
  rw [← h.pt_zero]
  exact h.pt_mem _

/-- Sifting from this level accepts exactly the packings of its subgroup. -/
theorem sift_iff {x : Nat} {σ : Equiv.Perm (Fin n)} (hx : Rep n x σ) :
    Kernel.sift n W e (L :: rest) x = true ↔ σ ∈ levelGroup n L := by
  have hxb : field W x L.base = (σ ⟨L.base, h.base_lt⟩).val := hx ⟨L.base, h.base_lt⟩
  simp only [Kernel.sift, hxb]
  by_cases hΩ : σ ⟨L.base, h.base_lt⟩ ∈ h.Ω
  · have h0 : field W L.lookup (σ ⟨L.base, h.base_lt⟩).val ≠ 0 := hΩ
    have hk := h.idx_lt hΩ
    rw [show Nat.beq (field W L.lookup (σ ⟨L.base, h.base_lt⟩).val) 0 = false by
      simpa [beq_eq_decide] using h0, Bool.cond_false]
    have hk' : Nat.sub (field W L.lookup (σ ⟨L.base, h.base_lt⟩).val) 1 =
        h.idx (σ ⟨L.base, h.base_lt⟩) := rfl
    rw [hk', h.sift _ _ (rep_comp (h.rep_invs hk) hx) (canon_comp _ _), h.mem_rest_iff]
    constructor
    · rintro ⟨hG, _⟩
      have := mul_mem (h.tr_mem hk) hG
      rwa [← mul_assoc, mul_inv_cancel, one_mul] at this
    · intro hσ
      refine ⟨mul_mem (inv_mem (h.tr_mem hk)) hσ, ?_⟩
      rw [Equiv.Perm.mul_apply, Equiv.Perm.inv_eq_iff_eq, h.tr_apply hk, h.pt_idx hΩ]
  · have h0 : field W L.lookup (σ ⟨L.base, h.base_lt⟩).val = 0 := by
      by_contra hne; exact hΩ hne
    rw [h0]
    simp only [Nat.beq_refl, Bool.cond_true, Bool.false_eq_true, false_iff]
    intro hσ
    exact hΩ (h.group_maps hσ _ h.base_mem)

/-- Orbit–stabilizer for the certified level. -/
theorem card_eq : Nat.card (levelGroup n L) = L.size * Nat.card (groupOf n rest) := by
  set G := levelGroup n L
  set b : Fin n := ⟨L.base, h.base_lt⟩
  have hstab : MulAction.stabilizer G b = (groupOf n rest).subgroupOf G := by
    ext g
    rw [MulAction.mem_stabilizer_iff, Subgroup.mem_subgroupOf, h.mem_rest_iff]
    exact ⟨fun hg => ⟨g.2, hg⟩, fun hg => hg.2⟩
  have horbit : MulAction.orbit G b = h.Ω := by
    ext y
    constructor
    · rintro ⟨g, rfl⟩
      exact h.group_maps g.2 _ h.base_mem
    · intro hy
      refine ⟨⟨h.tr (h.idx y), h.tr_mem (h.idx_lt hy)⟩, ?_⟩
      show h.tr (h.idx y) b = y
      rw [h.tr_apply (h.idx_lt hy), h.pt_idx hy]
  have hΩ : h.Ω.ncard = L.size := by
    have hrange : h.Ω = Set.range fun j : Fin L.size => h.pt j.val j.isLt := by
      ext y
      constructor
      · intro hy
        exact ⟨⟨h.idx y, h.idx_lt hy⟩, h.pt_idx hy⟩
      · rintro ⟨j, rfl⟩
        exact h.pt_mem j.isLt
    rw [hrange, Set.ncard_range_of_injective, Nat.card_eq_fintype_card, Fintype.card_fin]
    intro j k hjk
    have := congrArg h.idx hjk
    simp only [h.idx_pt] at this
    exact Fin.ext this
  have hle : groupOf n rest ≤ G := fun g hg => (h.rest_le hg).1
  have hmul := Subgroup.card_mul_index (MulAction.stabilizer G b)
  rw [MulAction.index_stabilizer, horbit, hΩ, hstab,
    Nat.card_congr (Subgroup.subgroupOfEquivOfLe hle).toEquiv] at hmul
  rw [← hmul, Nat.mul_comm]

end LevelHyp

end Level

/-! # The whole certificate -/

section Sound

variable {n : Nat}

local notation "W" => width n
local notation "e" => ident n (width n)

theorem levelsOk_cons {L : Level} {rest : List Level} :
    levelsOk n W e (L :: rest) = true ↔
      (shapeOk n W L = true ∧ invClosedOk n W e L = true ∧ transversalOk n W e L = true ∧
        nextOk n W L (headGens rest) = true) ∧
      pairsOk n W e L rest 0 (L.gens.length * L.size) = true ∧ levelsOk n W e rest = true := by
  simp only [levelsOk, levelOk, Bool.and_eq_true, mul_eq, and_assoc]

theorem order_cons (L : Level) (rest : List Level) : order (L :: rest) = L.size * order rest := rfl

/-- Soundness of sifting and of the order, from the last level upward. -/
theorem levels_sound : ∀ ls : List Level, levelsOk n W e ls = true →
    (∀ s ∈ headGens ls, ∃ σ, Rep n s σ) →
    (∀ x σ, Rep n x σ → Canon n x → (Kernel.sift n W e ls x = true ↔ σ ∈ groupOf n ls)) ∧
      Nat.card (groupOf n ls) = order ls
  | [], _, _ => by
    refine ⟨fun x σ hx hc => ?_, by simp [groupOf, order]⟩
    simp only [Kernel.sift, groupOf, Subgroup.mem_bot, beq_eq_decide, decide_eq_true_eq]
    constructor
    · rintro rfl
      exact hx.unique rep_ident
    · rintro rfl
      exact hc.eq_of_rep canon_ident hx rep_ident
  | L :: rest, hok, hgens => by
    obtain ⟨⟨hs, hi, ht, hn⟩, hp, hrest⟩ := levelsOk_cons.mp hok
    have base : LevelBase n L rest := ⟨hs, hi, ht, hn, hp, hgens⟩
    have hgens' : ∀ s ∈ headGens rest, ∃ σ, Rep n s σ := by
      match hr : rest with
      | [] => simp [headGens]
      | L' :: rest' =>
        intro t htt
        obtain ⟨τ, hτ, -⟩ := base.next_gens rfl htt
        exact ⟨τ, hτ⟩
    obtain ⟨ih₁, ih₂⟩ := levels_sound rest hrest hgens'
    have hyp : LevelHyp n L rest := { base with sift := ih₁ }
    refine ⟨fun x σ hx _ => hyp.sift_iff hx, ?_⟩
    show Nat.card (levelGroup n L) = _
    rw [hyp.card_eq, ih₂, order_cons]

theorem check_iff (inputs : List Nat) (c : Certificate) : check n inputs c = true ↔
    inputsOk n W e inputs c = true ∧ levelsOk n W e c = true := by
  simp [check]

/-- The first level's subgroup of an accepted certificate is the closure of the inputs. -/
theorem groupOf_eq_closure {S : Array (Perm n)} {c : Certificate}
    (h : check n (S.toList.map pack) c = true) : groupOf n c = closure S := by
  obtain ⟨hin, hlv⟩ := (check_iff _ _).mp h
  simp only [inputsOk, Bool.and_eq_true, List.all_eq_true, List.any_eq_true, List.mem_map,
    Bool.or_eq_true, beq_eq_decide, decide_eq_true_eq] at hin
  obtain ⟨hsift, hhead⟩ := hin
  have hgens : ∀ s ∈ headGens c, ∃ σ, Rep n s σ ∧ σ ∈ closure S := by
    intro s hs
    obtain ⟨x, ⟨p, hpS, rfl⟩, hx⟩ := hhead s hs
    have hpc : p.toEquiv ∈ closure S :=
      Subgroup.subset_closure ⟨p, Array.mem_toList_iff.mp hpS, rfl⟩
    rcases hx with rfl | hx
    · exact ⟨_, rep_pack p, hpc⟩
    · exact ⟨_, rep_of_comp_eq_ident (rep_pack p) hx, inv_mem hpc⟩
  have hsound := levels_sound c hlv fun s hs => (hgens s hs).imp fun _ h => h.1
  apply le_antisymm
  · match hc : c with
    | [] => exact bot_le
    | L :: _ =>
      show Subgroup.closure (genSet n L) ≤ _
      rw [Subgroup.closure_le]
      rintro σ ⟨s, hs, hsσ⟩
      obtain ⟨τ, hτ, hτS⟩ := hgens s hs
      rwa [hsσ.unique hτ]
  · unfold closure
    rw [Subgroup.closure_le]
    rintro _ ⟨p, hp, rfl⟩
    exact (hsound.1 _ _ (rep_pack p) (canon_pack p)).mp
      (hsift _ ⟨p, Array.mem_toList_iff.mpr hp, rfl⟩)

/-- An accepted certificate decides membership of every permutation in the
subgroup generated by the inputs. -/
theorem sift_pack_iff {S : Array (Perm n)} {c : Certificate}
    (h : check n (S.toList.map pack) c = true) (p : Perm n) :
    Kernel.sift n W e c (pack p) = true ↔ p.toEquiv ∈ closure S := by
  obtain ⟨hin, hlv⟩ := (check_iff _ _).mp h
  rw [← groupOf_eq_closure h]
  refine ((levels_sound c hlv ?_).1 _ _ (rep_pack p) (canon_pack p))
  intro s hs
  simp only [inputsOk, Bool.and_eq_true, List.all_eq_true, List.any_eq_true, List.mem_map,
    Bool.or_eq_true, beq_eq_decide, decide_eq_true_eq] at hin
  obtain ⟨x, ⟨q, -, rfl⟩, hx⟩ := hin.2 s hs
  rcases hx with rfl | hx
  · exact ⟨_, rep_pack q⟩
  · exact ⟨_, rep_of_comp_eq_ident (rep_pack q) hx⟩

/-- An accepted certificate gives the order of the subgroup generated by the inputs. -/
theorem card_closure {S : Array (Perm n)} {c : Certificate}
    (h : check n (S.toList.map pack) c = true) : Nat.card (closure S) = order c := by
  obtain ⟨hin, hlv⟩ := (check_iff _ _).mp h
  rw [← groupOf_eq_closure h]
  refine (levels_sound c hlv ?_).2
  intro s hs
  simp only [inputsOk, Bool.and_eq_true, List.all_eq_true, List.any_eq_true, List.mem_map,
    Bool.or_eq_true, beq_eq_decide, decide_eq_true_eq] at hin
  obtain ⟨x, ⟨q, -, rfl⟩, hx⟩ := hin.2 s hs
  rcases hx with rfl | hx
  · exact ⟨_, rep_pack q⟩
  · exact ⟨_, rep_of_comp_eq_ident (rep_pack q) hx⟩

end Sound

/-! # Statements for closed generating lists

The `perm_group` tactic instantiates these with a list `gs` of closed
generators, a certificate literal and kernel-checked hypotheses. -/

section Closed

variable {n : Nat}

/-- The permutation of `Fin n` sending `i` to `l[i]`, or the identity when `l` is
not the image list of a permutation of `Fin n`. A statement using it contains
only a list of numerals, so it elaborates in time linear in its length, unlike
a long product of cycles. -/
@[expose] def permOfImages (n : Nat) (l : List Nat) : Equiv.Perm (Fin n) :=
  match Perm.ofNatArray? n l.toArray with
  | some p => p.toEquiv
  | none => 1

/-- Bitset check that `l` lists distinct values below `n`, none of them in `seen`. -/
@[expose] def imagesDistinct (n : Nat) : List Nat → Nat → Bool
  | [], _ => true
  | x :: xs, seen =>
    Nat.blt x n && Nat.beq (Nat.land (Nat.shiftRight seen x) 1) 0 &&
      imagesDistinct n xs (Nat.lor seen (Nat.shiftLeft 1 x))

/-- `l` is the image list of a permutation of `Fin n`, checked in time linear in `n`. -/
@[expose] def imagesOk (n : Nat) (l : List Nat) : Bool :=
  Nat.beq l.length n && imagesDistinct n l 0

/-- The packing of an image list. -/
@[expose] def packList (n : Nat) (l : List Nat) : Nat :=
  packFn (width n) (fun i => l.getD i 0) n

theorem imagesDistinct_spec (n : Nat) : ∀ (l : List Nat) (seen : Nat),
    imagesDistinct n l seen = true →
      (∀ x ∈ l, x < n ∧ seen.testBit x = false) ∧ l.Nodup
  | [], _, _ => by simp
  | x :: xs, seen, h => by
    simp only [imagesDistinct, Bool.and_eq_true, blt_eq_decide, beq_eq_decide,
      decide_eq_true_eq] at h
    obtain ⟨⟨hx, hbit⟩, hrest⟩ := h
    have hxbit : seen.testBit x = false := by
      simp only [land_eq, shiftRight_eq, Nat.and_one_is_mod] at hbit
      simp [Nat.testBit, hbit]
    obtain ⟨ih₁, ih₂⟩ := imagesDistinct_spec n xs _ hrest
    have hne : ∀ y ∈ xs, y < n ∧ seen.testBit y = false ∧ y ≠ x := by
      intro y hy
      obtain ⟨hy₁, hy₂⟩ := ih₁ y hy
      simp only [lor_eq, shiftLeft_eq, Nat.one_shiftLeft, Nat.testBit_or,
        Nat.testBit_two_pow, Bool.or_eq_false_iff, decide_eq_false_iff_not] at hy₂
      exact ⟨hy₁, hy₂.1, fun h => hy₂.2 h.symm⟩
    refine ⟨?_, List.nodup_cons.mpr ⟨fun hmem => (hne x hmem).2.2 rfl, ih₂⟩⟩
    intro y hy
    rcases List.mem_cons.mp hy with rfl | hy
    · exact ⟨hx, hxbit⟩
    · exact ⟨(hne y hy).1, (hne y hy).2.1⟩

theorem imagesOk_spec {n : Nat} {l : List Nat} (h : imagesOk n l = true) :
    l.length = n ∧ (∀ x ∈ l, x < n) ∧ l.Nodup := by
  simp only [imagesOk, Bool.and_eq_true, beq_eq_decide, decide_eq_true_eq] at h
  obtain ⟨hl, hd⟩ := imagesDistinct_spec n l 0 h.2
  exact ⟨h.1, fun x hx => (hl x hx).1, hd⟩

/-- Every value below `n` occurs in an accepted image list. -/
theorem mem_of_imagesOk {n : Nat} {l : List Nat} (h : imagesOk n l = true) {i : Nat}
    (hi : i < n) : i ∈ l := by
  obtain ⟨hlen, hlt, hnd⟩ := imagesOk_spec h
  have hsub : l.toFinset ⊆ Finset.range n := fun x hx =>
    Finset.mem_range.mpr (hlt x (List.mem_toFinset.mp hx))
  have hcard : (Finset.range n).card ≤ l.toFinset.card := by
    rw [Finset.card_range, List.toFinset_card_of_nodup hnd, hlen]
  have := Finset.eq_of_subset_of_card_le hsub hcard
  exact List.mem_toFinset.mp (this ▸ Finset.mem_range.mpr hi)

theorem ofNatArray_permOfImages {n : Nat} {l : List Nat} (h : imagesOk n l = true) :
    ∃ p, Perm.ofNatArray? n l.toArray = some p := by
  obtain ⟨hlen, hlt, hnd⟩ := imagesOk_spec h
  have hc : l.toArray.size = n ∧ ∀ i, (hi : i < l.toArray.size) → l.toArray[i] < n :=
    ⟨by simpa using hlen, fun i hi => hlt _ (by simp)⟩
  rw [Perm.ofNatArray?]
  split
  case isFalse hn => exact absurd hc hn
  apply Option.isSome_iff_exists.mp
  rw [Perm.isSome_ofVector?]
  have hmap : ((Hex.Vector.ofFn' fun i : Fin n =>
      (⟨l.toArray[i.val]'(hc.1.symm ▸ i.isLt), hc.2 i.val (hc.1.symm ▸ i.isLt)⟩ : Fin n)).toList.map
        Fin.val) = l := by
    apply List.ext_getElem
    · simp [hlen]
    · intro i h₁ h₂
      simp [Hex.Vector.ofFn'_eq_ofFn]
  constructor
  · exact List.Nodup.of_map Fin.val (by rw [hmap]; exact hnd)
  · intro i
    have : i.val ∈ l := mem_of_imagesOk h i.isLt
    rw [← hmap] at this
    obtain ⟨j, hj, hji⟩ := List.mem_map.mp this
    rwa [Fin.ext hji] at hj

theorem pack_ofEquiv_permOfImages {n : Nat} {l : List Nat} (h : imagesOk n l = true) :
    pack (Perm.ofEquiv (permOfImages n l)) = packList n l := by
  obtain ⟨p, hp⟩ := ofNatArray_permOfImages h
  have hperm : permOfImages n l = p.toEquiv := by simp [permOfImages, hp]
  rw [hperm, Perm.ofEquiv_toEquiv]
  obtain ⟨hlen, hlt, -⟩ := imagesOk_spec h
  have hval : ∀ i : Fin n, (p.get i).val = l.getD i.val 0 := by
    intro i
    rw [Perm.val_get_of_ofNatArray? hp]
    simp [List.getD_eq_getElem?_getD]
  have hbound : ∀ i < n, l.getD i 0 < 2 ^ width n := fun i hi =>
    Nat.lt_trans (hlt _ (by
      rw [List.getD_eq_getElem?_getD, List.getElem?_eq_getElem (by omega), Option.getD_some]
      exact List.getElem_mem _))
      (lt_two_pow_width n)
  refine Canon.eq_of_rep (canon_pack p) (canon_packFn _ hbound) (rep_pack p) fun i => ?_
  rw [packList, field_packFn _ _ n hbound _ i.isLt, ← hval]
  simp

/-- The image list of a permutation, read by the tactic in compiled code. -/
def images (n : Nat) (g : Equiv.Perm (Fin n)) : List Nat :=
  (List.finRange n).map fun i => (g i).val

theorem levelsOk_cons_of {L : Level} {rest : List Level} {N : Nat}
    (hl : levelOk n (width n) (ident n (width n)) L rest = true)
    (hN : Nat.mul L.gens.length L.size = N)
    (hp : pairsOk n (width n) (ident n (width n)) L rest 0 N = true)
    (hr : levelsOk n (width n) (ident n (width n)) rest = true) :
    levelsOk n (width n) (ident n (width n)) (L :: rest) = true := by
  subst hN
  simp only [levelsOk, hl, hp, hr, Bool.and_self]

theorem levelsOk_nil : levelsOk n (width n) (ident n (width n)) [] = true := rfl

theorem check_of {inputs : List Nat} {c : Certificate}
    (hi : inputsOk n (width n) (ident n (width n)) inputs c = true)
    (hl : levelsOk n (width n) (ident n (width n)) c = true) : check n inputs c = true := by
  simp only [check, hi, hl, Bool.and_self]

theorem setOf_mem_cons {α : Type} (a b : α) (l : List α) :
    {x | x ∈ a :: b :: l} = insert a {x | x ∈ b :: l} := by
  ext x
  simp

theorem setOf_mem_singleton {α : Type} (a : α) : {x | x ∈ [a]} = ({a} : Set α) := by
  ext x
  simp

theorem setOf_mem_nil {α : Type} : {x | x ∈ ([] : List α)} = (∅ : Set α) := by
  ext x
  simp

theorem closure_ofEquiv (gs : List (Equiv.Perm (Fin n))) :
    closure (gs.map Perm.ofEquiv).toArray = Subgroup.closure {x | x ∈ gs} := by
  unfold closure
  congr 1
  ext x
  simp

theorem map_pack_nil : (([] : List (Equiv.Perm (Fin n))).map Perm.ofEquiv).map pack = [] :=
  rfl

theorem map_pack_cons {g : Equiv.Perm (Fin n)} {gs : List (Equiv.Perm (Fin n))} {x : Nat}
    {xs : List Nat} (h : pack (Perm.ofEquiv g) = x) (t : (gs.map Perm.ofEquiv).map pack = xs) :
    ((g :: gs).map Perm.ofEquiv).map pack = x :: xs := by
  simp [h, ← t]

theorem check_gs {gs : List (Equiv.Perm (Fin n))} {inputs : List Nat} {c : Certificate}
    (hS : (gs.map Perm.ofEquiv).map pack = inputs) (h : check n inputs c = true) :
    check n ((gs.map Perm.ofEquiv).toArray.toList.map pack) c = true := by
  simpa [hS] using h

theorem card_of_check {gs : List (Equiv.Perm (Fin n))} {inputs : List Nat} {c : Certificate}
    {N : Nat} (hS : (gs.map Perm.ofEquiv).map pack = inputs) (h : check n inputs c = true)
    (hN : order c = N) : Nat.card (Subgroup.closure {x | x ∈ gs}) = N := by
  rw [← closure_ofEquiv, card_closure (check_gs hS h), hN]

theorem mem_of_check {gs : List (Equiv.Perm (Fin n))} {inputs : List Nat} {c : Certificate}
    {g : Equiv.Perm (Fin n)} {x : Nat} (hS : (gs.map Perm.ofEquiv).map pack = inputs)
    (h : check n inputs c = true) (hx : pack (Perm.ofEquiv g) = x)
    (hs : Kernel.sift n (width n) (ident n (width n)) c x = true) :
    g ∈ Subgroup.closure {x | x ∈ gs} := by
  rw [← closure_ofEquiv]
  have := (sift_pack_iff (check_gs hS h) (Perm.ofEquiv g)).mp (hx ▸ hs)
  simpa using this

theorem not_mem_of_check {gs : List (Equiv.Perm (Fin n))} {inputs : List Nat} {c : Certificate}
    {g : Equiv.Perm (Fin n)} {x : Nat} (hS : (gs.map Perm.ofEquiv).map pack = inputs)
    (h : check n inputs c = true) (hx : pack (Perm.ofEquiv g) = x)
    (hs : Kernel.sift n (width n) (ident n (width n)) c x = false) :
    g ∉ Subgroup.closure {x | x ∈ gs} := by
  rw [← closure_ofEquiv]
  intro hg
  have := (sift_pack_iff (check_gs hS h) (Perm.ofEquiv g)).mpr (by simpa using hg)
  rw [hx, hs] at this
  exact Bool.false_ne_true this

theorem eq_top_of_check {gs : List (Equiv.Perm (Fin n))} {inputs : List Nat} {c : Certificate}
    (hS : (gs.map Perm.ofEquiv).map pack = inputs) (h : check n inputs c = true)
    (hN : order c = n.factorial) : Subgroup.closure {x | x ∈ gs} = ⊤ := by
  rw [← Subgroup.card_eq_iff_eq_top, card_of_check hS h hN, Nat.card_perm, Nat.card_eq_fintype_card,
    Fintype.card_fin]

end Closed

end Hex.PermGroup.Kernel
