/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Coefficients

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Imported C(2, 12), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_2_12 : FpPoly 2 :=
  { coeffs := #[(1 : ZMod64 2), 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(2, 12). -/
@[simp, grind .] theorem luebeckConwayPolynomial_2_12_monic : DensePoly.Monic luebeckConwayPolynomial_2_12 := by rfl

/-- Positive degree of C(2, 12). -/
@[simp, grind .] theorem luebeckConwayPolynomial_2_12_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_2_12 := by decide

/-- Lookup identifies the imported C(2, 12). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_2_12 :
    luebeckConwayPolynomial? 2 12 = some luebeckConwayPolynomial_2_12 := by
  show some (luebeckConwayPolynomialOfCoeffs 2 [1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1]) = some luebeckConwayPolynomial_2_12
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 2 [1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1]) k =
        ([1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 2 m)).getD k
          (Zero.zero : ZMod64 2) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_2_12]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | 5 => rfl
  | 6 => rfl
  | 7 => rfl
  | 8 => rfl
  | 9 => rfl
  | 10 => rfl
  | 11 => rfl
  | 12 => rfl
  | _ + 13 => rfl

/-- Imported C(5, 8), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_5_8 : FpPoly 5 :=
  { coeffs := #[(2 : ZMod64 5), 4, 3, 0, 1, 0, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(5, 8). -/
@[simp, grind .] theorem luebeckConwayPolynomial_5_8_monic : DensePoly.Monic luebeckConwayPolynomial_5_8 := by rfl

/-- Positive degree of C(5, 8). -/
@[simp, grind .] theorem luebeckConwayPolynomial_5_8_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_5_8 := by decide

/-- Lookup identifies the imported C(5, 8). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_5_8 :
    luebeckConwayPolynomial? 5 8 = some luebeckConwayPolynomial_5_8 := by
  show some (luebeckConwayPolynomialOfCoeffs 5 [2, 4, 3, 0, 1, 0, 0, 0, 1]) = some luebeckConwayPolynomial_5_8
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 5 [2, 4, 3, 0, 1, 0, 0, 0, 1]) k =
        ([2, 4, 3, 0, 1, 0, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 5 m)).getD k
          (Zero.zero : ZMod64 5) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_5_8]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | 5 => rfl
  | 6 => rfl
  | 7 => rfl
  | 8 => rfl
  | _ + 9 => rfl

/-- Imported C(2, 10), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_2_10 : FpPoly 2 :=
  { coeffs := #[(1 : ZMod64 2), 1, 1, 1, 0, 1, 1, 0, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(2, 10). -/
@[simp, grind .] theorem luebeckConwayPolynomial_2_10_monic : DensePoly.Monic luebeckConwayPolynomial_2_10 := by rfl

/-- Positive degree of C(2, 10). -/
@[simp, grind .] theorem luebeckConwayPolynomial_2_10_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_2_10 := by decide

/-- Lookup identifies the imported C(2, 10). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_2_10 :
    luebeckConwayPolynomial? 2 10 = some luebeckConwayPolynomial_2_10 := by
  show some (luebeckConwayPolynomialOfCoeffs 2 [1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1]) = some luebeckConwayPolynomial_2_10
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 2 [1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1]) k =
        ([1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 2 m)).getD k
          (Zero.zero : ZMod64 2) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_2_10]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | 5 => rfl
  | 6 => rfl
  | 7 => rfl
  | 8 => rfl
  | 9 => rfl
  | 10 => rfl
  | _ + 11 => rfl

/-- Imported C(13, 6), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_13_6 : FpPoly 13 :=
  { coeffs := #[(2 : ZMod64 13), 11, 11, 10, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(13, 6). -/
@[simp, grind .] theorem luebeckConwayPolynomial_13_6_monic : DensePoly.Monic luebeckConwayPolynomial_13_6 := by rfl

/-- Positive degree of C(13, 6). -/
@[simp, grind .] theorem luebeckConwayPolynomial_13_6_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_13_6 := by decide

/-- Lookup identifies the imported C(13, 6). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_13_6 :
    luebeckConwayPolynomial? 13 6 = some luebeckConwayPolynomial_13_6 := by
  show some (luebeckConwayPolynomialOfCoeffs 13 [2, 11, 11, 10, 0, 0, 1]) = some luebeckConwayPolynomial_13_6
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 13 [2, 11, 11, 10, 0, 0, 1]) k =
        ([2, 11, 11, 10, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 13 m)).getD k
          (Zero.zero : ZMod64 13) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_13_6]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | 5 => rfl
  | 6 => rfl
  | _ + 7 => rfl

/-- Imported C(3, 8), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_3_8 : FpPoly 3 :=
  { coeffs := #[(2 : ZMod64 3), 2, 2, 0, 1, 2, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(3, 8). -/
@[simp, grind .] theorem luebeckConwayPolynomial_3_8_monic : DensePoly.Monic luebeckConwayPolynomial_3_8 := by rfl

/-- Positive degree of C(3, 8). -/
@[simp, grind .] theorem luebeckConwayPolynomial_3_8_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_3_8 := by decide

/-- Lookup identifies the imported C(3, 8). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_3_8 :
    luebeckConwayPolynomial? 3 8 = some luebeckConwayPolynomial_3_8 := by
  show some (luebeckConwayPolynomialOfCoeffs 3 [2, 2, 2, 0, 1, 2, 0, 0, 1]) = some luebeckConwayPolynomial_3_8
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 3 [2, 2, 2, 0, 1, 2, 0, 0, 1]) k =
        ([2, 2, 2, 0, 1, 2, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 3 m)).getD k
          (Zero.zero : ZMod64 3) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_3_8]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | 5 => rfl
  | 6 => rfl
  | 7 => rfl
  | 8 => rfl
  | _ + 9 => rfl

/-- Imported C(5, 7), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_5_7 : FpPoly 5 :=
  { coeffs := #[(3 : ZMod64 5), 3, 0, 0, 0, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(5, 7). -/
@[simp, grind .] theorem luebeckConwayPolynomial_5_7_monic : DensePoly.Monic luebeckConwayPolynomial_5_7 := by rfl

/-- Positive degree of C(5, 7). -/
@[simp, grind .] theorem luebeckConwayPolynomial_5_7_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_5_7 := by decide

/-- Lookup identifies the imported C(5, 7). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_5_7 :
    luebeckConwayPolynomial? 5 7 = some luebeckConwayPolynomial_5_7 := by
  show some (luebeckConwayPolynomialOfCoeffs 5 [3, 3, 0, 0, 0, 0, 0, 1]) = some luebeckConwayPolynomial_5_7
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 5 [3, 3, 0, 0, 0, 0, 0, 1]) k =
        ([3, 3, 0, 0, 0, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 5 m)).getD k
          (Zero.zero : ZMod64 5) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_5_7]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | 5 => rfl
  | 6 => rfl
  | 7 => rfl
  | _ + 8 => rfl

/-- Imported C(3, 7), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_3_7 : FpPoly 3 :=
  { coeffs := #[(1 : ZMod64 3), 0, 2, 0, 0, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(3, 7). -/
@[simp, grind .] theorem luebeckConwayPolynomial_3_7_monic : DensePoly.Monic luebeckConwayPolynomial_3_7 := by rfl

/-- Positive degree of C(3, 7). -/
@[simp, grind .] theorem luebeckConwayPolynomial_3_7_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_3_7 := by decide

/-- Lookup identifies the imported C(3, 7). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_3_7 :
    luebeckConwayPolynomial? 3 7 = some luebeckConwayPolynomial_3_7 := by
  show some (luebeckConwayPolynomialOfCoeffs 3 [1, 0, 2, 0, 0, 0, 0, 1]) = some luebeckConwayPolynomial_3_7
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 3 [1, 0, 2, 0, 0, 0, 0, 1]) k =
        ([1, 0, 2, 0, 0, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 3 m)).getD k
          (Zero.zero : ZMod64 3) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_3_7]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | 5 => rfl
  | 6 => rfl
  | 7 => rfl
  | _ + 8 => rfl

/-- Imported C(5, 5), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_5_5 : FpPoly 5 :=
  { coeffs := #[(3 : ZMod64 5), 4, 0, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(5, 5). -/
@[simp, grind .] theorem luebeckConwayPolynomial_5_5_monic : DensePoly.Monic luebeckConwayPolynomial_5_5 := by rfl

/-- Positive degree of C(5, 5). -/
@[simp, grind .] theorem luebeckConwayPolynomial_5_5_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_5_5 := by decide

/-- Lookup identifies the imported C(5, 5). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_5_5 :
    luebeckConwayPolynomial? 5 5 = some luebeckConwayPolynomial_5_5 := by
  show some (luebeckConwayPolynomialOfCoeffs 5 [3, 4, 0, 0, 0, 1]) = some luebeckConwayPolynomial_5_5
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 5 [3, 4, 0, 0, 0, 1]) k =
        ([3, 4, 0, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 5 m)).getD k
          (Zero.zero : ZMod64 5) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_5_5]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | 5 => rfl
  | _ + 6 => rfl

/-- Imported C(2, 7), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_2_7 : FpPoly 2 :=
  { coeffs := #[(1 : ZMod64 2), 1, 0, 0, 0, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(2, 7). -/
@[simp, grind .] theorem luebeckConwayPolynomial_2_7_monic : DensePoly.Monic luebeckConwayPolynomial_2_7 := by rfl

/-- Positive degree of C(2, 7). -/
@[simp, grind .] theorem luebeckConwayPolynomial_2_7_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_2_7 := by decide

/-- Lookup identifies the imported C(2, 7). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_2_7 :
    luebeckConwayPolynomial? 2 7 = some luebeckConwayPolynomial_2_7 := by
  show some (luebeckConwayPolynomialOfCoeffs 2 [1, 1, 0, 0, 0, 0, 0, 1]) = some luebeckConwayPolynomial_2_7
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 2 [1, 1, 0, 0, 0, 0, 0, 1]) k =
        ([1, 1, 0, 0, 0, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 2 m)).getD k
          (Zero.zero : ZMod64 2) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_2_7]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | 5 => rfl
  | 6 => rfl
  | 7 => rfl
  | _ + 8 => rfl

/-- Imported C(2, 4), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_2_4 : FpPoly 2 :=
  { coeffs := #[(1 : ZMod64 2), 1, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(2, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_2_4_monic : DensePoly.Monic luebeckConwayPolynomial_2_4 := by rfl

/-- Positive degree of C(2, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_2_4_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_2_4 := by decide

/-- Lookup identifies the imported C(2, 4). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_2_4 :
    luebeckConwayPolynomial? 2 4 = some luebeckConwayPolynomial_2_4 := by
  show some (luebeckConwayPolynomialOfCoeffs 2 [1, 1, 0, 0, 1]) = some luebeckConwayPolynomial_2_4
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 2 [1, 1, 0, 0, 1]) k =
        ([1, 1, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 2 m)).getD k
          (Zero.zero : ZMod64 2) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_2_4]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | _ + 5 => rfl

/-- Imported C(3, 4), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_3_4 : FpPoly 3 :=
  { coeffs := #[(2 : ZMod64 3), 0, 0, 2, 1]
    normalized := by right; decide }

/-- Monicity of C(3, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_3_4_monic : DensePoly.Monic luebeckConwayPolynomial_3_4 := by rfl

/-- Positive degree of C(3, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_3_4_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_3_4 := by decide

/-- Lookup identifies the imported C(3, 4). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_3_4 :
    luebeckConwayPolynomial? 3 4 = some luebeckConwayPolynomial_3_4 := by
  show some (luebeckConwayPolynomialOfCoeffs 3 [2, 0, 0, 2, 1]) = some luebeckConwayPolynomial_3_4
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 3 [2, 0, 0, 2, 1]) k =
        ([2, 0, 0, 2, 1].toArray.map (fun m => ZMod64.ofNat 3 m)).getD k
          (Zero.zero : ZMod64 3) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_3_4]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | _ + 5 => rfl

/-- Imported C(71, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_71_2 : FpPoly 71 :=
  { coeffs := #[(7 : ZMod64 71), 69, 1]
    normalized := by right; decide }

/-- Monicity of C(71, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_71_2_monic : DensePoly.Monic luebeckConwayPolynomial_71_2 := by rfl

/-- Positive degree of C(71, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_71_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_71_2 := by decide

/-- Lookup identifies the imported C(71, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_71_2 :
    luebeckConwayPolynomial? 71 2 = some luebeckConwayPolynomial_71_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 71 [7, 69, 1]) = some luebeckConwayPolynomial_71_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 71 [7, 69, 1]) k =
        ([7, 69, 1].toArray.map (fun m => ZMod64.ofNat 71 m)).getD k
          (Zero.zero : ZMod64 71) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_71_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(41, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_41_2 : FpPoly 41 :=
  { coeffs := #[(6 : ZMod64 41), 38, 1]
    normalized := by right; decide }

/-- Monicity of C(41, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_41_2_monic : DensePoly.Monic luebeckConwayPolynomial_41_2 := by rfl

/-- Positive degree of C(41, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_41_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_41_2 := by decide

/-- Lookup identifies the imported C(41, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_41_2 :
    luebeckConwayPolynomial? 41 2 = some luebeckConwayPolynomial_41_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 41 [6, 38, 1]) = some luebeckConwayPolynomial_41_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 41 [6, 38, 1]) k =
        ([6, 38, 1].toArray.map (fun m => ZMod64.ofNat 41 m)).getD k
          (Zero.zero : ZMod64 41) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_41_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(73, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_73_2 : FpPoly 73 :=
  { coeffs := #[(5 : ZMod64 73), 70, 1]
    normalized := by right; decide }

/-- Monicity of C(73, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_73_2_monic : DensePoly.Monic luebeckConwayPolynomial_73_2 := by rfl

/-- Positive degree of C(73, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_73_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_73_2 := by decide

/-- Lookup identifies the imported C(73, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_73_2 :
    luebeckConwayPolynomial? 73 2 = some luebeckConwayPolynomial_73_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 73 [5, 70, 1]) = some luebeckConwayPolynomial_73_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 73 [5, 70, 1]) k =
        ([5, 70, 1].toArray.map (fun m => ZMod64.ofNat 73 m)).getD k
          (Zero.zero : ZMod64 73) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_73_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(37, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_37_2 : FpPoly 37 :=
  { coeffs := #[(2 : ZMod64 37), 33, 1]
    normalized := by right; decide }

/-- Monicity of C(37, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_37_2_monic : DensePoly.Monic luebeckConwayPolynomial_37_2 := by rfl

/-- Positive degree of C(37, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_37_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_37_2 := by decide

/-- Lookup identifies the imported C(37, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_37_2 :
    luebeckConwayPolynomial? 37 2 = some luebeckConwayPolynomial_37_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 37 [2, 33, 1]) = some luebeckConwayPolynomial_37_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 37 [2, 33, 1]) k =
        ([2, 33, 1].toArray.map (fun m => ZMod64.ofNat 37 m)).getD k
          (Zero.zero : ZMod64 37) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_37_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(23, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_23_2 : FpPoly 23 :=
  { coeffs := #[(5 : ZMod64 23), 21, 1]
    normalized := by right; decide }

/-- Monicity of C(23, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_23_2_monic : DensePoly.Monic luebeckConwayPolynomial_23_2 := by rfl

/-- Positive degree of C(23, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_23_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_23_2 := by decide

/-- Lookup identifies the imported C(23, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_23_2 :
    luebeckConwayPolynomial? 23 2 = some luebeckConwayPolynomial_23_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 23 [5, 21, 1]) = some luebeckConwayPolynomial_23_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 23 [5, 21, 1]) k =
        ([5, 21, 1].toArray.map (fun m => ZMod64.ofNat 23 m)).getD k
          (Zero.zero : ZMod64 23) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_23_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(13, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_13_2 : FpPoly 13 :=
  { coeffs := #[(2 : ZMod64 13), 12, 1]
    normalized := by right; decide }

/-- Monicity of C(13, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_13_2_monic : DensePoly.Monic luebeckConwayPolynomial_13_2 := by rfl

/-- Positive degree of C(13, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_13_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_13_2 := by decide

/-- Lookup identifies the imported C(13, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_13_2 :
    luebeckConwayPolynomial? 13 2 = some luebeckConwayPolynomial_13_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 13 [2, 12, 1]) = some luebeckConwayPolynomial_13_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 13 [2, 12, 1]) k =
        ([2, 12, 1].toArray.map (fun m => ZMod64.ofNat 13 m)).getD k
          (Zero.zero : ZMod64 13) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_13_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(7, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_7_2 : FpPoly 7 :=
  { coeffs := #[(3 : ZMod64 7), 6, 1]
    normalized := by right; decide }

/-- Monicity of C(7, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_7_2_monic : DensePoly.Monic luebeckConwayPolynomial_7_2 := by rfl

/-- Positive degree of C(7, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_7_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_7_2 := by decide

/-- Lookup identifies the imported C(7, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_7_2 :
    luebeckConwayPolynomial? 7 2 = some luebeckConwayPolynomial_7_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 7 [3, 6, 1]) = some luebeckConwayPolynomial_7_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 7 [3, 6, 1]) k =
        ([3, 6, 1].toArray.map (fun m => ZMod64.ofNat 7 m)).getD k
          (Zero.zero : ZMod64 7) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_7_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(83, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_83_1 : FpPoly 83 :=
  { coeffs := #[(81 : ZMod64 83), 1]
    normalized := by right; decide }

/-- Monicity of C(83, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_83_1_monic : DensePoly.Monic luebeckConwayPolynomial_83_1 := by rfl

/-- Positive degree of C(83, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_83_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_83_1 := by decide

/-- Lookup identifies the imported C(83, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_83_1 :
    luebeckConwayPolynomial? 83 1 = some luebeckConwayPolynomial_83_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 83 [81, 1]) = some luebeckConwayPolynomial_83_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 83 [81, 1]) k =
        ([81, 1].toArray.map (fun m => ZMod64.ofNat 83 m)).getD k
          (Zero.zero : ZMod64 83) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_83_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(41, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_41_1 : FpPoly 41 :=
  { coeffs := #[(35 : ZMod64 41), 1]
    normalized := by right; decide }

/-- Monicity of C(41, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_41_1_monic : DensePoly.Monic luebeckConwayPolynomial_41_1 := by rfl

/-- Positive degree of C(41, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_41_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_41_1 := by decide

/-- Lookup identifies the imported C(41, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_41_1 :
    luebeckConwayPolynomial? 41 1 = some luebeckConwayPolynomial_41_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 41 [35, 1]) = some luebeckConwayPolynomial_41_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 41 [35, 1]) k =
        ([35, 1].toArray.map (fun m => ZMod64.ofNat 41 m)).getD k
          (Zero.zero : ZMod64 41) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_41_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(19, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_19_1 : FpPoly 19 :=
  { coeffs := #[(17 : ZMod64 19), 1]
    normalized := by right; decide }

/-- Monicity of C(19, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_19_1_monic : DensePoly.Monic luebeckConwayPolynomial_19_1 := by rfl

/-- Positive degree of C(19, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_19_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_19_1 := by decide

/-- Lookup identifies the imported C(19, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_19_1 :
    luebeckConwayPolynomial? 19 1 = some luebeckConwayPolynomial_19_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 19 [17, 1]) = some luebeckConwayPolynomial_19_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 19 [17, 1]) k =
        ([17, 1].toArray.map (fun m => ZMod64.ofNat 19 m)).getD k
          (Zero.zero : ZMod64 19) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_19_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(13, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_13_1 : FpPoly 13 :=
  { coeffs := #[(11 : ZMod64 13), 1]
    normalized := by right; decide }

/-- Monicity of C(13, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_13_1_monic : DensePoly.Monic luebeckConwayPolynomial_13_1 := by rfl

/-- Positive degree of C(13, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_13_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_13_1 := by decide

/-- Lookup identifies the imported C(13, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_13_1 :
    luebeckConwayPolynomial? 13 1 = some luebeckConwayPolynomial_13_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 13 [11, 1]) = some luebeckConwayPolynomial_13_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 13 [11, 1]) k =
        ([11, 1].toArray.map (fun m => ZMod64.ofNat 13 m)).getD k
          (Zero.zero : ZMod64 13) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_13_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(3, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_3_1 : FpPoly 3 :=
  { coeffs := #[(1 : ZMod64 3), 1]
    normalized := by right; decide }

/-- Monicity of C(3, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_3_1_monic : DensePoly.Monic luebeckConwayPolynomial_3_1 := by rfl

/-- Positive degree of C(3, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_3_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_3_1 := by decide

/-- Lookup identifies the imported C(3, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_3_1 :
    luebeckConwayPolynomial? 3 1 = some luebeckConwayPolynomial_3_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 3 [1, 1]) = some luebeckConwayPolynomial_3_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 3 [1, 1]) k =
        ([1, 1].toArray.map (fun m => ZMod64.ofNat 3 m)).getD k
          (Zero.zero : ZMod64 3) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_3_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(2, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_2_1 : FpPoly 2 :=
  { coeffs := #[(1 : ZMod64 2), 1]
    normalized := by right; decide }

/-- Monicity of C(2, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_2_1_monic : DensePoly.Monic luebeckConwayPolynomial_2_1 := by rfl

/-- Positive degree of C(2, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_2_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_2_1 := by decide

/-- Lookup identifies the imported C(2, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_2_1 :
    luebeckConwayPolynomial? 2 1 = some luebeckConwayPolynomial_2_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 2 [1, 1]) = some luebeckConwayPolynomial_2_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 2 [1, 1]) k =
        ([1, 1].toArray.map (fun m => ZMod64.ofNat 2 m)).getD k
          (Zero.zero : ZMod64 2) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_2_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl


end Conway

end Hex
