/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Coefficients
public import HexConway.Entries.S3_3

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Imported C(821, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_821_2 : FpPoly 821 :=
  { coeffs := #[(2 : ZMod64 821), 816, 1]
    normalized := by right; decide }

/-- Monicity of C(821, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_821_2_monic : DensePoly.Monic luebeckConwayPolynomial_821_2 := by rfl

/-- Positive degree of C(821, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_821_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_821_2 := by decide

/-- Lookup identifies the imported C(821, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_821_2 :
    luebeckConwayPolynomial? 821 2 = some luebeckConwayPolynomial_821_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 821 [2, 816, 1]) = some luebeckConwayPolynomial_821_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 821 [2, 816, 1]) k =
        ([2, 816, 1].toArray.map (fun m => ZMod64.ofNat 821 m)).getD k
          (Zero.zero : ZMod64 821) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_821_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(853, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_853_2 : FpPoly 853 :=
  { coeffs := #[(2 : ZMod64 853), 852, 1]
    normalized := by right; decide }

/-- Monicity of C(853, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_853_2_monic : DensePoly.Monic luebeckConwayPolynomial_853_2 := by rfl

/-- Positive degree of C(853, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_853_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_853_2 := by decide

/-- Lookup identifies the imported C(853, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_853_2 :
    luebeckConwayPolynomial? 853 2 = some luebeckConwayPolynomial_853_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 853 [2, 852, 1]) = some luebeckConwayPolynomial_853_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 853 [2, 852, 1]) k =
        ([2, 852, 1].toArray.map (fun m => ZMod64.ofNat 853 m)).getD k
          (Zero.zero : ZMod64 853) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_853_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(919, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_919_2 : FpPoly 919 :=
  { coeffs := #[(7 : ZMod64 919), 910, 1]
    normalized := by right; decide }

/-- Monicity of C(919, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_919_2_monic : DensePoly.Monic luebeckConwayPolynomial_919_2 := by rfl

/-- Positive degree of C(919, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_919_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_919_2 := by decide

/-- Lookup identifies the imported C(919, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_919_2 :
    luebeckConwayPolynomial? 919 2 = some luebeckConwayPolynomial_919_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 919 [7, 910, 1]) = some luebeckConwayPolynomial_919_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 919 [7, 910, 1]) k =
        ([7, 910, 1].toArray.map (fun m => ZMod64.ofNat 919 m)).getD k
          (Zero.zero : ZMod64 919) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_919_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(947, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_947_2 : FpPoly 947 :=
  { coeffs := #[(2 : ZMod64 947), 943, 1]
    normalized := by right; decide }

/-- Monicity of C(947, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_947_2_monic : DensePoly.Monic luebeckConwayPolynomial_947_2 := by rfl

/-- Positive degree of C(947, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_947_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_947_2 := by decide

/-- Lookup identifies the imported C(947, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_947_2 :
    luebeckConwayPolynomial? 947 2 = some luebeckConwayPolynomial_947_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 947 [2, 943, 1]) = some luebeckConwayPolynomial_947_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 947 [2, 943, 1]) k =
        ([2, 943, 1].toArray.map (fun m => ZMod64.ofNat 947 m)).getD k
          (Zero.zero : ZMod64 947) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_947_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(281, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_281_2 : FpPoly 281 :=
  { coeffs := #[(3 : ZMod64 281), 280, 1]
    normalized := by right; decide }

/-- Monicity of C(281, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_281_2_monic : DensePoly.Monic luebeckConwayPolynomial_281_2 := by rfl

/-- Positive degree of C(281, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_281_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_281_2 := by decide

/-- Lookup identifies the imported C(281, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_281_2 :
    luebeckConwayPolynomial? 281 2 = some luebeckConwayPolynomial_281_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 281 [3, 280, 1]) = some luebeckConwayPolynomial_281_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 281 [3, 280, 1]) k =
        ([3, 280, 1].toArray.map (fun m => ZMod64.ofNat 281 m)).getD k
          (Zero.zero : ZMod64 281) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_281_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(311, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_311_2 : FpPoly 311 :=
  { coeffs := #[(17 : ZMod64 311), 310, 1]
    normalized := by right; decide }

/-- Monicity of C(311, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_311_2_monic : DensePoly.Monic luebeckConwayPolynomial_311_2 := by rfl

/-- Positive degree of C(311, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_311_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_311_2 := by decide

/-- Lookup identifies the imported C(311, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_311_2 :
    luebeckConwayPolynomial? 311 2 = some luebeckConwayPolynomial_311_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 311 [17, 310, 1]) = some luebeckConwayPolynomial_311_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 311 [17, 310, 1]) k =
        ([17, 310, 1].toArray.map (fun m => ZMod64.ofNat 311 m)).getD k
          (Zero.zero : ZMod64 311) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_311_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(379, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_379_2 : FpPoly 379 :=
  { coeffs := #[(2 : ZMod64 379), 374, 1]
    normalized := by right; decide }

/-- Monicity of C(379, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_379_2_monic : DensePoly.Monic luebeckConwayPolynomial_379_2 := by rfl

/-- Positive degree of C(379, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_379_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_379_2 := by decide

/-- Lookup identifies the imported C(379, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_379_2 :
    luebeckConwayPolynomial? 379 2 = some luebeckConwayPolynomial_379_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 379 [2, 374, 1]) = some luebeckConwayPolynomial_379_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 379 [2, 374, 1]) k =
        ([2, 374, 1].toArray.map (fun m => ZMod64.ofNat 379 m)).getD k
          (Zero.zero : ZMod64 379) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_379_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(439, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_439_2 : FpPoly 439 :=
  { coeffs := #[(15 : ZMod64 439), 436, 1]
    normalized := by right; decide }

/-- Monicity of C(439, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_439_2_monic : DensePoly.Monic luebeckConwayPolynomial_439_2 := by rfl

/-- Positive degree of C(439, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_439_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_439_2 := by decide

/-- Lookup identifies the imported C(439, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_439_2 :
    luebeckConwayPolynomial? 439 2 = some luebeckConwayPolynomial_439_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 439 [15, 436, 1]) = some luebeckConwayPolynomial_439_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 439 [15, 436, 1]) k =
        ([15, 436, 1].toArray.map (fun m => ZMod64.ofNat 439 m)).getD k
          (Zero.zero : ZMod64 439) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_439_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(509, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_509_2 : FpPoly 509 :=
  { coeffs := #[(2 : ZMod64 509), 508, 1]
    normalized := by right; decide }

/-- Monicity of C(509, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_509_2_monic : DensePoly.Monic luebeckConwayPolynomial_509_2 := by rfl

/-- Positive degree of C(509, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_509_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_509_2 := by decide

/-- Lookup identifies the imported C(509, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_509_2 :
    luebeckConwayPolynomial? 509 2 = some luebeckConwayPolynomial_509_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 509 [2, 508, 1]) = some luebeckConwayPolynomial_509_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 509 [2, 508, 1]) k =
        ([2, 508, 1].toArray.map (fun m => ZMod64.ofNat 509 m)).getD k
          (Zero.zero : ZMod64 509) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_509_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(239, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_239_2 : FpPoly 239 :=
  { coeffs := #[(7 : ZMod64 239), 237, 1]
    normalized := by right; decide }

/-- Monicity of C(239, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_239_2_monic : DensePoly.Monic luebeckConwayPolynomial_239_2 := by rfl

/-- Positive degree of C(239, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_239_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_239_2 := by decide

/-- Lookup identifies the imported C(239, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_239_2 :
    luebeckConwayPolynomial? 239 2 = some luebeckConwayPolynomial_239_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 239 [7, 237, 1]) = some luebeckConwayPolynomial_239_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 239 [7, 237, 1]) k =
        ([7, 237, 1].toArray.map (fun m => ZMod64.ofNat 239 m)).getD k
          (Zero.zero : ZMod64 239) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_239_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(563, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_563_2 : FpPoly 563 :=
  { coeffs := #[(2 : ZMod64 563), 559, 1]
    normalized := by right; decide }

/-- Monicity of C(563, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_563_2_monic : DensePoly.Monic luebeckConwayPolynomial_563_2 := by rfl

/-- Positive degree of C(563, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_563_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_563_2 := by decide

/-- Lookup identifies the imported C(563, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_563_2 :
    luebeckConwayPolynomial? 563 2 = some luebeckConwayPolynomial_563_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 563 [2, 559, 1]) = some luebeckConwayPolynomial_563_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 563 [2, 559, 1]) k =
        ([2, 559, 1].toArray.map (fun m => ZMod64.ofNat 563 m)).getD k
          (Zero.zero : ZMod64 563) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_563_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(613, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_613_2 : FpPoly 613 :=
  { coeffs := #[(2 : ZMod64 613), 609, 1]
    normalized := by right; decide }

/-- Monicity of C(613, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_613_2_monic : DensePoly.Monic luebeckConwayPolynomial_613_2 := by rfl

/-- Positive degree of C(613, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_613_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_613_2 := by decide

/-- Lookup identifies the imported C(613, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_613_2 :
    luebeckConwayPolynomial? 613 2 = some luebeckConwayPolynomial_613_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 613 [2, 609, 1]) = some luebeckConwayPolynomial_613_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 613 [2, 609, 1]) k =
        ([2, 609, 1].toArray.map (fun m => ZMod64.ofNat 613 m)).getD k
          (Zero.zero : ZMod64 613) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_613_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(673, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_673_2 : FpPoly 673 :=
  { coeffs := #[(5 : ZMod64 673), 672, 1]
    normalized := by right; decide }

/-- Monicity of C(673, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_673_2_monic : DensePoly.Monic luebeckConwayPolynomial_673_2 := by rfl

/-- Positive degree of C(673, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_673_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_673_2 := by decide

/-- Lookup identifies the imported C(673, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_673_2 :
    luebeckConwayPolynomial? 673 2 = some luebeckConwayPolynomial_673_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 673 [5, 672, 1]) = some luebeckConwayPolynomial_673_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 673 [5, 672, 1]) k =
        ([5, 672, 1].toArray.map (fun m => ZMod64.ofNat 673 m)).getD k
          (Zero.zero : ZMod64 673) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_673_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(751, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_751_2 : FpPoly 751 :=
  { coeffs := #[(3 : ZMod64 751), 749, 1]
    normalized := by right; decide }

/-- Monicity of C(751, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_751_2_monic : DensePoly.Monic luebeckConwayPolynomial_751_2 := by rfl

/-- Positive degree of C(751, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_751_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_751_2 := by decide

/-- Lookup identifies the imported C(751, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_751_2 :
    luebeckConwayPolynomial? 751 2 = some luebeckConwayPolynomial_751_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 751 [3, 749, 1]) = some luebeckConwayPolynomial_751_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 751 [3, 749, 1]) k =
        ([3, 749, 1].toArray.map (fun m => ZMod64.ofNat 751 m)).getD k
          (Zero.zero : ZMod64 751) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_751_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(809, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_809_2 : FpPoly 809 :=
  { coeffs := #[(3 : ZMod64 809), 799, 1]
    normalized := by right; decide }

/-- Monicity of C(809, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_809_2_monic : DensePoly.Monic luebeckConwayPolynomial_809_2 := by rfl

/-- Positive degree of C(809, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_809_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_809_2 := by decide

/-- Lookup identifies the imported C(809, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_809_2 :
    luebeckConwayPolynomial? 809 2 = some luebeckConwayPolynomial_809_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 809 [3, 799, 1]) = some luebeckConwayPolynomial_809_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 809 [3, 799, 1]) k =
        ([3, 799, 1].toArray.map (fun m => ZMod64.ofNat 809 m)).getD k
          (Zero.zero : ZMod64 809) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_809_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(907, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_907_2 : FpPoly 907 :=
  { coeffs := #[(2 : ZMod64 907), 903, 1]
    normalized := by right; decide }

/-- Monicity of C(907, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_907_2_monic : DensePoly.Monic luebeckConwayPolynomial_907_2 := by rfl

/-- Positive degree of C(907, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_907_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_907_2 := by decide

/-- Lookup identifies the imported C(907, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_907_2 :
    luebeckConwayPolynomial? 907 2 = some luebeckConwayPolynomial_907_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 907 [2, 903, 1]) = some luebeckConwayPolynomial_907_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 907 [2, 903, 1]) k =
        ([2, 903, 1].toArray.map (fun m => ZMod64.ofNat 907 m)).getD k
          (Zero.zero : ZMod64 907) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_907_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(997, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_997_2 : FpPoly 997 :=
  { coeffs := #[(7 : ZMod64 997), 995, 1]
    normalized := by right; decide }

/-- Monicity of C(997, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_997_2_monic : DensePoly.Monic luebeckConwayPolynomial_997_2 := by rfl

/-- Positive degree of C(997, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_997_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_997_2 := by decide

/-- Lookup identifies the imported C(997, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_997_2 :
    luebeckConwayPolynomial? 997 2 = some luebeckConwayPolynomial_997_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 997 [7, 995, 1]) = some luebeckConwayPolynomial_997_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 997 [7, 995, 1]) k =
        ([7, 995, 1].toArray.map (fun m => ZMod64.ofNat 997 m)).getD k
          (Zero.zero : ZMod64 997) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_997_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(277, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_277_2 : FpPoly 277 :=
  { coeffs := #[(5 : ZMod64 277), 274, 1]
    normalized := by right; decide }

/-- Monicity of C(277, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_277_2_monic : DensePoly.Monic luebeckConwayPolynomial_277_2 := by rfl

/-- Positive degree of C(277, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_277_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_277_2 := by decide

/-- Lookup identifies the imported C(277, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_277_2 :
    luebeckConwayPolynomial? 277 2 = some luebeckConwayPolynomial_277_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 277 [5, 274, 1]) = some luebeckConwayPolynomial_277_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 277 [5, 274, 1]) k =
        ([5, 274, 1].toArray.map (fun m => ZMod64.ofNat 277 m)).getD k
          (Zero.zero : ZMod64 277) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_277_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(317, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_317_2 : FpPoly 317 :=
  { coeffs := #[(2 : ZMod64 317), 313, 1]
    normalized := by right; decide }

/-- Monicity of C(317, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_317_2_monic : DensePoly.Monic luebeckConwayPolynomial_317_2 := by rfl

/-- Positive degree of C(317, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_317_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_317_2 := by decide

/-- Lookup identifies the imported C(317, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_317_2 :
    luebeckConwayPolynomial? 317 2 = some luebeckConwayPolynomial_317_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 317 [2, 313, 1]) = some luebeckConwayPolynomial_317_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 317 [2, 313, 1]) k =
        ([2, 313, 1].toArray.map (fun m => ZMod64.ofNat 317 m)).getD k
          (Zero.zero : ZMod64 317) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_317_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(359, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_359_2 : FpPoly 359 :=
  { coeffs := #[(7 : ZMod64 359), 358, 1]
    normalized := by right; decide }

/-- Monicity of C(359, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_359_2_monic : DensePoly.Monic luebeckConwayPolynomial_359_2 := by rfl

/-- Positive degree of C(359, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_359_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_359_2 := by decide

/-- Lookup identifies the imported C(359, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_359_2 :
    luebeckConwayPolynomial? 359 2 = some luebeckConwayPolynomial_359_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 359 [7, 358, 1]) = some luebeckConwayPolynomial_359_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 359 [7, 358, 1]) k =
        ([7, 358, 1].toArray.map (fun m => ZMod64.ofNat 359 m)).getD k
          (Zero.zero : ZMod64 359) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_359_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(431, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_431_2 : FpPoly 431 :=
  { coeffs := #[(7 : ZMod64 431), 430, 1]
    normalized := by right; decide }

/-- Monicity of C(431, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_431_2_monic : DensePoly.Monic luebeckConwayPolynomial_431_2 := by rfl

/-- Positive degree of C(431, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_431_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_431_2 := by decide

/-- Lookup identifies the imported C(431, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_431_2 :
    luebeckConwayPolynomial? 431 2 = some luebeckConwayPolynomial_431_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 431 [7, 430, 1]) = some luebeckConwayPolynomial_431_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 431 [7, 430, 1]) k =
        ([7, 430, 1].toArray.map (fun m => ZMod64.ofNat 431 m)).getD k
          (Zero.zero : ZMod64 431) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_431_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(467, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_467_2 : FpPoly 467 :=
  { coeffs := #[(2 : ZMod64 467), 463, 1]
    normalized := by right; decide }

/-- Monicity of C(467, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_467_2_monic : DensePoly.Monic luebeckConwayPolynomial_467_2 := by rfl

/-- Positive degree of C(467, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_467_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_467_2 := by decide

/-- Lookup identifies the imported C(467, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_467_2 :
    luebeckConwayPolynomial? 467 2 = some luebeckConwayPolynomial_467_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 467 [2, 463, 1]) = some luebeckConwayPolynomial_467_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 467 [2, 463, 1]) k =
        ([2, 463, 1].toArray.map (fun m => ZMod64.ofNat 467 m)).getD k
          (Zero.zero : ZMod64 467) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_467_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(17, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_17_3 : FpPoly 17 :=
  { coeffs := #[(14 : ZMod64 17), 1, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(17, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_17_3_monic : DensePoly.Monic luebeckConwayPolynomial_17_3 := by rfl

/-- Positive degree of C(17, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_17_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_17_3 := by decide

/-- Lookup identifies the imported C(17, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_17_3 :
    luebeckConwayPolynomial? 17 3 = some luebeckConwayPolynomial_17_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 17 [14, 1, 0, 1]) = some luebeckConwayPolynomial_17_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 17 [14, 1, 0, 1]) k =
        ([14, 1, 0, 1].toArray.map (fun m => ZMod64.ofNat 17 m)).getD k
          (Zero.zero : ZMod64 17) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_17_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(3, 4), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_3_4 : FpPoly 3 :=
  { coeffs := #[(2 : ZMod64 3), 0, 0, 2, 1]
    normalized := by right; decide }

/-- Monicity of C(3, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_3_4_monic : DensePoly.Monic luebeckConwayPolynomial_3_4 := by rfl

/-- Positive degree of C(3, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_3_4_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_3_4 := by decide

/-- Lookup identifies the imported C(3, 4). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_3_4 :
    luebeckConwayPolynomial? 3 4 = some luebeckConwayPolynomial_3_4 := by
  show some (luebeckConwayPolynomialOfCoeffs 3 [2, 0, 0, 2, 1]) = some luebeckConwayPolynomial_3_4
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 3 [2, 0, 0, 2, 1]) k =
        ([2, 0, 0, 2, 1].toArray.map (fun m => ZMod64.ofNat 3 m)).getD k
          (Zero.zero : ZMod64 3) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_3_4]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | _ + 5 => rfl


end Conway

end Hex
