/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

import HexGraphIso.Cases

/-!
The extended graph-isomorphism conformance campaign, streamed to the
external nauty oracle rather than committed: all 32,768 labelled graphs
at `n = 6`, larger deterministic pseudo-random cases from the SplitMix64
corpus seeds, and the deterministic hard families. The cases are
generated by `HexGraphIso.Cases`. Run locally or on the scheduled
profile as

```
lake exe hexgraphiso_emit_campaign | python3 scripts/oracle/graphiso_nauty.py
```

Records carry the public `canonicalize` answer (label and canonical
upper-triangle bits) with the node count from the transcribed search,
as in `HexGraphIso.EmitFixtures`, so the campaign pins the public
operations against real nauty. Only failures are retained as replay
records (the oracle reports the failing case identifier).

`--engine` emits the same cases with the label, canonical bits and node
count read off `Cases.engine` instead, so the oracle pins that search
against real nauty on its own.
-/

def main (args : List String) : IO Unit := do
  let runner ← Hex.GraphIsoCases.runnerOfArgs args
  Hex.GraphIsoCases.eachCampaign (Hex.GraphIsoCases.emit runner)
