/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexPrimality.Cert
public import HexConway.FactorProofs.S0_3

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_751 : Hex.Nat.Prime 751 := by
  exact Hex.Nat.prime_of_bounded 751 27 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_761 : Hex.Nat.Prime 761 := by
  exact Hex.Nat.prime_of_bounded 761 27 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_773 : Hex.Nat.Prime 773 := by
  exact Hex.Nat.prime_of_bounded 773 27 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_787 : Hex.Nat.Prime 787 := by
  exact Hex.Nat.prime_of_bounded 787 28 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_809 : Hex.Nat.Prime 809 := by
  exact Hex.Nat.prime_of_bounded 809 28 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_811 : Hex.Nat.Prime 811 := by
  exact Hex.Nat.prime_of_bounded 811 28 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_823 : Hex.Nat.Prime 823 := by
  exact Hex.Nat.prime_of_bounded 823 28 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_827 : Hex.Nat.Prime 827 := by
  exact Hex.Nat.prime_of_bounded 827 28 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_839 : Hex.Nat.Prime 839 := by
  exact Hex.Nat.prime_of_bounded 839 28 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_857 : Hex.Nat.Prime 857 := by
  exact Hex.Nat.prime_of_bounded 857 29 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_877 : Hex.Nat.Prime 877 := by
  exact Hex.Nat.prime_of_bounded 877 29 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_883 : Hex.Nat.Prime 883 := by
  exact Hex.Nat.prime_of_bounded 883 29 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_911 : Hex.Nat.Prime 911 := by
  exact Hex.Nat.prime_of_bounded 911 30 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_919 : Hex.Nat.Prime 919 := by
  exact Hex.Nat.prime_of_bounded 919 30 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_941 : Hex.Nat.Prime 941 := by
  exact Hex.Nat.prime_of_bounded 941 30 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_991 : Hex.Nat.Prime 991 := by
  exact Hex.Nat.prime_of_bounded 991 31 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1061 : Hex.Nat.Prime 1061 := by
  exact Hex.Nat.prime_of_bounded 1061 32 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1063 : Hex.Nat.Prime 1063 := by
  exact Hex.Nat.prime_of_bounded 1063 32 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1087 : Hex.Nat.Prime 1087 := by
  exact Hex.Nat.prime_of_bounded 1087 32 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1093 : Hex.Nat.Prime 1093 := by
  exact Hex.Nat.prime_of_bounded 1093 33 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1201 : Hex.Nat.Prime 1201 := by
  exact Hex.Nat.prime_of_bounded 1201 34 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1277 : Hex.Nat.Prime 1277 := by
  exact Hex.Nat.prime_of_bounded 1277 35 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1289 : Hex.Nat.Prime 1289 := by
  exact Hex.Nat.prime_of_bounded 1289 35 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1321 : Hex.Nat.Prime 1321 := by
  exact Hex.Nat.prime_of_bounded 1321 36 (by decide) (by decide) (by decide)


end Conway

end Hex
