/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexPrimality.Cert
public import HexConway.FactorProofs.S0_5

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_2801 : Hex.Nat.Prime 2801 := by
  exact Hex.Nat.prime_of_bounded 2801 52 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_3019 : Hex.Nat.Prime 3019 := by
  exact Hex.Nat.prime_of_bounded 3019 54 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_3037 : Hex.Nat.Prime 3037 := by
  exact Hex.Nat.prime_of_bounded 3037 55 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_3121 : Hex.Nat.Prime 3121 := by
  exact Hex.Nat.prime_of_bounded 3121 55 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_3169 : Hex.Nat.Prime 3169 := by
  exact Hex.Nat.prime_of_bounded 3169 56 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_3221 : Hex.Nat.Prime 3221 := by
  exact Hex.Nat.prime_of_bounded 3221 56 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_3463 : Hex.Nat.Prime 3463 := by
  exact Hex.Nat.prime_of_bounded 3463 58 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_3541 : Hex.Nat.Prime 3541 := by
  exact Hex.Nat.prime_of_bounded 3541 59 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_3571 : Hex.Nat.Prime 3571 := by
  exact Hex.Nat.prime_of_bounded 3571 59 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_3769 : Hex.Nat.Prime 3769 := by
  exact Hex.Nat.prime_of_bounded 3769 61 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_3881 : Hex.Nat.Prime 3881 := by
  exact Hex.Nat.prime_of_bounded 3881 62 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_3931 : Hex.Nat.Prime 3931 := by
  exact Hex.Nat.prime_of_bounded 3931 62 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_4051 : Hex.Nat.Prime 4051 := by
  exact Hex.Nat.prime_of_bounded 4051 63 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_4177 : Hex.Nat.Prime 4177 := by
  exact Hex.Nat.prime_of_bounded 4177 64 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_4603 : Hex.Nat.Prime 4603 := by
  exact Hex.Nat.prime_of_bounded 4603 67 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_4657 : Hex.Nat.Prime 4657 := by
  exact Hex.Nat.prime_of_bounded 4657 68 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_4733 : Hex.Nat.Prime 4733 := by
  exact Hex.Nat.prime_of_bounded 4733 68 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_4957 : Hex.Nat.Prime 4957 := by
  exact Hex.Nat.prime_of_bounded 4957 70 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_4973 : Hex.Nat.Prime 4973 := by
  exact Hex.Nat.prime_of_bounded 4973 70 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_5023 : Hex.Nat.Prime 5023 := by
  exact Hex.Nat.prime_of_bounded 5023 70 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_5101 : Hex.Nat.Prime 5101 := by
  exact Hex.Nat.prime_of_bounded 5101 71 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_5107 : Hex.Nat.Prime 5107 := by
  exact Hex.Nat.prime_of_bounded 5107 71 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_5113 : Hex.Nat.Prime 5113 := by
  exact Hex.Nat.prime_of_bounded 5113 71 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_5153 : Hex.Nat.Prime 5153 := by
  exact Hex.Nat.prime_of_bounded 5153 71 (by decide) (by decide) (by decide)


end Conway

end Hex
