/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexBerlekamp.RabinSoundness
public import HexGFqRing.PolynomialQuotient
public import HexArith.Nat.Prime

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Primality of characteristic 2. -/
theorem prime_two : Hex.Nat.Prime 2 :=
  Hex.Nat.prime_of_bounded 2 1 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 2. -/
instance instPrimeModulus2 : ZMod64.PrimeModulus 2 := ZMod64.primeModulusOfPrime prime_two

/-- Word bounds for characteristic 3. -/
instance bounds3 : ZMod64.Bounds 3 := ⟨by decide, by decide⟩
/-- Primality of characteristic 3. -/
theorem prime_three : Hex.Nat.Prime 3 :=
  Hex.Nat.prime_of_bounded 3 1 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 3. -/
instance instPrimeModulus3 : ZMod64.PrimeModulus 3 := ZMod64.primeModulusOfPrime prime_three

/-- Word bounds for characteristic 5. -/
instance bounds5 : ZMod64.Bounds 5 := ⟨by decide, by decide⟩
/-- Primality of characteristic 5. -/
theorem prime_five : Hex.Nat.Prime 5 :=
  Hex.Nat.prime_of_bounded 5 2 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 5. -/
instance instPrimeModulus5 : ZMod64.PrimeModulus 5 := ZMod64.primeModulusOfPrime prime_five

/-- Word bounds for characteristic 7. -/
instance bounds7 : ZMod64.Bounds 7 := ⟨by decide, by decide⟩
/-- Primality of characteristic 7. -/
theorem prime_seven : Hex.Nat.Prime 7 :=
  Hex.Nat.prime_of_bounded 7 2 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 7. -/
instance instPrimeModulus7 : ZMod64.PrimeModulus 7 := ZMod64.primeModulusOfPrime prime_seven

/-- Word bounds for characteristic 11. -/
instance bounds11 : ZMod64.Bounds 11 := ⟨by decide, by decide⟩
/-- Primality of characteristic 11. -/
theorem prime_eleven : Hex.Nat.Prime 11 :=
  Hex.Nat.prime_of_bounded 11 3 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 11. -/
instance instPrimeModulus11 : ZMod64.PrimeModulus 11 := ZMod64.primeModulusOfPrime prime_eleven

/-- Word bounds for characteristic 13. -/
instance bounds13 : ZMod64.Bounds 13 := ⟨by decide, by decide⟩
/-- Primality of characteristic 13. -/
theorem prime_thirteen : Hex.Nat.Prime 13 :=
  Hex.Nat.prime_of_bounded 13 3 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 13. -/
instance instPrimeModulus13 : ZMod64.PrimeModulus 13 := ZMod64.primeModulusOfPrime prime_thirteen

/-- Word bounds for characteristic 17. -/
instance bounds17 : ZMod64.Bounds 17 := ⟨by decide, by decide⟩
/-- Primality of characteristic 17. -/
theorem prime_17 : Hex.Nat.Prime 17 :=
  Hex.Nat.prime_of_bounded 17 4 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 17. -/
instance instPrimeModulus17 : ZMod64.PrimeModulus 17 := ZMod64.primeModulusOfPrime prime_17

/-- Word bounds for characteristic 19. -/
instance bounds19 : ZMod64.Bounds 19 := ⟨by decide, by decide⟩
/-- Primality of characteristic 19. -/
theorem prime_19 : Hex.Nat.Prime 19 :=
  Hex.Nat.prime_of_bounded 19 4 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 19. -/
instance instPrimeModulus19 : ZMod64.PrimeModulus 19 := ZMod64.primeModulusOfPrime prime_19

/-- Word bounds for characteristic 23. -/
instance bounds23 : ZMod64.Bounds 23 := ⟨by decide, by decide⟩
/-- Primality of characteristic 23. -/
theorem prime_23 : Hex.Nat.Prime 23 :=
  Hex.Nat.prime_of_bounded 23 4 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 23. -/
instance instPrimeModulus23 : ZMod64.PrimeModulus 23 := ZMod64.primeModulusOfPrime prime_23

/-- Word bounds for characteristic 29. -/
instance bounds29 : ZMod64.Bounds 29 := ⟨by decide, by decide⟩
/-- Primality of characteristic 29. -/
theorem prime_29 : Hex.Nat.Prime 29 :=
  Hex.Nat.prime_of_bounded 29 5 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 29. -/
instance instPrimeModulus29 : ZMod64.PrimeModulus 29 := ZMod64.primeModulusOfPrime prime_29

/-- Word bounds for characteristic 31. -/
instance bounds31 : ZMod64.Bounds 31 := ⟨by decide, by decide⟩
/-- Primality of characteristic 31. -/
theorem prime_31 : Hex.Nat.Prime 31 :=
  Hex.Nat.prime_of_bounded 31 5 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 31. -/
instance instPrimeModulus31 : ZMod64.PrimeModulus 31 := ZMod64.primeModulusOfPrime prime_31

/-- Word bounds for characteristic 37. -/
instance bounds37 : ZMod64.Bounds 37 := ⟨by decide, by decide⟩
/-- Primality of characteristic 37. -/
theorem prime_37 : Hex.Nat.Prime 37 :=
  Hex.Nat.prime_of_bounded 37 6 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 37. -/
instance instPrimeModulus37 : ZMod64.PrimeModulus 37 := ZMod64.primeModulusOfPrime prime_37

/-- Word bounds for characteristic 41. -/
instance bounds41 : ZMod64.Bounds 41 := ⟨by decide, by decide⟩
/-- Primality of characteristic 41. -/
theorem prime_41 : Hex.Nat.Prime 41 :=
  Hex.Nat.prime_of_bounded 41 6 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 41. -/
instance instPrimeModulus41 : ZMod64.PrimeModulus 41 := ZMod64.primeModulusOfPrime prime_41

/-- Word bounds for characteristic 43. -/
instance bounds43 : ZMod64.Bounds 43 := ⟨by decide, by decide⟩
/-- Primality of characteristic 43. -/
theorem prime_43 : Hex.Nat.Prime 43 :=
  Hex.Nat.prime_of_bounded 43 6 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 43. -/
instance instPrimeModulus43 : ZMod64.PrimeModulus 43 := ZMod64.primeModulusOfPrime prime_43

/-- Word bounds for characteristic 47. -/
instance bounds47 : ZMod64.Bounds 47 := ⟨by decide, by decide⟩
/-- Primality of characteristic 47. -/
theorem prime_47 : Hex.Nat.Prime 47 :=
  Hex.Nat.prime_of_bounded 47 6 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 47. -/
instance instPrimeModulus47 : ZMod64.PrimeModulus 47 := ZMod64.primeModulusOfPrime prime_47

/-- Word bounds for characteristic 53. -/
instance bounds53 : ZMod64.Bounds 53 := ⟨by decide, by decide⟩
/-- Primality of characteristic 53. -/
theorem prime_53 : Hex.Nat.Prime 53 :=
  Hex.Nat.prime_of_bounded 53 7 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 53. -/
instance instPrimeModulus53 : ZMod64.PrimeModulus 53 := ZMod64.primeModulusOfPrime prime_53

/-- Word bounds for characteristic 59. -/
instance bounds59 : ZMod64.Bounds 59 := ⟨by decide, by decide⟩
/-- Primality of characteristic 59. -/
theorem prime_59 : Hex.Nat.Prime 59 :=
  Hex.Nat.prime_of_bounded 59 7 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 59. -/
instance instPrimeModulus59 : ZMod64.PrimeModulus 59 := ZMod64.primeModulusOfPrime prime_59

/-- Word bounds for characteristic 61. -/
instance bounds61 : ZMod64.Bounds 61 := ⟨by decide, by decide⟩
/-- Primality of characteristic 61. -/
theorem prime_61 : Hex.Nat.Prime 61 :=
  Hex.Nat.prime_of_bounded 61 7 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 61. -/
instance instPrimeModulus61 : ZMod64.PrimeModulus 61 := ZMod64.primeModulusOfPrime prime_61

/-- Word bounds for characteristic 67. -/
instance bounds67 : ZMod64.Bounds 67 := ⟨by decide, by decide⟩
/-- Primality of characteristic 67. -/
theorem prime_67 : Hex.Nat.Prime 67 :=
  Hex.Nat.prime_of_bounded 67 8 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 67. -/
instance instPrimeModulus67 : ZMod64.PrimeModulus 67 := ZMod64.primeModulusOfPrime prime_67

/-- Word bounds for characteristic 71. -/
instance bounds71 : ZMod64.Bounds 71 := ⟨by decide, by decide⟩
/-- Primality of characteristic 71. -/
theorem prime_71 : Hex.Nat.Prime 71 :=
  Hex.Nat.prime_of_bounded 71 8 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 71. -/
instance instPrimeModulus71 : ZMod64.PrimeModulus 71 := ZMod64.primeModulusOfPrime prime_71

/-- Word bounds for characteristic 73. -/
instance bounds73 : ZMod64.Bounds 73 := ⟨by decide, by decide⟩
/-- Primality of characteristic 73. -/
theorem prime_73 : Hex.Nat.Prime 73 :=
  Hex.Nat.prime_of_bounded 73 8 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 73. -/
instance instPrimeModulus73 : ZMod64.PrimeModulus 73 := ZMod64.primeModulusOfPrime prime_73

/-- Word bounds for characteristic 79. -/
instance bounds79 : ZMod64.Bounds 79 := ⟨by decide, by decide⟩
/-- Primality of characteristic 79. -/
theorem prime_79 : Hex.Nat.Prime 79 :=
  Hex.Nat.prime_of_bounded 79 8 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 79. -/
instance instPrimeModulus79 : ZMod64.PrimeModulus 79 := ZMod64.primeModulusOfPrime prime_79

/-- Word bounds for characteristic 83. -/
instance bounds83 : ZMod64.Bounds 83 := ⟨by decide, by decide⟩
/-- Primality of characteristic 83. -/
theorem prime_83 : Hex.Nat.Prime 83 :=
  Hex.Nat.prime_of_bounded 83 9 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 83. -/
instance instPrimeModulus83 : ZMod64.PrimeModulus 83 := ZMod64.primeModulusOfPrime prime_83

/-- Word bounds for characteristic 89. -/
instance bounds89 : ZMod64.Bounds 89 := ⟨by decide, by decide⟩
/-- Primality of characteristic 89. -/
theorem prime_89 : Hex.Nat.Prime 89 :=
  Hex.Nat.prime_of_bounded 89 9 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 89. -/
instance instPrimeModulus89 : ZMod64.PrimeModulus 89 := ZMod64.primeModulusOfPrime prime_89

/-- Word bounds for characteristic 97. -/
instance bounds97 : ZMod64.Bounds 97 := ⟨by decide, by decide⟩
/-- Primality of characteristic 97. -/
theorem prime_97 : Hex.Nat.Prime 97 :=
  Hex.Nat.prime_of_bounded 97 9 (by decide) (by decide) (by decide)
/-- Prime modulus for characteristic 97. -/
instance instPrimeModulus97 : ZMod64.PrimeModulus 97 := ZMod64.primeModulusOfPrime prime_97

/-- Imported coefficients in ascending degree order. -/
@[expose] def luebeckConwayCoeffs? : Nat → Nat → Option (List Nat)
  | 2, n => match n with
    | 1 => some [1, 1]
    | 2 => some [1, 1, 1]
    | 3 => some [1, 1, 0, 1]
    | 4 => some [1, 1, 0, 0, 1]
    | 5 => some [1, 0, 1, 0, 0, 1]
    | 6 => some [1, 1, 0, 1, 1, 0, 1]
    | 7 => some [1, 1, 0, 0, 0, 0, 0, 1]
    | 8 => some [1, 0, 1, 1, 1, 0, 0, 0, 1]
    | 9 => some [1, 0, 0, 0, 1, 0, 0, 0, 0, 1]
    | 10 => some [1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1]
    | 11 => some [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1]
    | 12 => some [1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1]
    | 13 => some [1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1]
    | 14 => some [1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1]
    | 15 => some [1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
    | 16 => some [1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
    | _ => none
  | 3, n => match n with
    | 1 => some [1, 1]
    | 2 => some [2, 2, 1]
    | 3 => some [1, 2, 0, 1]
    | 4 => some [2, 0, 0, 2, 1]
    | 5 => some [1, 2, 0, 0, 0, 1]
    | 6 => some [2, 2, 1, 0, 2, 0, 1]
    | 7 => some [1, 0, 2, 0, 0, 0, 0, 1]
    | 8 => some [2, 2, 2, 0, 1, 2, 0, 0, 1]
    | _ => none
  | 5, n => match n with
    | 1 => some [3, 1]
    | 2 => some [2, 4, 1]
    | 3 => some [3, 3, 0, 1]
    | 4 => some [2, 4, 4, 0, 1]
    | 5 => some [3, 4, 0, 0, 0, 1]
    | 6 => some [2, 0, 1, 4, 1, 0, 1]
    | 7 => some [3, 3, 0, 0, 0, 0, 0, 1]
    | 8 => some [2, 4, 3, 0, 1, 0, 0, 0, 1]
    | _ => none
  | 7, n => match n with
    | 1 => some [4, 1]
    | 2 => some [3, 6, 1]
    | 3 => some [4, 0, 6, 1]
    | 4 => some [3, 4, 5, 0, 1]
    | 5 => some [4, 1, 0, 0, 0, 1]
    | 6 => some [3, 6, 4, 5, 1, 0, 1]
    | 7 => some [4, 6, 0, 0, 0, 0, 0, 1]
    | 8 => some [3, 2, 6, 4, 0, 0, 0, 0, 1]
    | _ => none
  | 11, n => match n with
    | 1 => some [9, 1]
    | 2 => some [2, 7, 1]
    | 3 => some [9, 2, 0, 1]
    | 4 => some [2, 10, 8, 0, 1]
    | 5 => some [9, 0, 10, 0, 0, 1]
    | 6 => some [2, 7, 6, 4, 3, 0, 1]
    | _ => none
  | 13, n => match n with
    | 1 => some [11, 1]
    | 2 => some [2, 12, 1]
    | 3 => some [11, 2, 0, 1]
    | 4 => some [2, 12, 3, 0, 1]
    | 5 => some [11, 4, 0, 0, 0, 1]
    | 6 => some [2, 11, 11, 10, 0, 0, 1]
    | _ => none
  | 17, n => match n with
    | 1 => some [14, 1]
    | 2 => some [3, 16, 1]
    | _ => none
  | 19, n => match n with
    | 1 => some [17, 1]
    | 2 => some [2, 18, 1]
    | _ => none
  | 23, n => match n with
    | 1 => some [18, 1]
    | 2 => some [5, 21, 1]
    | _ => none
  | 29, n => match n with
    | 1 => some [27, 1]
    | 2 => some [2, 24, 1]
    | _ => none
  | 31, n => match n with
    | 1 => some [28, 1]
    | 2 => some [3, 29, 1]
    | _ => none
  | 37, n => match n with
    | 1 => some [35, 1]
    | 2 => some [2, 33, 1]
    | _ => none
  | 41, n => match n with
    | 1 => some [35, 1]
    | 2 => some [6, 38, 1]
    | _ => none
  | 43, n => match n with
    | 1 => some [40, 1]
    | 2 => some [3, 42, 1]
    | _ => none
  | 47, n => match n with
    | 1 => some [42, 1]
    | 2 => some [5, 45, 1]
    | _ => none
  | 53, n => match n with
    | 1 => some [51, 1]
    | 2 => some [2, 49, 1]
    | _ => none
  | 59, n => match n with
    | 1 => some [57, 1]
    | 2 => some [2, 58, 1]
    | _ => none
  | 61, n => match n with
    | 1 => some [59, 1]
    | 2 => some [2, 60, 1]
    | _ => none
  | 67, n => match n with
    | 1 => some [65, 1]
    | 2 => some [2, 63, 1]
    | _ => none
  | 71, n => match n with
    | 1 => some [64, 1]
    | 2 => some [7, 69, 1]
    | _ => none
  | 73, n => match n with
    | 1 => some [68, 1]
    | 2 => some [5, 70, 1]
    | _ => none
  | 79, n => match n with
    | 1 => some [76, 1]
    | 2 => some [3, 78, 1]
    | _ => none
  | 83, n => match n with
    | 1 => some [81, 1]
    | 2 => some [2, 82, 1]
    | _ => none
  | 89, n => match n with
    | 1 => some [86, 1]
    | 2 => some [3, 82, 1]
    | _ => none
  | 97, n => match n with
    | 1 => some [92, 1]
    | 2 => some [5, 96, 1]
    | _ => none
  | _, _ => none

/-- Construct a polynomial from ascending coefficient representatives. -/
@[expose] def luebeckConwayPolynomialOfCoeffs
    (p : Nat) [ZMod64.Bounds p] (coeffs : List Nat) : FpPoly p :=
  FpPoly.ofCoeffs (coeffs.toArray.map (fun n => ZMod64.ofNat p n))

/-- Lookup an imported, verified polynomial. -/
@[expose] def luebeckConwayPolynomial? (p n : Nat) [ZMod64.Bounds p] : Option (FpPoly p) :=
  (luebeckConwayCoeffs? p n).map (luebeckConwayPolynomialOfCoeffs p)

/-- Exact verified keys, in characteristic and degree order. -/
@[expose] def supportedPairs : List (Nat × Nat) :=
  [(2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10), (2, 11), (2, 12), (2, 13), (2, 14), (2, 15), (2, 16), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7), (7, 8), (11, 1), (11, 2), (11, 3), (11, 4), (11, 5), (11, 6), (13, 1), (13, 2), (13, 3), (13, 4), (13, 5), (13, 6), (17, 1), (17, 2), (19, 1), (19, 2), (23, 1), (23, 2), (29, 1), (29, 2), (31, 1), (31, 2), (37, 1), (37, 2), (41, 1), (41, 2), (43, 1), (43, 2), (47, 1), (47, 2), (53, 1), (53, 2), (59, 1), (59, 2), (61, 1), (61, 2), (67, 1), (67, 2), (71, 1), (71, 2), (73, 1), (73, 2), (79, 1), (79, 2), (83, 1), (83, 2), (89, 1), (89, 2), (97, 1), (97, 2)]


end Conway

end Hex
