/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

import HexSignDet.Codec.Json

/-! Constructor data generated from `conformance-fixtures/HexRCF/selected-catalog.json`.
The kernel checks the exact selected root and source binding. -/

open Hex.SignDet
namespace Hex.RCF.SelectedRootTests.CatalogData
def j0 : Codec.Json := .array .nil
def j1 : Codec.Json := .number (0)
def j2 : Codec.Json := .array (.cons (j1) .nil)
def j3 : Codec.Json := .number (-2)
def j4 : Codec.Json := .number (1)
def j5 : Codec.Json := .array (.cons (j1) (.cons (j3) (.cons (j4) .nil)))
def j6 : Codec.Json := .array (.cons (j1) (.cons (j1) (.cons (j4) .nil)))
def j7 : Codec.Json := .array (.cons (j1) (.cons (j4) (.cons (j4) .nil)))
def j8 : Codec.Json := .array (.cons (j5) (.cons (j6) (.cons (j7) .nil)))
def j9 : Codec.Json := .array (.cons (j4) (.cons (j7) .nil))
def j10 : Codec.Json := .number (2)
def j11 : Codec.Json := .array (.cons (j1) (.cons (j10) (.cons (j4) .nil)))
def j12 : Codec.Json := .array (.cons (j4) (.cons (j11) .nil))
def j13 : Codec.Json := .array (.cons (j0) .nil)
def j14 : Codec.Json := .array (.cons (j4) .nil)
def j15 : Codec.Json := .array (.cons (j14) .nil)
def j16 : Codec.Json := .array (.cons (j13) (.cons (j13) (.cons (j14) (.cons (j14) (.cons (j15) (.cons (j4) .nil))))))
def j17 : Codec.Json := .array (.cons (j7) .nil)
def j18 : Codec.Json := .array (.cons (j6) (.cons (j7) .nil))
def j19 : Codec.Json := .array (.cons (j8) (.cons (j18) (.cons (j17) .nil)))
def j20 : Codec.Json := .array (.cons (j10) (.cons (j4) (.cons (j1) .nil)))
def j21 : Codec.Json := .array (.cons (j7) (.cons (j0) (.cons (j11) .nil)))
def j22 : Codec.Json := .array (.cons (j7) (.cons (j18) (.cons (j11) .nil)))
def j23 : Codec.Json := .array (.cons (j22) .nil)
def j24 : Codec.Json := .array (.cons (j7) (.cons (j18) .nil))
def j25 : Codec.Json := .array (.cons (j24) .nil)
def j26 : Codec.Json := .array (.cons (j19) (.cons (j20) (.cons (j21) (.cons (j23) (.cons (j25) .nil)))))
def j27 : Codec.Json := .number (-1)
def j28 : Codec.Json := .array (.cons (j27) (.cons (j4) (.cons (j4) .nil)))
def j29 : Codec.Json := .array (.cons (j4) (.cons (j4) (.cons (j4) .nil)))
def j30 : Codec.Json := .array (.cons (j2) (.cons (j8) (.cons (j17) (.cons (j9) (.cons (j12) (.cons (j26) (.cons (j26) (.cons (j28) (.cons (j29) (.cons (j4) (.cons (j1) (.cons (j4) .nil))))))))))))
def j31 : Codec.Json := .array (.cons (j30) .nil)
def j32 : Codec.Json := .array (.cons (j0) (.cons (j17) .nil))
def j33 : Codec.Json := .array (.cons (j32) .nil)
def j34 : Codec.Json := .array (.cons (j33) .nil)
def j35 : Codec.Json := .array (.cons (j4) (.cons (j2) (.cons (j2) (.cons (j4) (.cons (j15) .nil)))))
def j36 : Codec.Json := .array (.cons (j2) (.cons (j8) (.cons (j9) (.cons (j12) (.cons (j0) (.cons (j4) (.cons (j16) (.cons (j31) (.cons (j34) (.cons (j13) (.cons (j35) .nil)))))))))))
def j37 : Codec.Json := .array (.cons (j36) (.cons (j0) .nil))
def j38 : Codec.Json := .array (.cons (j37) .nil)
def j39 : Codec.Json := .array (.cons (j4) (.cons (j1) (.cons (j38) .nil)))
def j40 : Codec.Json := .array (.cons (j2) (.cons (j8) (.cons (j9) (.cons (j12) (.cons (j0) (.cons (j0) (.cons (j39) .nil)))))))
def j41 : Codec.Json := .array (.cons (j40) .nil)
def j42 : Codec.Json := .array (.cons (j0) (.cons (j1) (.cons (j41) .nil)))
def j43 : Codec.Json := .array (.cons (j1) (.cons (j27) (.cons (j4) .nil)))
def j44 : Codec.Json := .array (.cons (j6) (.cons (j43) .nil))
def j45 : Codec.Json := .array (.cons (j44) (.cons (j27) .nil))
def j46 : Codec.Json := .array (.cons (j17) (.cons (j4) .nil))
def j47 : Codec.Json := .array (.cons (j45) (.cons (j0) (.cons (j46) .nil)))
def j48 : Codec.Json := .array (.cons (j4) (.cons (j46) .nil))
def j49 : Codec.Json := .array (.cons (j11) .nil)
def j50 : Codec.Json := .array (.cons (j49) (.cons (j4) .nil))
def j51 : Codec.Json := .array (.cons (j4) (.cons (j50) .nil))
def j52 : Codec.Json := .array (.cons (j46) .nil)
def j53 : Codec.Json := .array (.cons (j0) (.cons (j46) .nil))
def j54 : Codec.Json := .array (.cons (j47) (.cons (j53) (.cons (j52) .nil)))
def j55 : Codec.Json := .array (.cons (j46) (.cons (j0) (.cons (j50) .nil)))
def j56 : Codec.Json := .array (.cons (j18) (.cons (j4) .nil))
def j57 : Codec.Json := .array (.cons (j46) (.cons (j53) (.cons (j56) .nil)))
def j58 : Codec.Json := .array (.cons (j57) .nil)
def j59 : Codec.Json := .array (.cons (j46) (.cons (j53) .nil))
def j60 : Codec.Json := .array (.cons (j59) .nil)
def j61 : Codec.Json := .array (.cons (j54) (.cons (j20) (.cons (j55) (.cons (j58) (.cons (j60) .nil)))))
def j62 : Codec.Json := .array (.cons (j2) (.cons (j47) (.cons (j52) (.cons (j48) (.cons (j51) (.cons (j61) (.cons (j61) (.cons (j28) (.cons (j29) (.cons (j4) (.cons (j1) (.cons (j4) .nil))))))))))))
def j63 : Codec.Json := .array (.cons (j62) .nil)
def j64 : Codec.Json := .array (.cons (j0) (.cons (j52) .nil))
def j65 : Codec.Json := .array (.cons (j64) .nil)
def j66 : Codec.Json := .array (.cons (j65) .nil)
def j67 : Codec.Json := .array (.cons (j2) (.cons (j47) (.cons (j48) (.cons (j51) (.cons (j0) (.cons (j4) (.cons (j16) (.cons (j63) (.cons (j66) (.cons (j13) (.cons (j35) .nil)))))))))))
def j68 : Codec.Json := .array (.cons (j67) (.cons (j0) .nil))
def j69 : Codec.Json := .array (.cons (j68) .nil)
def j70 : Codec.Json := .array (.cons (j4) (.cons (j1) (.cons (j69) .nil)))
def j71 : Codec.Json := .array (.cons (j2) (.cons (j47) (.cons (j48) (.cons (j51) (.cons (j0) (.cons (j0) (.cons (j70) .nil)))))))
def j72 : Codec.Json := .array (.cons (j4) (.cons (j71) .nil))
def j73 : Codec.Json := .array (.cons (j42) (.cons (j72) .nil))
def packet : Codec.Json := j73
end Hex.RCF.SelectedRootTests.CatalogData
