/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexSignDet.Codec.Json

@[expose] public section

/-! Shared constructor literals generated from
`conformance-fixtures/HexRCF/selected-root.json` by
`scripts/rcf/selected_literals.py`. No certificate producer is invoked. -/

open Hex.SignDet

namespace Hex.RCF.SelectedRootTests.Intermediates
def j0 : Codec.Json := .array (.cons (.number (0)) (.cons (.number (1)) (.cons (.number (1)) .nil)))
def j1 : Codec.Json := .array (.cons (.number (0)) (.cons (.number (-1)) (.cons (.number (1)) .nil)))
def j2 : Codec.Json := .array (.cons (j0) (.cons (j1) .nil))
def j3 : Codec.Json := .array .nil
def j4 : Codec.Json := .array (.cons (j3) (.cons (.number (0)) (.cons (j3) .nil)))
def j5 : Codec.Json := .array (.cons (.number (0)) (.cons (.number (-2)) (.cons (.number (1)) .nil)))
def j6 : Codec.Json := .array (.cons (.number (0)) (.cons (.number (0)) (.cons (.number (1)) .nil)))
def j7 : Codec.Json := .array (.cons (j5) (.cons (j6) (.cons (j0) .nil)))
def j8 : Codec.Json := .array (.cons (.number (1)) (.cons (j0) .nil))
def j9 : Codec.Json := .array (.cons (.number (0)) (.cons (.number (2)) (.cons (.number (1)) .nil)))
def j10 : Codec.Json := .array (.cons (.number (1)) (.cons (j9) .nil))
def j11 : Codec.Json := .array (.cons (j2) .nil)
def j12 : Codec.Json := .array (.cons (.number (0)) .nil)
def j13 : Codec.Json := .array (.cons (.number (1)) .nil)
def j14 : Codec.Json := .array (.cons (.number (2)) .nil)
def j15 : Codec.Json := .array (.cons (j12) (.cons (j13) (.cons (j14) .nil)))
def j16 : Codec.Json := .array (.cons (.number (-1)) .nil)
def j17 : Codec.Json := .array (.cons (j16) (.cons (j12) (.cons (j13) .nil)))
def j18 : Codec.Json := .array (.cons (.number (1)) (.cons (.number (0)) (.cons (.number (0)) .nil)))
def j19 : Codec.Json := .array (.cons (.number (1)) (.cons (.number (-1)) (.cons (.number (1)) .nil)))
def j20 : Codec.Json := .array (.cons (.number (2)) (.cons (.number (0)) (.cons (.number (-2)) .nil)))
def j21 : Codec.Json := .array (.cons (j1) (.cons (j20) (.cons (j0) .nil)))
def j22 : Codec.Json := .array (.cons (j15) (.cons (j17) (.cons (j18) (.cons (j19) (.cons (j21) (.cons (.number (2)) .nil))))))
def j23 : Codec.Json := .array (.cons (j0) .nil)
def j24 : Codec.Json := .array (.cons (j6) (.cons (j0) .nil))
def j25 : Codec.Json := .array (.cons (j7) (.cons (j24) (.cons (j23) .nil)))
def j26 : Codec.Json := .array (.cons (.number (2)) (.cons (.number (1)) (.cons (.number (0)) .nil)))
def j27 : Codec.Json := .array (.cons (j0) (.cons (j3) (.cons (j9) .nil)))
def j28 : Codec.Json := .array (.cons (j0) (.cons (j24) (.cons (j9) .nil)))
def j29 : Codec.Json := .array (.cons (j28) .nil)
def j30 : Codec.Json := .array (.cons (j0) (.cons (j24) .nil))
def j31 : Codec.Json := .array (.cons (j30) .nil)
def j32 : Codec.Json := .array (.cons (j25) (.cons (j26) (.cons (j27) (.cons (j29) (.cons (j31) .nil)))))
def j33 : Codec.Json := .array (.cons (.number (-1)) (.cons (.number (1)) (.cons (.number (1)) .nil)))
def j34 : Codec.Json := .array (.cons (.number (1)) (.cons (.number (1)) (.cons (.number (1)) .nil)))
def j35 : Codec.Json := .array (.cons (j4) (.cons (j7) (.cons (j23) (.cons (j8) (.cons (j10) (.cons (j32) (.cons (j32) (.cons (j33) (.cons (j34) (.cons (.number (1)) (.cons (.number (0)) (.cons (.number (1)) .nil))))))))))))
def j36 : Codec.Json := .array (.cons (j5) (.cons (j0) .nil))
def j37 : Codec.Json := .array (.cons (j1) .nil)
def j38 : Codec.Json := .array (.cons (j7) (.cons (j36) (.cons (j37) .nil)))
def j39 : Codec.Json := .array (.cons (j5) .nil)
def j40 : Codec.Json := .array (.cons (j0) (.cons (j39) (.cons (j9) .nil)))
def j41 : Codec.Json := .array (.cons (j9) (.cons (j0) .nil))
def j42 : Codec.Json := .array (.cons (j0) (.cons (j41) (.cons (j9) .nil)))
def j43 : Codec.Json := .array (.cons (j42) .nil)
def j44 : Codec.Json := .array (.cons (j9) (.cons (j1) .nil))
def j45 : Codec.Json := .array (.cons (j0) (.cons (j44) .nil))
def j46 : Codec.Json := .array (.cons (j45) .nil)
def j47 : Codec.Json := .array (.cons (j38) (.cons (j26) (.cons (j40) (.cons (j43) (.cons (j46) .nil)))))
def j48 : Codec.Json := .array (.cons (.number (-1)) (.cons (.number (-1)) (.cons (.number (-1)) .nil)))
def j49 : Codec.Json := .array (.cons (.number (1)) (.cons (.number (0)) (.cons (.number (-1)) .nil)))
def j50 : Codec.Json := .array (.cons (j4) (.cons (j7) (.cons (j2) (.cons (j8) (.cons (j10) (.cons (j32) (.cons (j47) (.cons (j48) (.cons (j49) (.cons (.number (0)) (.cons (.number (1)) (.cons (.number (-1)) .nil))))))))))))
def j51 : Codec.Json := .array (.cons (.number (0)) (.cons (.number (3)) (.cons (.number (2)) .nil)))
def j52 : Codec.Json := .array (.cons (j51) (.cons (j1) .nil))
def j53 : Codec.Json := .array (.cons (.number (0)) (.cons (.number (-4)) (.cons (.number (3)) .nil)))
def j54 : Codec.Json := .array (.cons (j53) (.cons (j0) .nil))
def j55 : Codec.Json := .array (.cons (j7) (.cons (j54) (.cons (j23) .nil)))
def j56 : Codec.Json := .array (.cons (.number (0)) (.cons (.number (3)) (.cons (.number (1)) .nil)))
def j57 : Codec.Json := .array (.cons (j0) (.cons (j39) (.cons (j56) .nil)))
def j58 : Codec.Json := .array (.cons (.number (0)) (.cons (.number (4)) (.cons (.number (3)) .nil)))
def j59 : Codec.Json := .array (.cons (j58) (.cons (j0) .nil))
def j60 : Codec.Json := .array (.cons (.number (0)) (.cons (.number (2)) (.cons (.number (9)) .nil)))
def j61 : Codec.Json := .array (.cons (j0) (.cons (j59) (.cons (j60) .nil)))
def j62 : Codec.Json := .array (.cons (j61) .nil)
def j63 : Codec.Json := .array (.cons (j0) (.cons (j54) .nil))
def j64 : Codec.Json := .array (.cons (j63) .nil)
def j65 : Codec.Json := .array (.cons (j55) (.cons (j26) (.cons (j57) (.cons (j62) (.cons (j64) .nil)))))
def j66 : Codec.Json := .array (.cons (.number (-1)) (.cons (.number (-1)) (.cons (.number (1)) .nil)))
def j67 : Codec.Json := .array (.cons (j4) (.cons (j7) (.cons (j52) (.cons (j8) (.cons (j10) (.cons (j32) (.cons (j65) (.cons (j66) (.cons (j34) (.cons (.number (1)) (.cons (.number (0)) (.cons (.number (1)) .nil))))))))))))
def j68 : Codec.Json := .array (.cons (j35) (.cons (j50) (.cons (j67) .nil)))
def j69 : Codec.Json := .array (.cons (j3) (.cons (j23) .nil))
def j70 : Codec.Json := .array (.cons (j69) .nil)
def j71 : Codec.Json := .array (.cons (j0) (.cons (j3) (.cons (j0) .nil)))
def j72 : Codec.Json := .array (.cons (.number (0)) (.cons (j2) (.cons (j71) .nil)))
def j73 : Codec.Json := .array (.cons (j72) .nil)
def j74 : Codec.Json := .array (.cons (j73) (.cons (j2) .nil))
def j75 : Codec.Json := .array (.cons (j74) .nil)
def j76 : Codec.Json := .array (.cons (j0) (.cons (j23) (.cons (j9) .nil)))
def j77 : Codec.Json := .array (.cons (.number (0)) (.cons (j52) (.cons (j76) .nil)))
def j78 : Codec.Json := .array (.cons (j72) (.cons (j77) .nil))
def j79 : Codec.Json := .array (.cons (j78) (.cons (j52) .nil))
def j80 : Codec.Json := .array (.cons (j79) .nil)
def j81 : Codec.Json := .array (.cons (j70) (.cons (j75) (.cons (j80) .nil)))
def j82 : Codec.Json := .array (.cons (j73) .nil)
def j83 : Codec.Json := .array (.cons (j13) .nil)
def j84 : Codec.Json := .array (.cons (.number (1)) (.cons (j12) (.cons (j12) (.cons (.number (1)) (.cons (j83) .nil)))))
def j85 : Codec.Json := .array (.cons (j4) (.cons (j7) (.cons (j8) (.cons (j10) (.cons (j11) (.cons (.number (3)) (.cons (j22) (.cons (j68) (.cons (j81) (.cons (j82) (.cons (j84) .nil)))))))))))
def j86 : Codec.Json := .array (.cons (j85) (.cons (j3) .nil))
def j87 : Codec.Json := .array (.cons (j86) .nil)
def j88 : Codec.Json := .array (.cons (.number (1)) (.cons (.number (0)) (.cons (j87) .nil)))
def packet0 : Codec.Json × Int × Codec.Json := (j2, (-1), j88)
def j89 : Codec.Json := .array (.cons (.number (0)) (.cons (.number (4)) (.cons (.number (1)) .nil)))
def j90 : Codec.Json := .array (.cons (j89) (.cons (j1) .nil))
def j91 : Codec.Json := .array (.cons (j90) .nil)
def j92 : Codec.Json := .array (.cons (j15) (.cons (j17) (.cons (j6) (.cons (j34) (.cons (j21) (.cons (.number (2)) .nil))))))
def j93 : Codec.Json := .array (.cons (.number (0)) (.cons (.number (-1)) (.cons (.number (2)) .nil)))
def j94 : Codec.Json := .array (.cons (j93) (.cons (j0) .nil))
def j95 : Codec.Json := .array (.cons (j7) (.cons (j94) (.cons (j23) .nil)))
def j96 : Codec.Json := .array (.cons (.number (0)) (.cons (.number (8)) (.cons (.number (1)) .nil)))
def j97 : Codec.Json := .array (.cons (j0) (.cons (j39) (.cons (j96) .nil)))
def j98 : Codec.Json := .array (.cons (.number (0)) (.cons (.number (1)) (.cons (.number (2)) .nil)))
def j99 : Codec.Json := .array (.cons (j98) (.cons (j0) .nil))
def j100 : Codec.Json := .array (.cons (.number (0)) (.cons (.number (7)) (.cons (.number (4)) .nil)))
def j101 : Codec.Json := .array (.cons (j0) (.cons (j99) (.cons (j100) .nil)))
def j102 : Codec.Json := .array (.cons (j101) .nil)
def j103 : Codec.Json := .array (.cons (j0) (.cons (j94) .nil))
def j104 : Codec.Json := .array (.cons (j103) .nil)
def j105 : Codec.Json := .array (.cons (j95) (.cons (j26) (.cons (j97) (.cons (j102) (.cons (j104) .nil)))))
def j106 : Codec.Json := .array (.cons (j4) (.cons (j7) (.cons (j90) (.cons (j8) (.cons (j10) (.cons (j32) (.cons (j105) (.cons (j33) (.cons (j34) (.cons (.number (1)) (.cons (.number (0)) (.cons (.number (1)) .nil))))))))))))
def j107 : Codec.Json := .array (.cons (.number (0)) (.cons (.number (9)) (.cons (.number (4)) .nil)))
def j108 : Codec.Json := .array (.cons (j107) (.cons (j1) .nil))
def j109 : Codec.Json := .array (.cons (.number (0)) (.cons (.number (-8)) (.cons (.number (9)) .nil)))
def j110 : Codec.Json := .array (.cons (j109) (.cons (j0) .nil))
def j111 : Codec.Json := .array (.cons (j7) (.cons (j110) (.cons (j23) .nil)))
def j112 : Codec.Json := .array (.cons (.number (0)) (.cons (.number (9)) (.cons (.number (2)) .nil)))
def j113 : Codec.Json := .array (.cons (j0) (.cons (j39) (.cons (j112) .nil)))
def j114 : Codec.Json := .array (.cons (.number (0)) (.cons (.number (8)) (.cons (.number (9)) .nil)))
def j115 : Codec.Json := .array (.cons (j114) (.cons (j0) .nil))
def j116 : Codec.Json := .array (.cons (.number (0)) (.cons (.number (98)) (.cons (.number (81)) .nil)))
def j117 : Codec.Json := .array (.cons (j0) (.cons (j115) (.cons (j116) .nil)))
def j118 : Codec.Json := .array (.cons (j117) .nil)
def j119 : Codec.Json := .array (.cons (j0) (.cons (j110) .nil))
def j120 : Codec.Json := .array (.cons (j119) .nil)
def j121 : Codec.Json := .array (.cons (j111) (.cons (j26) (.cons (j113) (.cons (j118) (.cons (j120) .nil)))))
def j122 : Codec.Json := .array (.cons (j4) (.cons (j7) (.cons (j108) (.cons (j8) (.cons (j10) (.cons (j32) (.cons (j121) (.cons (j33) (.cons (j34) (.cons (.number (1)) (.cons (.number (0)) (.cons (.number (1)) .nil))))))))))))
def j123 : Codec.Json := .array (.cons (j35) (.cons (j106) (.cons (j122) .nil)))
def j124 : Codec.Json := .array (.cons (.number (0)) (.cons (j90) (.cons (j71) .nil)))
def j125 : Codec.Json := .array (.cons (j124) .nil)
def j126 : Codec.Json := .array (.cons (j125) (.cons (j90) .nil))
def j127 : Codec.Json := .array (.cons (j126) .nil)
def j128 : Codec.Json := .array (.cons (j0) (.cons (j23) (.cons (j96) .nil)))
def j129 : Codec.Json := .array (.cons (.number (0)) (.cons (j108) (.cons (j128) .nil)))
def j130 : Codec.Json := .array (.cons (j124) (.cons (j129) .nil))
def j131 : Codec.Json := .array (.cons (j130) (.cons (j108) .nil))
def j132 : Codec.Json := .array (.cons (j131) .nil)
def j133 : Codec.Json := .array (.cons (j70) (.cons (j127) (.cons (j132) .nil)))
def j134 : Codec.Json := .array (.cons (j125) .nil)
def j135 : Codec.Json := .array (.cons (j4) (.cons (j7) (.cons (j8) (.cons (j10) (.cons (j91) (.cons (.number (3)) (.cons (j92) (.cons (j123) (.cons (j133) (.cons (j134) (.cons (j84) .nil)))))))))))
def j136 : Codec.Json := .array (.cons (j135) (.cons (j3) .nil))
def j137 : Codec.Json := .array (.cons (j136) .nil)
def j138 : Codec.Json := .array (.cons (.number (1)) (.cons (.number (0)) (.cons (j137) .nil)))
def packet1 : Codec.Json × Int × Codec.Json := (j90, (1), j138)
end Hex.RCF.SelectedRootTests.Intermediates
