/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Certificates
public import HexConway.Transport.S0_0

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

theorem ofCoeffs_13_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 13 [11, 2, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_13_3
  change luebeckConwayPolynomialOfCoeffs 13 [11, 2, 0, 1] = luebeckConwayPolynomial_13_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_13_3_irreducible

theorem ofCoeffs_13_5_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 13 [11, 4, 0, 0, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_13_5
  change luebeckConwayPolynomialOfCoeffs 13 [11, 4, 0, 0, 0, 1] = luebeckConwayPolynomial_13_5 at heq
  rw [heq]
  exact luebeckConwayPolynomial_13_5_irreducible

theorem ofCoeffs_17_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 17 [14, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_17_1
  change luebeckConwayPolynomialOfCoeffs 17 [14, 1] = luebeckConwayPolynomial_17_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_17_1_irreducible

theorem ofCoeffs_19_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 19 [17, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_19_1
  change luebeckConwayPolynomialOfCoeffs 19 [17, 1] = luebeckConwayPolynomial_19_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_19_1_irreducible

theorem ofCoeffs_23_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 23 [18, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_23_1
  change luebeckConwayPolynomialOfCoeffs 23 [18, 1] = luebeckConwayPolynomial_23_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_23_1_irreducible

theorem ofCoeffs_29_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 29 [27, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_29_1
  change luebeckConwayPolynomialOfCoeffs 29 [27, 1] = luebeckConwayPolynomial_29_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_29_1_irreducible

theorem ofCoeffs_31_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 31 [28, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_31_1
  change luebeckConwayPolynomialOfCoeffs 31 [28, 1] = luebeckConwayPolynomial_31_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_31_1_irreducible

theorem ofCoeffs_37_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 37 [35, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_37_1
  change luebeckConwayPolynomialOfCoeffs 37 [35, 1] = luebeckConwayPolynomial_37_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_37_1_irreducible

theorem ofCoeffs_41_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 41 [35, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_41_1
  change luebeckConwayPolynomialOfCoeffs 41 [35, 1] = luebeckConwayPolynomial_41_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_41_1_irreducible

theorem ofCoeffs_43_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 43 [40, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_43_1
  change luebeckConwayPolynomialOfCoeffs 43 [40, 1] = luebeckConwayPolynomial_43_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_43_1_irreducible

theorem ofCoeffs_47_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 47 [42, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_47_1
  change luebeckConwayPolynomialOfCoeffs 47 [42, 1] = luebeckConwayPolynomial_47_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_47_1_irreducible

theorem ofCoeffs_53_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 53 [51, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_53_1
  change luebeckConwayPolynomialOfCoeffs 53 [51, 1] = luebeckConwayPolynomial_53_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_53_1_irreducible

theorem ofCoeffs_59_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 59 [57, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_59_1
  change luebeckConwayPolynomialOfCoeffs 59 [57, 1] = luebeckConwayPolynomial_59_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_59_1_irreducible

theorem ofCoeffs_61_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 61 [59, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_61_1
  change luebeckConwayPolynomialOfCoeffs 61 [59, 1] = luebeckConwayPolynomial_61_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_61_1_irreducible

theorem ofCoeffs_67_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 67 [65, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_67_1
  change luebeckConwayPolynomialOfCoeffs 67 [65, 1] = luebeckConwayPolynomial_67_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_67_1_irreducible

theorem ofCoeffs_71_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 71 [64, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_71_1
  change luebeckConwayPolynomialOfCoeffs 71 [64, 1] = luebeckConwayPolynomial_71_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_71_1_irreducible

theorem ofCoeffs_73_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 73 [68, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_73_1
  change luebeckConwayPolynomialOfCoeffs 73 [68, 1] = luebeckConwayPolynomial_73_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_73_1_irreducible

theorem ofCoeffs_79_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 79 [76, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_79_1
  change luebeckConwayPolynomialOfCoeffs 79 [76, 1] = luebeckConwayPolynomial_79_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_79_1_irreducible

theorem ofCoeffs_83_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 83 [81, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_83_1
  change luebeckConwayPolynomialOfCoeffs 83 [81, 1] = luebeckConwayPolynomial_83_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_83_1_irreducible

theorem ofCoeffs_89_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 89 [86, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_89_1
  change luebeckConwayPolynomialOfCoeffs 89 [86, 1] = luebeckConwayPolynomial_89_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_89_1_irreducible

theorem ofCoeffs_97_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 97 [92, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_97_1
  change luebeckConwayPolynomialOfCoeffs 97 [92, 1] = luebeckConwayPolynomial_97_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_97_1_irreducible


end Conway

end Hex
