/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Certificates
public import HexConway.Transport.S1_9

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

theorem ofCoeffs_619_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 619 [617, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_619_1
  change luebeckConwayPolynomialOfCoeffs 619 [617, 1] = luebeckConwayPolynomial_619_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_619_1_monic

theorem ofCoeffs_619_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 619 [617, 6, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_619_3
  change luebeckConwayPolynomialOfCoeffs 619 [617, 6, 0, 1] = luebeckConwayPolynomial_619_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_619_3_monic

theorem ofCoeffs_631_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 631 [628, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_631_1
  change luebeckConwayPolynomialOfCoeffs 631 [628, 1] = luebeckConwayPolynomial_631_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_631_1_monic

theorem ofCoeffs_631_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 631 [628, 5, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_631_3
  change luebeckConwayPolynomialOfCoeffs 631 [628, 5, 0, 1] = luebeckConwayPolynomial_631_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_631_3_monic

theorem ofCoeffs_641_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 641 [638, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_641_1
  change luebeckConwayPolynomialOfCoeffs 641 [638, 1] = luebeckConwayPolynomial_641_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_641_1_monic

theorem ofCoeffs_641_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 641 [638, 4, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_641_3
  change luebeckConwayPolynomialOfCoeffs 641 [638, 4, 0, 1] = luebeckConwayPolynomial_641_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_641_3_monic

theorem ofCoeffs_643_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 643 [632, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_643_1
  change luebeckConwayPolynomialOfCoeffs 643 [632, 1] = luebeckConwayPolynomial_643_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_643_1_monic

theorem ofCoeffs_643_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 643 [632, 1, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_643_3
  change luebeckConwayPolynomialOfCoeffs 643 [632, 1, 0, 1] = luebeckConwayPolynomial_643_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_643_3_monic

theorem ofCoeffs_647_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 647 [642, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_647_1
  change luebeckConwayPolynomialOfCoeffs 647 [642, 1] = luebeckConwayPolynomial_647_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_647_1_monic

theorem ofCoeffs_647_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 647 [642, 6, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_647_3
  change luebeckConwayPolynomialOfCoeffs 647 [642, 6, 0, 1] = luebeckConwayPolynomial_647_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_647_3_monic

theorem ofCoeffs_653_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 653 [651, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_653_1
  change luebeckConwayPolynomialOfCoeffs 653 [651, 1] = luebeckConwayPolynomial_653_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_653_1_monic

theorem ofCoeffs_653_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 653 [651, 3, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_653_3
  change luebeckConwayPolynomialOfCoeffs 653 [651, 3, 0, 1] = luebeckConwayPolynomial_653_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_653_3_monic

theorem ofCoeffs_659_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 659 [657, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_659_1
  change luebeckConwayPolynomialOfCoeffs 659 [657, 1] = luebeckConwayPolynomial_659_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_659_1_monic

theorem ofCoeffs_659_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 659 [657, 2, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_659_3
  change luebeckConwayPolynomialOfCoeffs 659 [657, 2, 0, 1] = luebeckConwayPolynomial_659_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_659_3_monic

theorem ofCoeffs_661_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 661 [659, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_661_1
  change luebeckConwayPolynomialOfCoeffs 661 [659, 1] = luebeckConwayPolynomial_661_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_661_1_monic

theorem ofCoeffs_661_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 661 [659, 4, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_661_3
  change luebeckConwayPolynomialOfCoeffs 661 [659, 4, 0, 1] = luebeckConwayPolynomial_661_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_661_3_monic

theorem ofCoeffs_673_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 673 [668, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_673_1
  change luebeckConwayPolynomialOfCoeffs 673 [668, 1] = luebeckConwayPolynomial_673_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_673_1_monic

theorem ofCoeffs_673_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 673 [668, 1, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_673_3
  change luebeckConwayPolynomialOfCoeffs 673 [668, 1, 0, 1] = luebeckConwayPolynomial_673_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_673_3_monic

theorem ofCoeffs_677_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 677 [675, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_677_1
  change luebeckConwayPolynomialOfCoeffs 677 [675, 1] = luebeckConwayPolynomial_677_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_677_1_monic

theorem ofCoeffs_677_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 677 [675, 2, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_677_3
  change luebeckConwayPolynomialOfCoeffs 677 [675, 2, 0, 1] = luebeckConwayPolynomial_677_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_677_3_monic

theorem ofCoeffs_683_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 683 [678, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_683_1
  change luebeckConwayPolynomialOfCoeffs 683 [678, 1] = luebeckConwayPolynomial_683_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_683_1_monic

theorem ofCoeffs_683_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 683 [678, 5, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_683_3
  change luebeckConwayPolynomialOfCoeffs 683 [678, 5, 0, 1] = luebeckConwayPolynomial_683_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_683_3_monic

theorem ofCoeffs_691_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 691 [688, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_691_1
  change luebeckConwayPolynomialOfCoeffs 691 [688, 1] = luebeckConwayPolynomial_691_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_691_1_monic

theorem ofCoeffs_691_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 691 [688, 14, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_691_3
  change luebeckConwayPolynomialOfCoeffs 691 [688, 14, 0, 1] = luebeckConwayPolynomial_691_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_691_3_monic


end Conway

end Hex
