/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Certificates
public import HexConway.Transport.S2_9

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

theorem ofCoeffs_619_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 619 [2, 618, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_619_2
  change luebeckConwayPolynomialOfCoeffs 619 [2, 618, 1] = luebeckConwayPolynomial_619_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_619_2_irreducible

theorem ofCoeffs_619_4_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 619 [2, 492, 6, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_619_4
  change luebeckConwayPolynomialOfCoeffs 619 [2, 492, 6, 0, 1] = luebeckConwayPolynomial_619_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_619_4_irreducible

theorem ofCoeffs_631_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 631 [3, 629, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_631_2
  change luebeckConwayPolynomialOfCoeffs 631 [3, 629, 1] = luebeckConwayPolynomial_631_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_631_2_irreducible

theorem ofCoeffs_631_4_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 631 [3, 376, 6, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_631_4
  change luebeckConwayPolynomialOfCoeffs 631 [3, 376, 6, 0, 1] = luebeckConwayPolynomial_631_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_631_4_irreducible

theorem ofCoeffs_641_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 641 [3, 635, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_641_2
  change luebeckConwayPolynomialOfCoeffs 641 [3, 635, 1] = luebeckConwayPolynomial_641_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_641_2_irreducible

theorem ofCoeffs_641_4_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 641 [3, 629, 0, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_641_4
  change luebeckConwayPolynomialOfCoeffs 641 [3, 629, 0, 0, 1] = luebeckConwayPolynomial_641_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_641_4_irreducible

theorem ofCoeffs_643_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 643 [11, 641, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_643_2
  change luebeckConwayPolynomialOfCoeffs 643 [11, 641, 1] = luebeckConwayPolynomial_643_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_643_2_irreducible

theorem ofCoeffs_643_4_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 643 [11, 600, 0, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_643_4
  change luebeckConwayPolynomialOfCoeffs 643 [11, 600, 0, 0, 1] = luebeckConwayPolynomial_643_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_643_4_irreducible

theorem ofCoeffs_647_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 647 [5, 645, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_647_2
  change luebeckConwayPolynomialOfCoeffs 647 [5, 645, 1] = luebeckConwayPolynomial_647_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_647_2_irreducible

theorem ofCoeffs_647_4_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 647 [5, 643, 3, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_647_4
  change luebeckConwayPolynomialOfCoeffs 647 [5, 643, 3, 0, 1] = luebeckConwayPolynomial_647_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_647_4_irreducible

theorem ofCoeffs_653_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 653 [2, 649, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_653_2
  change luebeckConwayPolynomialOfCoeffs 653 [2, 649, 1] = luebeckConwayPolynomial_653_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_653_2_irreducible

theorem ofCoeffs_653_4_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 653 [2, 596, 6, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_653_4
  change luebeckConwayPolynomialOfCoeffs 653 [2, 596, 6, 0, 1] = luebeckConwayPolynomial_653_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_653_4_irreducible

theorem ofCoeffs_659_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 659 [2, 655, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_659_2
  change luebeckConwayPolynomialOfCoeffs 659 [2, 655, 1] = luebeckConwayPolynomial_659_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_659_2_irreducible

theorem ofCoeffs_659_4_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 659 [2, 351, 8, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_659_4
  change luebeckConwayPolynomialOfCoeffs 659 [2, 351, 8, 0, 1] = luebeckConwayPolynomial_659_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_659_4_irreducible

theorem ofCoeffs_661_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 661 [2, 660, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_661_2
  change luebeckConwayPolynomialOfCoeffs 661 [2, 660, 1] = luebeckConwayPolynomial_661_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_661_2_irreducible

theorem ofCoeffs_661_4_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 661 [2, 616, 7, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_661_4
  change luebeckConwayPolynomialOfCoeffs 661 [2, 616, 7, 0, 1] = luebeckConwayPolynomial_661_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_661_4_irreducible

theorem ofCoeffs_673_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 673 [5, 672, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_673_2
  change luebeckConwayPolynomialOfCoeffs 673 [5, 672, 1] = luebeckConwayPolynomial_673_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_673_2_irreducible

theorem ofCoeffs_673_4_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 673 [5, 416, 6, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_673_4
  change luebeckConwayPolynomialOfCoeffs 673 [5, 416, 6, 0, 1] = luebeckConwayPolynomial_673_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_673_4_irreducible

theorem ofCoeffs_677_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 677 [2, 672, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_677_2
  change luebeckConwayPolynomialOfCoeffs 677 [2, 672, 1] = luebeckConwayPolynomial_677_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_677_2_irreducible

theorem ofCoeffs_677_4_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 677 [2, 631, 0, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_677_4
  change luebeckConwayPolynomialOfCoeffs 677 [2, 631, 0, 0, 1] = luebeckConwayPolynomial_677_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_677_4_irreducible

theorem ofCoeffs_683_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 683 [5, 682, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_683_2
  change luebeckConwayPolynomialOfCoeffs 683 [5, 682, 1] = luebeckConwayPolynomial_683_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_683_2_irreducible

theorem ofCoeffs_683_4_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 683 [5, 455, 5, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_683_4
  change luebeckConwayPolynomialOfCoeffs 683 [5, 455, 5, 0, 1] = luebeckConwayPolynomial_683_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_683_4_irreducible

theorem ofCoeffs_691_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 691 [3, 686, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_691_2
  change luebeckConwayPolynomialOfCoeffs 691 [3, 686, 1] = luebeckConwayPolynomial_691_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_691_2_irreducible

theorem ofCoeffs_691_4_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 691 [3, 632, 3, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_691_4
  change luebeckConwayPolynomialOfCoeffs 691 [3, 632, 3, 0, 1] = luebeckConwayPolynomial_691_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_691_4_irreducible


end Conway

end Hex
