/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexDeterminantalIdealMathlib.Transport
public import Mathlib.RingTheory.Ideal.Span

public section

/-!
The determinantal ideal `I_r(A) = Ideal.span {x | x ∈ minors r A}`: it is
generated by `detIdealGens r A` as well, it is the unit ideal at `r = 0` and
the zero ideal past the dimensions, the ideals descend in `r` (Laplace
expansion), and `I_r` is unchanged by transposition and by invertible row
and column operations (Cauchy-Binet through `minor_mul_left_expand` and
`minor_mul_right_expand`).
-/

namespace HexDeterminantalIdealMathlib

open Hex.Matrix

universe u v

variable {R : Type u} [CommRing R] {n m : Nat}

/-- A fold of additions of members of an ideal, from a member, stays in the
ideal. -/
private theorem foldl_add_mem (I : Ideal R) {α : Type v} (xs : List α) (f : α → R) (z : R)
    (hz : z ∈ I) (h : ∀ x ∈ xs, f x ∈ I) :
    xs.foldl (fun acc x => acc + f x) z ∈ I := by
  induction xs generalizing z with
  | nil => exact hz
  | cons x xs ih =>
    exact ih _ (I.add_mem hz (h x List.mem_cons_self)) fun y hy => h y (List.mem_cons_of_mem x hy)

/-- `detIdealGens` generates the same ideal as `minors`. -/
theorem span_detIdealGens_eq [DecidableEq R] (A : Hex.Matrix R n m) (r : Nat) :
    Ideal.span {x | x ∈ detIdealGens r A} = Ideal.span {x | x ∈ minors r A} := by
  apply le_antisymm
  · apply Ideal.span_mono
    intro x hx
    exact ((mem_detIdealGens_iff A r x).mp hx).1
  · rw [Ideal.span_le]
    intro x hx
    by_cases h0 : x = 0
    · rw [h0]
      exact Ideal.zero_mem _
    · exact Ideal.subset_span ((mem_detIdealGens_iff A r x).mpr ⟨hx, h0⟩)

/-- `I_0(A)` is the unit ideal. -/
theorem span_minors_zero (A : Hex.Matrix R n m) :
    Ideal.span {x | x ∈ minors 0 A} = ⊤ := by
  rw [minors_zero]
  have h : {x : R | x ∈ [1]} = {1} := by
    ext x
    simp
  rw [h, Ideal.span_singleton_one]

/-- `I_r(A)` is the zero ideal once `r` exceeds a dimension. -/
theorem span_minors_eq_bot_of_lt (A : Hex.Matrix R n m) {r : Nat} (h : n < r ∨ m < r) :
    Ideal.span {x | x ∈ minors r A} = ⊥ := by
  rw [(minors_eq_nil_iff A r).mpr h]
  have h' : {x : R | x ∈ ([] : List R)} = ∅ := by
    ext x
    simp
  rw [h', Ideal.span_empty]

/-- The determinantal ideals descend: `I_(r+1)(A) ≤ I_r(A)`. -/
theorem span_minors_succ_le (A : Hex.Matrix R n m) (r : Nat) :
    Ideal.span {x | x ∈ minors (r + 1) A} ≤ Ideal.span {x | x ∈ minors r A} := by
  rw [Ideal.span_le]
  intro x hx
  obtain ⟨rows, hrows, cols, hcols, rfl⟩ := (mem_minors_iff A (r + 1) x).mp hx
  rw [SetLike.mem_coe, det_eq_foldl_laplace_col _ ⟨0, Nat.succ_pos r⟩]
  apply foldl_add_mem _ _ _ _ (Ideal.zero_mem _)
  intro i _
  apply Ideal.mul_mem_left
  unfold cofactor
  apply Ideal.mul_mem_left
  rw [deleteRowCol_selectedSubmatrix]
  apply Ideal.subset_span
  exact (mem_minors_iff A r _).mpr
    ⟨_, (mem_selectedColumnTuples_iff _).mpr
        (isStrictlyIncreasingColumnTuple_eraseIdx ((mem_selectedColumnTuples_iff _).mp hrows) i),
      _, (mem_selectedColumnTuples_iff _).mpr
        (isStrictlyIncreasingColumnTuple_eraseIdx ((mem_selectedColumnTuples_iff _).mp hcols)
          ⟨0, Nat.succ_pos r⟩), rfl⟩

/-- Transposition preserves `I_r`. -/
theorem span_minors_transpose (A : Hex.Matrix R n m) (r : Nat) :
    Ideal.span {x | x ∈ minors r A.transpose} = Ideal.span {x | x ∈ minors r A} := by
  congr 1
  ext x
  exact (minors_transpose A r).mem_iff

/-- `I_r(P * A) ≤ I_r(A)`. -/
theorem span_minors_mul_left_le {q : Nat} (P : Hex.Matrix R q n) (A : Hex.Matrix R n m)
    (r : Nat) :
    Ideal.span {x | x ∈ minors r (P * A)} ≤ Ideal.span {x | x ∈ minors r A} := by
  rw [Ideal.span_le]
  intro x hx
  obtain ⟨rows, hrows, cols, hcols, rfl⟩ := (mem_minors_iff (P * A) r x).mp hx
  rw [SetLike.mem_coe, minor_mul_left_expand]
  apply foldl_add_mem _ _ _ _ (Ideal.zero_mem _)
  intro middle hmid
  apply Ideal.mul_mem_right
  exact Ideal.subset_span ((mem_minors_iff A r _).mpr ⟨middle, hmid, cols, hcols, rfl⟩)

/-- `I_r(A * Q) ≤ I_r(A)`. -/
theorem span_minors_mul_right_le {q : Nat} (A : Hex.Matrix R n m) (Q : Hex.Matrix R m q)
    (r : Nat) :
    Ideal.span {x | x ∈ minors r (A * Q)} ≤ Ideal.span {x | x ∈ minors r A} := by
  rw [Ideal.span_le]
  intro x hx
  obtain ⟨rows, hrows, cols, hcols, rfl⟩ := (mem_minors_iff (A * Q) r x).mp hx
  rw [SetLike.mem_coe, minor_mul_right_expand]
  apply foldl_add_mem _ _ _ _ (Ideal.zero_mem _)
  intro middle hmid
  apply Ideal.mul_mem_left
  exact Ideal.subset_span ((mem_minors_iff A r _).mpr ⟨rows, hrows, middle, hmid, rfl⟩)

/-- An invertible row operation preserves `I_r`. -/
theorem span_minors_mul_left_eq (P Pinv : Hex.Matrix R n n)
    (h : Pinv * P = Hex.Matrix.identity (R := R) n) (A : Hex.Matrix R n m) (r : Nat) :
    Ideal.span {x | x ∈ minors r (P * A)} = Ideal.span {x | x ∈ minors r A} := by
  apply le_antisymm (span_minors_mul_left_le P A r)
  have hA : Pinv * (P * A) = A := by
    rw [← Hex.Matrix.mul_assoc, h, Hex.Matrix.identity_mul]
  have hle := span_minors_mul_left_le Pinv (P * A) r
  rw [hA] at hle
  exact hle

/-- An invertible column operation preserves `I_r`. -/
theorem span_minors_mul_right_eq (Q Qinv : Hex.Matrix R m m)
    (h : Q * Qinv = Hex.Matrix.identity (R := R) m) (A : Hex.Matrix R n m) (r : Nat) :
    Ideal.span {x | x ∈ minors r (A * Q)} = Ideal.span {x | x ∈ minors r A} := by
  apply le_antisymm (span_minors_mul_right_le A Q r)
  have hA : (A * Q) * Qinv = A := by
    rw [Hex.Matrix.mul_assoc, h, Hex.Matrix.mul_identity]
  have hle := span_minors_mul_right_le (A * Q) Qinv r
  rw [hA] at hle
  exact hle

end HexDeterminantalIdealMathlib
