/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexMatrix.MatrixAlgebra

public section

/-! Integer row-lattice membership and transport through explicit row maps. -/

namespace Hex.Matrix

/-- `v` lies in the integer lattice generated by the rows of `b`. -/
@[expose]
def memLattice (b : Matrix Int n m) (v : Vector Int m) : Prop :=
  ∃ c : Vector Int n, vecMul c b = v

/-- Row combinations transport across an explicit integer row transform. -/
theorem vecMul_mul (U : Matrix Int n' n) (B : Matrix Int n m)
    (c : Vector Int n') :
    vecMul (Matrix.transpose U * c) B = vecMul c (U * B) := by
  unfold vecMul
  calc
    Matrix.transpose B * (Matrix.transpose U * c) =
        (Matrix.transpose B * Matrix.transpose U) * c := by
          exact (Matrix.mul_assoc_vec (A := Matrix.transpose B)
            (B := Matrix.transpose U) (v := c)).symm
    _ = Matrix.transpose (U * B) * c := by
          rw [← Matrix.transpose_mul_of_mul_comm]

/-- If every row of `B'` is an integer row combination of rows of `B`, then
membership in the lattice generated by `B'` implies membership for `B`. -/
theorem memLattice_of_mul_eq {B : Matrix Int n m} {B' : Matrix Int n' m}
    {U : Matrix Int n' n} {v : Vector Int m} (h : U * B = B') :
    B'.memLattice v → B.memLattice v := by
  intro hv
  rcases hv with ⟨c, hc⟩
  refine ⟨Matrix.transpose U * c, ?_⟩
  rw [vecMul_mul U B, h, hc]

/-- Two explicit integer row transforms in opposite directions prove equality
of the generated row lattices. -/
theorem memLattice_iff_of_mul_eq {B B' : Matrix Int n m} {U V : Matrix Int n n}
    (hU : U * B = B') (hV : V * B' = B) (v : Vector Int m) :
    B.memLattice v ↔ B'.memLattice v := by
  constructor
  · exact memLattice_of_mul_eq hV
  · exact memLattice_of_mul_eq hU

end Hex.Matrix
