/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.PrimitivityCore
public import HexConway.PrimeFactors
public import HexConway.PrimitiveProofs.S2_0

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- C(127, 4) has a generator of order 260144640. -/
theorem primitive_127_4 :
    Primitive 127 4 supportedEntry_127_4 [2, 3, 5, 7, 1613] [9, 2, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_1613
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(53, 4) has a generator of order 7890480. -/
theorem primitive_53_4 :
    Primitive 53 4 supportedEntry_53_4 [2, 3, 5, 13, 281] [4, 3, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_281
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(919, 3) has a generator of order 776151558. -/
theorem primitive_919_3 :
    Primitive 919 3 supportedEntry_919_3 [2, 3, 7, 13, 17, 19, 163] [1, 4, 1, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_17
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_19
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_163
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(691, 3) has a generator of order 329939370. -/
theorem primitive_691_3 :
    Primitive 691 3 supportedEntry_691_3 [2, 3, 5, 19, 23, 8389] [1, 2, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_19
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_23
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_8389
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(823, 3) has a generator of order 557441766. -/
theorem primitive_823_3 :
    Primitive 823 3 supportedEntry_823_3 [2, 3, 7, 43, 137, 751] [1, 2, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_43
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_137
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_751
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(971, 3) has a generator of order 915498610. -/
theorem primitive_971_3 :
    Primitive 971 3 supportedEntry_971_3 [2, 5, 13, 79, 97, 919] [1, 1, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_79
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_97
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_919
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(31, 4) has a generator of order 923520. -/
theorem primitive_31_4 :
    Primitive 31 4 supportedEntry_31_4 [2, 3, 5, 13, 37] [7, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_37
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(277, 3) has a generator of order 21253932. -/
theorem primitive_277_3 :
    Primitive 277 3 supportedEntry_277_3 [2, 3, 7, 19, 23, 193] [2, 2, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_19
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_23
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_193
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(463, 3) has a generator of order 99252846. -/
theorem primitive_463_3 :
    Primitive 463 3 supportedEntry_463_3 [2, 3, 7, 11, 19, 3769] [1, 2, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_19
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3769
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(541, 3) has a generator of order 158340420. -/
theorem primitive_541_3 :
    Primitive 541 3 supportedEntry_541_3 [2, 3, 5, 7, 13963] [2, 4, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13963
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(613, 3) has a generator of order 230346396. -/
theorem primitive_613_3 :
    Primitive 613 3 supportedEntry_613_3 [2, 3, 7, 17, 17923] [2, 3, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_17
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_17923
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(647, 3) has a generator of order 270840022. -/
theorem primitive_647_3 :
    Primitive 647 3 supportedEntry_647_3 [2, 17, 19, 211, 1987] [1, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_17
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_19
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_211
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_1987
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(683, 3) has a generator of order 318611986. -/
theorem primitive_683_3 :
    Primitive 683 3 supportedEntry_683_3 [2, 7, 11, 31, 66739] [1, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_31
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_66739
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(751, 3) has a generator of order 423564750. -/
theorem primitive_751_3 :
    Primitive 751 3 supportedEntry_751_3 [2, 3, 5, 7, 26893] [1, 2, 3, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_26893
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(853, 3) has a generator of order 620650476. -/
theorem primitive_853_3 :
    Primitive 853 3 supportedEntry_853_3 [2, 3, 43, 71, 5647] [2, 2, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_43
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_71
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5647
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(911, 3) has a generator of order 756058030. -/
theorem primitive_911_3 :
    Primitive 911 3 supportedEntry_911_3 [2, 5, 7, 13, 830833] [1, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_830833
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(191, 3) has a generator of order 6967870. -/
theorem primitive_191_3 :
    Primitive 191 3 supportedEntry_191_3 [2, 5, 7, 13, 19, 31] [1, 1, 1, 2, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_19
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_31
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(263, 3) has a generator of order 18191446. -/
theorem primitive_263_3 :
    Primitive 263 3 supportedEntry_263_3 [2, 7, 13, 109, 131] [1, 2, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_109
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_131
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(307, 3) has a generator of order 28934442. -/
theorem primitive_307_3 :
    Primitive 307 3 supportedEntry_307_3 [2, 3, 17, 43, 733] [1, 3, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_17
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_43
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_733
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(349, 3) has a generator of order 42508548. -/
theorem primitive_349_3 :
    Primitive 349 3 supportedEntry_349_3 [2, 3, 19, 29, 2143] [2, 2, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_19
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_29
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2143
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(397, 3) has a generator of order 62570772. -/
theorem primitive_397_3 :
    Primitive 397 3 supportedEntry_397_3 [2, 3, 11, 31, 1699] [2, 3, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_31
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_1699
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(443, 3) has a generator of order 86938306. -/
theorem primitive_443_3 :
    Primitive 443 3 supportedEntry_443_3 [2, 7, 13, 17, 28099] [1, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_17
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_28099
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(499, 3) has a generator of order 124251498. -/
theorem primitive_499_3 :
    Primitive 499 3 supportedEntry_499_3 [2, 3, 7, 83, 109] [1, 2, 1, 1, 2] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_83
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_109
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(139, 3) has a generator of order 2685618. -/
theorem primitive_139_3 :
    Primitive 139 3 supportedEntry_139_3 [2, 3, 13, 23, 499] [1, 2, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_23
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_499
    exact absurd hq (by simp)
  check := by decide +kernel


end Conway

end Hex
