/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.PrimitivityCore
public import HexConway.PrimeFactors
public import HexConway.PrimitiveProofs.S3_2

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- C(419, 2) has a generator of order 175560. -/
theorem primitive_419_2 :
    Primitive 419 2 supportedEntry_419_2 [2, 3, 5, 7, 11, 19] [3, 1, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_19
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(547, 2) has a generator of order 299208. -/
theorem primitive_547_2 :
    Primitive 547 2 supportedEntry_547_2 [2, 3, 7, 13, 137] [3, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_137
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(617, 2) has a generator of order 380688. -/
theorem primitive_617_2 :
    Primitive 617 2 supportedEntry_617_2 [2, 3, 7, 11, 103] [4, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_103
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(661, 2) has a generator of order 436920. -/
theorem primitive_661_2 :
    Primitive 661 2 supportedEntry_661_2 [2, 3, 5, 11, 331] [3, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_331
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(709, 2) has a generator of order 502680. -/
theorem primitive_709_2 :
    Primitive 709 2 supportedEntry_709_2 [2, 3, 5, 59, 71] [3, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_59
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_71
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(761, 2) has a generator of order 579120. -/
theorem primitive_761_2 :
    Primitive 761 2 supportedEntry_761_2 [2, 3, 5, 19, 127] [4, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_19
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_127
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(821, 2) has a generator of order 674040. -/
theorem primitive_821_2 :
    Primitive 821 2 supportedEntry_821_2 [2, 3, 5, 41, 137] [3, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_41
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_137
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(853, 2) has a generator of order 727608. -/
theorem primitive_853_2 :
    Primitive 853 2 supportedEntry_853_2 [2, 3, 7, 61, 71] [3, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_61
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_71
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(919, 2) has a generator of order 844560. -/
theorem primitive_919_2 :
    Primitive 919 2 supportedEntry_919_2 [2, 3, 5, 17, 23] [4, 3, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_17
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_23
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(947, 2) has a generator of order 896808. -/
theorem primitive_947_2 :
    Primitive 947 2 supportedEntry_947_2 [2, 3, 11, 43, 79] [3, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_43
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_79
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(281, 2) has a generator of order 78960. -/
theorem primitive_281_2 :
    Primitive 281 2 supportedEntry_281_2 [2, 3, 5, 7, 47] [4, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_47
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(349, 2) has a generator of order 121800. -/
theorem primitive_349_2 :
    Primitive 349 2 supportedEntry_349_2 [2, 3, 5, 7, 29] [3, 1, 2, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_29
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(409, 2) has a generator of order 167280. -/
theorem primitive_409_2 :
    Primitive 409 2 supportedEntry_409_2 [2, 3, 5, 17, 41] [4, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_17
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_41
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(463, 2) has a generator of order 214368. -/
theorem primitive_463_2 :
    Primitive 463 2 supportedEntry_463_2 [2, 3, 7, 11, 29] [5, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_29
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(131, 2) has a generator of order 17160. -/
theorem primitive_131_2 :
    Primitive 131 2 supportedEntry_131_2 [2, 3, 5, 11, 13] [3, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(229, 2) has a generator of order 52440. -/
theorem primitive_229_2 :
    Primitive 229 2 supportedEntry_229_2 [2, 3, 5, 19, 23] [3, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_19
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_23
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(557, 2) has a generator of order 310248. -/
theorem primitive_557_2 :
    Primitive 557 2 supportedEntry_557_2 [2, 3, 31, 139] [3, 2, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_31
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_139
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(607, 2) has a generator of order 368448. -/
theorem primitive_607_2 :
    Primitive 607 2 supportedEntry_607_2 [2, 3, 19, 101] [6, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_19
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_101
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(653, 2) has a generator of order 426408. -/
theorem primitive_653_2 :
    Primitive 653 2 supportedEntry_653_2 [2, 3, 109, 163] [3, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_109
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_163
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(733, 2) has a generator of order 537288. -/
theorem primitive_733_2 :
    Primitive 733 2 supportedEntry_733_2 [2, 3, 61, 367] [3, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_61
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_367
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(787, 2) has a generator of order 619368. -/
theorem primitive_787_2 :
    Primitive 787 2 supportedEntry_787_2 [2, 3, 131, 197] [3, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_131
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_197
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(887, 2) has a generator of order 786768. -/
theorem primitive_887_2 :
    Primitive 887 2 supportedEntry_887_2 [2, 3, 37, 443] [4, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_37
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_443
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(983, 2) has a generator of order 966288. -/
theorem primitive_983_2 :
    Primitive 983 2 supportedEntry_983_2 [2, 3, 41, 491] [4, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_41
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_491
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(271, 2) has a generator of order 73440. -/
theorem primitive_271_2 :
    Primitive 271 2 supportedEntry_271_2 [2, 3, 5, 17] [5, 3, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_17
    exact absurd hq (by simp)
  check := by decide +kernel


end Conway

end Hex
