/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.PrimitivityCore
public import HexConway.PrimeFactors
public import HexConway.PrimitiveProofs.S3_4

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- C(157, 2) has a generator of order 24648. -/
theorem primitive_157_2 :
    Primitive 157 2 supportedEntry_157_2 [2, 3, 13, 79] [3, 1, 1, 1]
      [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0] [[1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0], [1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0], [1, 0, 0, 1, 1, 1, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_79
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(191, 2) has a generator of order 36480. -/
theorem primitive_191_2 :
    Primitive 191 2 supportedEntry_191_2 [2, 3, 5, 19] [7, 1, 1, 1]
      [1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0] [[1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0], [1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_19
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(227, 2) has a generator of order 51528. -/
theorem primitive_227_2 :
    Primitive 227 2 supportedEntry_227_2 [2, 3, 19, 113] [3, 1, 1, 1]
      [1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0] [[1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0], [1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0], [1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0], [1, 1, 1, 0, 0, 1, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_19
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_113
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(2, 5) has a generator of order 31. -/
theorem primitive_2_5 :
    Primitive 2 5 supportedEntry_2_5 [31] [1]
      [1, 1, 1, 1, 1] [[1]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_31
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(71, 2) has a generator of order 5040. -/
theorem primitive_71_2 :
    Primitive 71 2 supportedEntry_71_2 [2, 3, 5, 7] [4, 2, 1, 1]
      [1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0] [[1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0], [1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 0, 0, 0, 0], [1, 0, 1, 1, 0, 1, 0, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(89, 2) has a generator of order 7920. -/
theorem primitive_89_2 :
    Primitive 89 2 supportedEntry_89_2 [2, 3, 5, 11] [4, 2, 1, 1]
      [1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0] [[1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0], [1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0], [1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0], [1, 0, 1, 1, 0, 1, 0, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(113, 2) has a generator of order 12768. -/
theorem primitive_113_2 :
    Primitive 113 2 supportedEntry_113_2 [2, 3, 7, 19] [5, 1, 1, 1]
      [1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0] [[1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0], [1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0], [1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0], [1, 0, 1, 0, 1, 0, 0, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_19
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(43, 2) has a generator of order 1848. -/
theorem primitive_43_2 :
    Primitive 43 2 supportedEntry_43_2 [2, 3, 7, 11] [3, 1, 1, 1]
      [1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0] [[1, 1, 1, 0, 0, 1, 1, 1, 0, 0], [1, 0, 0, 1, 1, 0, 1, 0, 0, 0], [1, 0, 0, 0, 0, 1, 0, 0, 0], [1, 0, 1, 0, 1, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(163, 2) has a generator of order 26568. -/
theorem primitive_163_2 :
    Primitive 163 2 supportedEntry_163_2 [2, 3, 41] [3, 4, 1]
      [1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0] [[1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0], [1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0], [1, 0, 1, 0, 0, 0, 1, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_41
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(127, 2) has a generator of order 16128. -/
theorem primitive_127_2 :
    Primitive 127 2 supportedEntry_127_2 [2, 3, 7] [8, 2, 1]
      [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0] [[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0], [1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(53, 2) has a generator of order 2808. -/
theorem primitive_53_2 :
    Primitive 53 2 supportedEntry_53_2 [2, 3, 13] [3, 3, 1]
      [1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0] [[1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0], [1, 1, 1, 0, 1, 0, 1, 0, 0, 0], [1, 1, 0, 1, 1, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(31, 2) has a generator of order 960. -/
theorem primitive_31_2 :
    Primitive 31 2 supportedEntry_31_2 [2, 3, 5] [6, 1, 1]
      [1, 1, 1, 1, 0, 0, 0, 0, 0, 0] [[1, 1, 1, 1, 0, 0, 0, 0, 0], [1, 0, 1, 0, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(17, 2) has a generator of order 288. -/
theorem primitive_17_2 :
    Primitive 17 2 supportedEntry_17_2 [2, 3] [5, 2]
      [1, 0, 0, 1, 0, 0, 0, 0, 0] [[1, 0, 0, 1, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(7, 2) has a generator of order 48. -/
theorem primitive_7_2 :
    Primitive 7 2 supportedEntry_7_2 [2, 3] [4, 1]
      [1, 1, 0, 0, 0, 0] [[1, 1, 0, 0, 0], [1, 0, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(661, 1) has a generator of order 660. -/
theorem primitive_661_1 :
    Primitive 661 1 supportedEntry_661_1 [2, 3, 5, 11] [2, 1, 1, 1]
      [1, 0, 1, 0, 0, 1, 0, 1, 0, 0] [[1, 0, 1, 0, 0, 1, 0, 1, 0], [1, 1, 0, 1, 1, 1, 0, 0], [1, 0, 0, 0, 0, 1, 0, 0], [1, 1, 1, 1, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(967, 1) has a generator of order 966. -/
theorem primitive_967_1 :
    Primitive 967 1 supportedEntry_967_1 [2, 3, 7, 23] [1, 1, 1, 1]
      [1, 1, 1, 1, 0, 0, 0, 1, 1, 0] [[1, 1, 1, 1, 0, 0, 0, 1, 1], [1, 0, 1, 0, 0, 0, 0, 1, 0], [1, 0, 0, 0, 1, 0, 1, 0], [1, 0, 1, 0, 1, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_23
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(463, 1) has a generator of order 462. -/
theorem primitive_463_1 :
    Primitive 463 1 supportedEntry_463_1 [2, 3, 7, 11] [1, 1, 1, 1]
      [1, 1, 1, 0, 0, 1, 1, 1, 0] [[1, 1, 1, 0, 0, 1, 1, 1], [1, 0, 0, 1, 1, 0, 1, 0], [1, 0, 0, 0, 0, 1, 0], [1, 0, 1, 0, 1, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(599, 1) has a generator of order 598. -/
theorem primitive_599_1 :
    Primitive 599 1 supportedEntry_599_1 [2, 13, 23] [1, 1, 1]
      [1, 0, 0, 1, 0, 1, 0, 1, 1, 0] [[1, 0, 0, 1, 0, 1, 0, 1, 1], [1, 0, 1, 1, 1, 0], [1, 1, 0, 1, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_23
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(617, 1) has a generator of order 616. -/
theorem primitive_617_1 :
    Primitive 617 1 supportedEntry_617_1 [2, 7, 11] [3, 1, 1]
      [1, 0, 0, 1, 1, 0, 1, 0, 0, 0] [[1, 0, 0, 1, 1, 0, 1, 0, 0], [1, 0, 1, 1, 0, 0, 0], [1, 1, 1, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(659, 1) has a generator of order 658. -/
theorem primitive_659_1 :
    Primitive 659 1 supportedEntry_659_1 [2, 7, 47] [1, 1, 1]
      [1, 0, 1, 0, 0, 1, 0, 0, 1, 0] [[1, 0, 1, 0, 0, 1, 0, 0, 1], [1, 0, 1, 1, 1, 1, 0], [1, 1, 1, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_47
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(709, 1) has a generator of order 708. -/
theorem primitive_709_1 :
    Primitive 709 1 supportedEntry_709_1 [2, 3, 59] [2, 1, 1]
      [1, 0, 1, 1, 0, 0, 0, 1, 0, 0] [[1, 0, 1, 1, 0, 0, 0, 1, 0], [1, 1, 1, 0, 1, 1, 0, 0], [1, 1, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_59
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(743, 1) has a generator of order 742. -/
theorem primitive_743_1 :
    Primitive 743 1 supportedEntry_743_1 [2, 7, 53] [1, 1, 1]
      [1, 0, 1, 1, 1, 0, 0, 1, 1, 0] [[1, 0, 1, 1, 1, 0, 0, 1, 1], [1, 1, 0, 1, 0, 1, 0], [1, 1, 1, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_53
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(787, 1) has a generator of order 786. -/
theorem primitive_787_1 :
    Primitive 787 1 supportedEntry_787_1 [2, 3, 131] [1, 1, 1]
      [1, 1, 0, 0, 0, 1, 0, 0, 1, 0] [[1, 1, 0, 0, 0, 1, 0, 0, 1], [1, 0, 0, 0, 0, 0, 1, 1, 0], [1, 1, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_131
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(827, 1) has a generator of order 826. -/
theorem primitive_827_1 :
    Primitive 827 1 supportedEntry_827_1 [2, 7, 59] [1, 1, 1]
      [1, 1, 0, 0, 1, 1, 1, 0, 1, 0] [[1, 1, 0, 0, 1, 1, 1, 0, 1], [1, 1, 1, 0, 1, 1, 0], [1, 1, 1, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_59
    exact absurd hq (by simp)
  check := by decide +kernel


end Conway

end Hex
