/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.PrimitivityCore
public import HexConway.PrimeFactors
public import HexConway.PrimitiveProofs.S3_4

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- C(601, 1) has a generator of order 600. -/
theorem primitive_601_1 :
    Primitive 601 1 supportedEntry_601_1 [2, 3, 5] [3, 1, 2] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(619, 1) has a generator of order 618. -/
theorem primitive_619_1 :
    Primitive 619 1 supportedEntry_619_1 [2, 3, 103] [1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_103
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(673, 1) has a generator of order 672. -/
theorem primitive_673_1 :
    Primitive 673 1 supportedEntry_673_1 [2, 3, 7] [5, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(727, 1) has a generator of order 726. -/
theorem primitive_727_1 :
    Primitive 727 1 supportedEntry_727_1 [2, 3, 11] [1, 1, 2] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(751, 1) has a generator of order 750. -/
theorem primitive_751_1 :
    Primitive 751 1 supportedEntry_751_1 [2, 3, 5] [1, 1, 3] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(811, 1) has a generator of order 810. -/
theorem primitive_811_1 :
    Primitive 811 1 supportedEntry_811_1 [2, 3, 5] [1, 4, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(829, 1) has a generator of order 828. -/
theorem primitive_829_1 :
    Primitive 829 1 supportedEntry_829_1 [2, 3, 23] [2, 2, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_23
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(883, 1) has a generator of order 882. -/
theorem primitive_883_1 :
    Primitive 883 1 supportedEntry_883_1 [2, 3, 7] [1, 2, 2] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(941, 1) has a generator of order 940. -/
theorem primitive_941_1 :
    Primitive 941 1 supportedEntry_941_1 [2, 5, 47] [2, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_47
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(997, 1) has a generator of order 996. -/
theorem primitive_997_1 :
    Primitive 997 1 supportedEntry_997_1 [2, 3, 83] [2, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_83
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(311, 1) has a generator of order 310. -/
theorem primitive_311_1 :
    Primitive 311 1 supportedEntry_311_1 [2, 5, 31] [1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_31
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(367, 1) has a generator of order 366. -/
theorem primitive_367_1 :
    Primitive 367 1 supportedEntry_367_1 [2, 3, 61] [1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_61
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(409, 1) has a generator of order 408. -/
theorem primitive_409_1 :
    Primitive 409 1 supportedEntry_409_1 [2, 3, 17] [3, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_17
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(443, 1) has a generator of order 442. -/
theorem primitive_443_1 :
    Primitive 443 1 supportedEntry_443_1 [2, 13, 17] [1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_17
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(499, 1) has a generator of order 498. -/
theorem primitive_499_1 :
    Primitive 499 1 supportedEntry_499_1 [2, 3, 83] [1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_83
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(181, 1) has a generator of order 180. -/
theorem primitive_181_1 :
    Primitive 181 1 supportedEntry_181_1 [2, 3, 5] [2, 2, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(229, 1) has a generator of order 228. -/
theorem primitive_229_1 :
    Primitive 229 1 supportedEntry_229_1 [2, 3, 19] [2, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_19
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(71, 1) has a generator of order 70. -/
theorem primitive_71_1 :
    Primitive 71 1 supportedEntry_71_1 [2, 5, 7] [1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(103, 1) has a generator of order 102. -/
theorem primitive_103_1 :
    Primitive 103 1 supportedEntry_103_1 [2, 3, 17] [1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_17
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(577, 1) has a generator of order 576. -/
theorem primitive_577_1 :
    Primitive 577 1 supportedEntry_577_1 [2, 3] [6, 2] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(653, 1) has a generator of order 652. -/
theorem primitive_653_1 :
    Primitive 653 1 supportedEntry_653_1 [2, 163] [2, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_163
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(773, 1) has a generator of order 772. -/
theorem primitive_773_1 :
    Primitive 773 1 supportedEntry_773_1 [2, 193] [2, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_193
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(857, 1) has a generator of order 856. -/
theorem primitive_857_1 :
    Primitive 857 1 supportedEntry_857_1 [2, 107] [3, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_107
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(977, 1) has a generator of order 976. -/
theorem primitive_977_1 :
    Primitive 977 1 supportedEntry_977_1 [2, 61] [4, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_61
    exact absurd hq (by simp)
  check := by decide +kernel


end Conway

end Hex
