/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.PrimitivityCore
public import HexConway.PrimeFactors
public import HexConway.PrimitiveProofs.S3_5

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- C(881, 1) has a generator of order 880. -/
theorem primitive_881_1 :
    Primitive 881 1 supportedEntry_881_1 [2, 5, 11] [4, 1, 1]
      [1, 1, 0, 1, 1, 1, 0, 0, 0, 0] [[1, 1, 0, 1, 1, 1, 0, 0, 0], [1, 0, 1, 1, 0, 0, 0, 0], [1, 0, 1, 0, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(937, 1) has a generator of order 936. -/
theorem primitive_937_1 :
    Primitive 937 1 supportedEntry_937_1 [2, 3, 13] [3, 2, 1]
      [1, 1, 1, 0, 1, 0, 1, 0, 0, 0] [[1, 1, 1, 0, 1, 0, 1, 0, 0], [1, 0, 0, 1, 1, 1, 0, 0, 0], [1, 0, 0, 1, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(971, 1) has a generator of order 970. -/
theorem primitive_971_1 :
    Primitive 971 1 supportedEntry_971_1 [2, 5, 97] [1, 1, 1]
      [1, 1, 1, 1, 0, 0, 1, 0, 1, 0] [[1, 1, 1, 1, 0, 0, 1, 0, 1], [1, 1, 0, 0, 0, 0, 1, 0], [1, 0, 1, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_97
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(281, 1) has a generator of order 280. -/
theorem primitive_281_1 :
    Primitive 281 1 supportedEntry_281_1 [2, 5, 7] [3, 1, 1]
      [1, 0, 0, 0, 1, 1, 0, 0, 0] [[1, 0, 0, 0, 1, 1, 0, 0], [1, 1, 1, 0, 0, 0], [1, 0, 1, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(313, 1) has a generator of order 312. -/
theorem primitive_313_1 :
    Primitive 313 1 supportedEntry_313_1 [2, 3, 13] [3, 1, 1]
      [1, 0, 0, 1, 1, 1, 0, 0, 0] [[1, 0, 0, 1, 1, 1, 0, 0], [1, 1, 0, 1, 0, 0, 0], [1, 1, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(373, 1) has a generator of order 372. -/
theorem primitive_373_1 :
    Primitive 373 1 supportedEntry_373_1 [2, 3, 31] [2, 1, 1]
      [1, 0, 1, 1, 1, 0, 1, 0, 0] [[1, 0, 1, 1, 1, 0, 1, 0], [1, 1, 1, 1, 1, 0, 0], [1, 1, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_31
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(419, 1) has a generator of order 418. -/
theorem primitive_419_1 :
    Primitive 419 1 supportedEntry_419_1 [2, 11, 19] [1, 1, 1]
      [1, 1, 0, 1, 0, 0, 0, 1, 0] [[1, 1, 0, 1, 0, 0, 0, 1], [1, 0, 0, 1, 1, 0], [1, 0, 1, 1, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_19
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(457, 1) has a generator of order 456. -/
theorem primitive_457_1 :
    Primitive 457 1 supportedEntry_457_1 [2, 3, 19] [3, 1, 1]
      [1, 1, 1, 0, 0, 1, 0, 0, 0] [[1, 1, 1, 0, 0, 1, 0, 0], [1, 0, 0, 1, 1, 0, 0, 0], [1, 1, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_19
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(131, 1) has a generator of order 130. -/
theorem primitive_131_1 :
    Primitive 131 1 supportedEntry_131_1 [2, 5, 13] [1, 1, 1]
      [1, 0, 0, 0, 0, 0, 1, 0] [[1, 0, 0, 0, 0, 0, 1], [1, 1, 0, 1, 0], [1, 0, 1, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(157, 1) has a generator of order 156. -/
theorem primitive_157_1 :
    Primitive 157 1 supportedEntry_157_1 [2, 3, 13] [2, 1, 1]
      [1, 0, 0, 1, 1, 1, 0, 0] [[1, 0, 0, 1, 1, 1, 0], [1, 1, 0, 1, 0, 0], [1, 1, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(223, 1) has a generator of order 222. -/
theorem primitive_223_1 :
    Primitive 223 1 supportedEntry_223_1 [2, 3, 37] [1, 1, 1]
      [1, 1, 0, 1, 1, 1, 1, 0] [[1, 1, 0, 1, 1, 1, 1], [1, 0, 0, 1, 0, 1, 0], [1, 1, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_37
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(67, 1) has a generator of order 66. -/
theorem primitive_67_1 :
    Primitive 67 1 supportedEntry_67_1 [2, 3, 11] [1, 1, 1]
      [1, 0, 0, 0, 0, 1, 0] [[1, 0, 0, 0, 0, 1], [1, 0, 1, 1, 0], [1, 1, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(127, 1) has a generator of order 126. -/
theorem primitive_127_1 :
    Primitive 127 1 supportedEntry_127_1 [2, 3, 7] [1, 2, 1]
      [1, 1, 1, 1, 1, 1, 0] [[1, 1, 1, 1, 1, 1], [1, 0, 1, 0, 1, 0], [1, 0, 0, 1, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(587, 1) has a generator of order 586. -/
theorem primitive_587_1 :
    Primitive 587 1 supportedEntry_587_1 [2, 293] [1, 1]
      [1, 0, 0, 1, 0, 0, 1, 0, 1, 0] [[1, 0, 0, 1, 0, 0, 1, 0, 1], [1, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_293
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(677, 1) has a generator of order 676. -/
theorem primitive_677_1 :
    Primitive 677 1 supportedEntry_677_1 [2, 13] [2, 2]
      [1, 0, 1, 0, 1, 0, 0, 1, 0, 0] [[1, 0, 1, 0, 1, 0, 0, 1, 0], [1, 1, 0, 1, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(797, 1) has a generator of order 796. -/
theorem primitive_797_1 :
    Primitive 797 1 supportedEntry_797_1 [2, 199] [2, 1]
      [1, 1, 0, 0, 0, 1, 1, 1, 0, 0] [[1, 1, 0, 0, 0, 1, 1, 1, 0], [1, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_199
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(863, 1) has a generator of order 862. -/
theorem primitive_863_1 :
    Primitive 863 1 supportedEntry_863_1 [2, 431] [1, 1]
      [1, 1, 0, 1, 0, 1, 1, 1, 1, 0] [[1, 1, 0, 1, 0, 1, 1, 1, 1], [1, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_431
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(983, 1) has a generator of order 982. -/
theorem primitive_983_1 :
    Primitive 983 1 supportedEntry_983_1 [2, 491] [1, 1]
      [1, 1, 1, 1, 0, 1, 0, 1, 1, 0] [[1, 1, 1, 1, 0, 1, 0, 1, 1], [1, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_491
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(317, 1) has a generator of order 316. -/
theorem primitive_317_1 :
    Primitive 317 1 supportedEntry_317_1 [2, 79] [2, 1]
      [1, 0, 0, 1, 1, 1, 1, 0, 0] [[1, 0, 0, 1, 1, 1, 1, 0], [1, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_79
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(383, 1) has a generator of order 382. -/
theorem primitive_383_1 :
    Primitive 383 1 supportedEntry_383_1 [2, 191] [1, 1]
      [1, 0, 1, 1, 1, 1, 1, 1, 0] [[1, 0, 1, 1, 1, 1, 1, 1], [1, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_191
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(449, 1) has a generator of order 448. -/
theorem primitive_449_1 :
    Primitive 449 1 supportedEntry_449_1 [2, 7] [6, 1]
      [1, 1, 1, 0, 0, 0, 0, 0, 0] [[1, 1, 1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(503, 1) has a generator of order 502. -/
theorem primitive_503_1 :
    Primitive 503 1 supportedEntry_503_1 [2, 251] [1, 1]
      [1, 1, 1, 1, 1, 0, 1, 1, 0] [[1, 1, 1, 1, 1, 0, 1, 1], [1, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_251
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(137, 1) has a generator of order 136. -/
theorem primitive_137_1 :
    Primitive 137 1 supportedEntry_137_1 [2, 17] [3, 1]
      [1, 0, 0, 0, 1, 0, 0, 0] [[1, 0, 0, 0, 1, 0, 0], [1, 0, 0, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_17
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(167, 1) has a generator of order 166. -/
theorem primitive_167_1 :
    Primitive 167 1 supportedEntry_167_1 [2, 83] [1, 1]
      [1, 0, 1, 0, 0, 1, 1, 0] [[1, 0, 1, 0, 0, 1, 1], [1, 0]] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_83
    exact absurd hq (by simp)
  check := by decide +kernel


end Conway

end Hex
