/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

import VersoManual
import HexPermGroupMathlib
import Mathlib.GroupTheory.Perm.Cycle.Concrete

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

#doc (Manual) "HexPermGroup: checked finite permutation groups" =>
%%%
tag := "hex-perm-group"
%%%

# The Mathlib correspondence

`HexPermGroupMathlib` identifies the checked array representation with
`Equiv.Perm (Fin n)` and transports membership, order, stabilizers, and finite
actions to Mathlib. All producers and certificate checkers remain in the
Mathlib-free `HexPermGroup` library.

# Explicit actions and stabilizer chains

`Perm n` stores all `n` images, including fixed points. Composition is the
left-action convention `(p.comp q) x = p (q x)`. `Group.ofGenerators` builds a
complete checked stabilizer chain; order and negative membership become
mathematical facts only after that check succeeds.

```lean
open Hex Hex.PermGroup

namespace HexPermGroupChapter

def rotation : Perm 4 :=
  ⟨#v[1, 2, 3, 0], by decide, by decide⟩
def reflection : Perm 4 :=
  ⟨#v[0, 3, 2, 1], by decide, by decide⟩
def polygon : Group 4 :=
  Group.ofGenerators #[rotation, reflection]

#guard polygon.order = 8
#guard (polygon.orbit 0).size = 4
#guard (polygon.stabilizer 0).order = 2
#guard (polygon.word? (rotation.comp reflection)).isSome
```

The returned membership program is expressed in the original presentation and
is accepted by `checkWord`. Different presentations can be compared as
subgroups rather than by generator-array equality. Left cosets are used
throughout; for a nonnormal subgroup they must not be interchanged with right
cosets.

For graph automorphisms, constructing a group from known automorphism
generators proves only that subgroup. The graph-isomorphism completeness
certificate is the additional boundary needed to identify it with the whole
automorphism group.

```lean
def cyclicA : Group 4 := Group.ofGenerators #[rotation]
def cyclicB : Group 4 := Group.ofGenerators #[rotation.inv]
#guard cyclicA.sameGroup cyclicB

def swap3 : Perm 3 := ⟨#v[1, 0, 2], by decide, by decide⟩
def cycle3 : Perm 3 := ⟨#v[1, 2, 0], by decide, by decide⟩
def symmetric3 : Group 3 :=
  Group.ofGenerators #[swap3, cycle3]
def pointFixer : Group 3 := symmetric3.stabilizer 2

example : pointFixer.IsSubgroup symmetric3 := by
  intro p hp
  exact (symmetric3.mem_stabilizer 2 p).mp hp |>.1

#guard (symmetric3.leftCosetsWith 3 pointFixer (by
  intro p hp
  exact (symmetric3.mem_stabilizer 2 p).mp hp |>.1)).isOk
```

# Actions, transporters, blocks, and element access

Finite actions retain their domain ordering. Images record the induced
generator permutations; kernels are accepted only after checking the complete
domain and every generator action. This is the kernel-checking boundary: a
generator map alone does not prove an action law or a final kernel.

```lean
def opposite := polygon.blocks [(0, 2)]
#guard opposite.blockSize 0 = 2

def oppositeAction := polygon.blockAction opposite
  (polygon.blocks_invariant [(0, 2)]) 2
#guard oppositeAction.isOk

def source : Vector Bool 4 := #v[true, true, false, false]
def target : Vector Bool 4 := #v[false, true, true, false]
#guard (polygon.setTransporter? source target).isSome

def rankRoundTrip : Bool :=
  match polygon.unrank? 5 with
  | none => false
  | some p => (polygon.rank p).val == 5

#guard rankRoundTrip
```

# Normal structure and products

The complete derived-series result retains and checks every derived subgroup.
The four-point imprimitive `C₂ wr C₂` action exposes both factor embeddings and
has order eight.

```lean
def symmetric4 : Group 4 := Group.ofGenerators
  #[⟨#v[1, 0, 2, 3], by decide, by decide⟩, rotation]
def derivedOrders :=
  symmetric4.derivedSeries.certificate.orders symmetric4
#guard derivedOrders = [24, 12, 4, 1]

def c2Swap : Perm 2 := ⟨#v[1, 0], by decide, by decide⟩
def c2 : Group 2 := Group.ofGenerators #[c2Swap]
def c2wr2 := c2.wreathProduct c2 (by decide)
#guard c2wr2.order = 8
#guard c2wr2.generators.size = 3

def c2Element : Element c2 :=
  ⟨c2Swap, .generator (by simp [c2])⟩
def baseCopy :=
  WreathProduct.copy c2 (by decide) 0 c2Element
def topCopy :=
  WreathProduct.inr c2 (by decide) c2Element
#guard baseCopy != topCopy
def baseTopIsId : Bool :=
  WreathProduct.top (by decide) baseCopy == Element.id c2
#guard baseTopIsId
#guard WreathProduct.top (by decide) topCopy = c2Element

end HexPermGroupChapter
```

# The Mathieu group M11 in the kernel

The Mathieu group `M11` is generated by an 11-cycle and a product of two
4-cycles. Stated with Mathlib's types and cycle notation, its order is proved
by {name}`Hex.PermGroup.Kernel.Tactic.permGroup`, the `perm_group` tactic:

```lean
namespace HexPermGroupM11

def σ : Equiv.Perm (Fin 11) :=
  c[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
def τ : Equiv.Perm (Fin 11) :=
  c[2, 6, 10, 7] * c[3, 9, 4, 5]

theorem card_m11 : Nat.card (Subgroup.closure
    ({c[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      c[2, 6, 10, 7] * c[3, 9, 4, 5]} :
      Set (Equiv.Perm (Fin 11)))) = 7920 := by
  perm_group

end HexPermGroupM11
```

The tactic runs the compiled producer {name}`Hex.PermGroup.Kernel.certify`,
which builds a stabilizer chain with {name}`Hex.PermGroup.Group.ofGenerators`
and keeps the levels whose orbit has more than one point. For `M11` there are
four, with orbits of 11, 10, 9 and 8 points:

```lean
open Hex Hex.PermGroup HexPermGroupM11 in
def m11Certificate : Kernel.Certificate :=
  let S := #[Perm.ofEquiv σ, Perm.ofEquiv τ]
  match Kernel.certify S with
  | .ok c => c
  | .error _ => []

#eval m11Certificate.map (·.size)
#eval Hex.PermGroup.Kernel.order m11Certificate
```

Each level stores its generators, its orbit, a transversal and its inverses as
packed natural numbers. The kernel check recomputes every Schreier generator of
every level and sifts it through the later levels. Here is one, the element
`t⁻¹ * s * t` for the first generator `s` and the second orbit point of the
first level, sifting to the identity:

```lean
open Hex.PermGroup.Kernel in
#eval
  let W := width 11
  match m11Certificate with
  | L :: rest =>
    sift 11 W (ident 11 W) rest (schreier 11 W L 0 1)
  | [] => false
```

The theorem that turns an accepted check into the Mathlib order is
{name}`Hex.PermGroup.Kernel.card_closure`:

{docstring Hex.PermGroup.Kernel.card_closure}

The kernel does not evaluate the compiled chain of
{name}`Hex.PermGroup.Group.ofGenerators`. That chain has a level for every point
and stores permutations as vectors of `Fin n`, which the kernel reads by walking
lists, so replaying it costs a number of reduction steps that grows quickly
with the degree. The kernel certificate packs each permutation into one natural
number, keeps only the nontrivial levels, and stores the inverses it needs.
For this example, measured on `chungus2` on 2026-09-28, each run alone:

| check | kernel time | peak memory |
|---|---|---|
| replay of the compiled chain by `checkChain` | 28.3 s | 5.8 GB |
| {name}`Hex.PermGroup.Kernel.check` | 0.1 s | 0.24 GB |

The report `reports/20260928-perm-group-kernel-replay-sizing.md` gives the same
comparison for the Mathieu groups, `J2`, `HS`, `McL` and `Co3`.

# Incomplete results

Construction, enumeration, actions, search, normal structure, and products
have bounded entry points. A limit is checked before the corresponding work.
An exhausted search can retain a proved subgroup lower bound, and a term-capped
derived series can retain a checked prefix. Neither result supplies a negative
answer. Producer meters and replay limits are separate so certificate checking
never consumes or inherits a producer's unused allowance.
